// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// augur_subsample_cpp
NumericMatrix augur_subsample_cpp(S4 mat, IntegerVector cols);
RcppExport SEXP _scop_augur_subsample_cpp(SEXP matSEXP, SEXP colsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type mat(matSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cols(colsSEXP);
    rcpp_result_gen = Rcpp::wrap(augur_subsample_cpp(mat, cols));
    return rcpp_result_gen;
END_RCPP
}
// bayesprism_gibbs_initial_cpp
List bayesprism_gibbs_initial_cpp(NumericMatrix mixture, NumericMatrix phi, IntegerVector gibbs_idx, double alpha, int seed, int n_threads);
RcppExport SEXP _scop_bayesprism_gibbs_initial_cpp(SEXP mixtureSEXP, SEXP phiSEXP, SEXP gibbs_idxSEXP, SEXP alphaSEXP, SEXP seedSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mixture(mixtureSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type gibbs_idx(gibbs_idxSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(bayesprism_gibbs_initial_cpp(mixture, phi, gibbs_idx, alpha, seed, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// bayesprism_gibbs_final_cpp
List bayesprism_gibbs_final_cpp(NumericMatrix mixture, NumericMatrix phi, IntegerVector gibbs_idx, double alpha, int seed, int n_threads);
RcppExport SEXP _scop_bayesprism_gibbs_final_cpp(SEXP mixtureSEXP, SEXP phiSEXP, SEXP gibbs_idxSEXP, SEXP alphaSEXP, SEXP seedSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mixture(mixtureSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type gibbs_idx(gibbs_idxSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(bayesprism_gibbs_final_cpp(mixture, phi, gibbs_idx, alpha, seed, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// cibersort_cpp
List cibersort_cpp(NumericMatrix signature, NumericMatrix mixture, int perm, bool QN, bool absolute, int n_threads, int seed, bool verbose);
RcppExport SEXP _scop_cibersort_cpp(SEXP signatureSEXP, SEXP mixtureSEXP, SEXP permSEXP, SEXP QNSEXP, SEXP absoluteSEXP, SEXP n_threadsSEXP, SEXP seedSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type signature(signatureSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mixture(mixtureSEXP);
    Rcpp::traits::input_parameter< int >::type perm(permSEXP);
    Rcpp::traits::input_parameter< bool >::type QN(QNSEXP);
    Rcpp::traits::input_parameter< bool >::type absolute(absoluteSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(cibersort_cpp(signature, mixture, perm, QN, absolute, n_threads, seed, verbose));
    return rcpp_result_gen;
END_RCPP
}
// classification_metrics
List classification_metrics(CharacterVector predicted, CharacterVector truth, CharacterVector classes, double rare_threshold);
RcppExport SEXP _scop_classification_metrics(SEXP predictedSEXP, SEXP truthSEXP, SEXP classesSEXP, SEXP rare_thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type predicted(predictedSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type truth(truthSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type classes(classesSEXP);
    Rcpp::traits::input_parameter< double >::type rare_threshold(rare_thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(classification_metrics(predicted, truth, classes, rare_threshold));
    return rcpp_result_gen;
END_RCPP
}
// cytospace_assign
List cytospace_assign(NumericMatrix sc_expr, NumericMatrix st_expr, IntegerVector spot_capacities, int seed, bool upstream_tie_break, bool verbose);
RcppExport SEXP _scop_cytospace_assign(SEXP sc_exprSEXP, SEXP st_exprSEXP, SEXP spot_capacitiesSEXP, SEXP seedSEXP, SEXP upstream_tie_breakSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type sc_expr(sc_exprSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type st_expr(st_exprSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type spot_capacities(spot_capacitiesSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type upstream_tie_break(upstream_tie_breakSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(cytospace_assign(sc_expr, st_expr, spot_capacities, seed, upstream_tie_break, verbose));
    return rcpp_result_gen;
END_RCPP
}
// cytotrace2_ensemble_predict
List cytotrace2_ensemble_predict(const arma::mat& rank_data, const arma::mat& log2_data, const List& parameter_dict, int cores);
RcppExport SEXP _scop_cytotrace2_ensemble_predict(SEXP rank_dataSEXP, SEXP log2_dataSEXP, SEXP parameter_dictSEXP, SEXP coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type rank_data(rank_dataSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type log2_data(log2_dataSEXP);
    Rcpp::traits::input_parameter< const List& >::type parameter_dict(parameter_dictSEXP);
    Rcpp::traits::input_parameter< int >::type cores(coresSEXP);
    rcpp_result_gen = Rcpp::wrap(cytotrace2_ensemble_predict(rank_data, log2_data, parameter_dict, cores));
    return rcpp_result_gen;
END_RCPP
}
// cytotrace2_diffusion_smooth
arma::vec cytotrace2_diffusion_smooth(const arma::mat& log2_data, const arma::vec& raw_scores, const IntegerVector& smooth_groups);
RcppExport SEXP _scop_cytotrace2_diffusion_smooth(SEXP log2_dataSEXP, SEXP raw_scoresSEXP, SEXP smooth_groupsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type log2_data(log2_dataSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type raw_scores(raw_scoresSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type smooth_groups(smooth_groupsSEXP);
    rcpp_result_gen = Rcpp::wrap(cytotrace2_diffusion_smooth(log2_data, raw_scores, smooth_groups));
    return rcpp_result_gen;
END_RCPP
}
// cytotrace2_bin_data
List cytotrace2_bin_data(const arma::vec& smoothed_scores, const IntegerVector& categories, const StringVector& category_labels);
RcppExport SEXP _scop_cytotrace2_bin_data(SEXP smoothed_scoresSEXP, SEXP categoriesSEXP, SEXP category_labelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type smoothed_scores(smoothed_scoresSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type categories(categoriesSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type category_labels(category_labelsSEXP);
    rcpp_result_gen = Rcpp::wrap(cytotrace2_bin_data(smoothed_scores, categories, category_labels));
    return rcpp_result_gen;
END_RCPP
}
// cytotrace2_knn_smooth
List cytotrace2_knn_smooth(const arma::mat& pca_coords, const arma::vec& preKNN_scores, const StringVector& preKNN_potency, int cores, int seed);
RcppExport SEXP _scop_cytotrace2_knn_smooth(SEXP pca_coordsSEXP, SEXP preKNN_scoresSEXP, SEXP preKNN_potencySEXP, SEXP coresSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type pca_coords(pca_coordsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type preKNN_scores(preKNN_scoresSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type preKNN_potency(preKNN_potencySEXP);
    Rcpp::traits::input_parameter< int >::type cores(coresSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(cytotrace2_knn_smooth(pca_coords, preKNN_scores, preKNN_potency, cores, seed));
    return rcpp_result_gen;
END_RCPP
}
// cytotrace2_main
List cytotrace2_main(const arma::mat& rank_data, const arma::mat& log2_data, const List& parameter_dict, const IntegerVector& smooth_groups, int cores, int seed, const arma::mat& pca_coords);
RcppExport SEXP _scop_cytotrace2_main(SEXP rank_dataSEXP, SEXP log2_dataSEXP, SEXP parameter_dictSEXP, SEXP smooth_groupsSEXP, SEXP coresSEXP, SEXP seedSEXP, SEXP pca_coordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type rank_data(rank_dataSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type log2_data(log2_dataSEXP);
    Rcpp::traits::input_parameter< const List& >::type parameter_dict(parameter_dictSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type smooth_groups(smooth_groupsSEXP);
    Rcpp::traits::input_parameter< int >::type cores(coresSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type pca_coords(pca_coordsSEXP);
    rcpp_result_gen = Rcpp::wrap(cytotrace2_main(rank_data, log2_data, parameter_dict, smooth_groups, cores, seed, pca_coords));
    return rcpp_result_gen;
END_RCPP
}
// aucell_auc_sparse
NumericMatrix aucell_auc_sparse(S4 expr, List gene_sets, int auc_max_rank, bool norm_auc, int strategy, int algorithm);
RcppExport SEXP _scop_aucell_auc_sparse(SEXP exprSEXP, SEXP gene_setsSEXP, SEXP auc_max_rankSEXP, SEXP norm_aucSEXP, SEXP strategySEXP, SEXP algorithmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type expr(exprSEXP);
    Rcpp::traits::input_parameter< List >::type gene_sets(gene_setsSEXP);
    Rcpp::traits::input_parameter< int >::type auc_max_rank(auc_max_rankSEXP);
    Rcpp::traits::input_parameter< bool >::type norm_auc(norm_aucSEXP);
    Rcpp::traits::input_parameter< int >::type strategy(strategySEXP);
    Rcpp::traits::input_parameter< int >::type algorithm(algorithmSEXP);
    rcpp_result_gen = Rcpp::wrap(aucell_auc_sparse(expr, gene_sets, auc_max_rank, norm_auc, strategy, algorithm));
    return rcpp_result_gen;
END_RCPP
}
// aucell_auc_ranked
NumericMatrix aucell_auc_ranked(NumericMatrix rankings, List gene_sets, int auc_max_rank);
RcppExport SEXP _scop_aucell_auc_ranked(SEXP rankingsSEXP, SEXP gene_setsSEXP, SEXP auc_max_rankSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type rankings(rankingsSEXP);
    Rcpp::traits::input_parameter< List >::type gene_sets(gene_setsSEXP);
    Rcpp::traits::input_parameter< int >::type auc_max_rank(auc_max_rankSEXP);
    rcpp_result_gen = Rcpp::wrap(aucell_auc_ranked(rankings, gene_sets, auc_max_rank));
    return rcpp_result_gen;
END_RCPP
}
// ora_hypergeom
DataFrame ora_hypergeom(CharacterVector genes, CharacterVector term_ids, CharacterVector term_genes, CharacterVector term_name_ids, CharacterVector term_names, int min_size, int max_size);
RcppExport SEXP _scop_ora_hypergeom(SEXP genesSEXP, SEXP term_idsSEXP, SEXP term_genesSEXP, SEXP term_name_idsSEXP, SEXP term_namesSEXP, SEXP min_sizeSEXP, SEXP max_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type genes(genesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type term_ids(term_idsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type term_genes(term_genesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type term_name_ids(term_name_idsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type term_names(term_namesSEXP);
    Rcpp::traits::input_parameter< int >::type min_size(min_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type max_size(max_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(ora_hypergeom(genes, term_ids, term_genes, term_name_ids, term_names, min_size, max_size));
    return rcpp_result_gen;
END_RCPP
}
// module_score_sparse
NumericMatrix module_score_sparse(S4 expr, List feature_sets, List control_sets);
RcppExport SEXP _scop_module_score_sparse(SEXP exprSEXP, SEXP feature_setsSEXP, SEXP control_setsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type expr(exprSEXP);
    Rcpp::traits::input_parameter< List >::type feature_sets(feature_setsSEXP);
    Rcpp::traits::input_parameter< List >::type control_sets(control_setsSEXP);
    rcpp_result_gen = Rcpp::wrap(module_score_sparse(expr, feature_sets, control_sets));
    return rcpp_result_gen;
END_RCPP
}
// proportion_permutation
DataFrame proportion_permutation(IntegerVector sample_ids, IntegerVector cluster_ids, CharacterVector cluster_levels, int n_permutations, double pseudocount, bool verbose);
RcppExport SEXP _scop_proportion_permutation(SEXP sample_idsSEXP, SEXP cluster_idsSEXP, SEXP cluster_levelsSEXP, SEXP n_permutationsSEXP, SEXP pseudocountSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type sample_ids(sample_idsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cluster_ids(cluster_idsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type cluster_levels(cluster_levelsSEXP);
    Rcpp::traits::input_parameter< int >::type n_permutations(n_permutationsSEXP);
    Rcpp::traits::input_parameter< double >::type pseudocount(pseudocountSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(proportion_permutation(sample_ids, cluster_ids, cluster_levels, n_permutations, pseudocount, verbose));
    return rcpp_result_gen;
END_RCPP
}
// ssgsea_rank_dense
NumericMatrix ssgsea_rank_dense(S4 expr, List gene_sets, double alpha, bool normalize);
RcppExport SEXP _scop_ssgsea_rank_dense(SEXP exprSEXP, SEXP gene_setsSEXP, SEXP alphaSEXP, SEXP normalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type expr(exprSEXP);
    Rcpp::traits::input_parameter< List >::type gene_sets(gene_setsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(ssgsea_rank_dense(expr, gene_sets, alpha, normalize));
    return rcpp_result_gen;
END_RCPP
}
// zscore_dense
NumericMatrix zscore_dense(S4 expr, List gene_sets, int min_size, int max_size);
RcppExport SEXP _scop_zscore_dense(SEXP exprSEXP, SEXP gene_setsSEXP, SEXP min_sizeSEXP, SEXP max_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type expr(exprSEXP);
    Rcpp::traits::input_parameter< List >::type gene_sets(gene_setsSEXP);
    Rcpp::traits::input_parameter< int >::type min_size(min_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type max_size(max_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(zscore_dense(expr, gene_sets, min_size, max_size));
    return rcpp_result_gen;
END_RCPP
}
// plage_dense
NumericMatrix plage_dense(S4 expr, List gene_sets, int min_size, int max_size);
RcppExport SEXP _scop_plage_dense(SEXP exprSEXP, SEXP gene_setsSEXP, SEXP min_sizeSEXP, SEXP max_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type expr(exprSEXP);
    Rcpp::traits::input_parameter< List >::type gene_sets(gene_setsSEXP);
    Rcpp::traits::input_parameter< int >::type min_size(min_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type max_size(max_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(plage_dense(expr, gene_sets, min_size, max_size));
    return rcpp_result_gen;
END_RCPP
}
// gsva_gaussian_dense
NumericMatrix gsva_gaussian_dense(S4 expr, List gene_sets, bool max_diff, bool abs_ranking, double tau, int chunk_size);
RcppExport SEXP _scop_gsva_gaussian_dense(SEXP exprSEXP, SEXP gene_setsSEXP, SEXP max_diffSEXP, SEXP abs_rankingSEXP, SEXP tauSEXP, SEXP chunk_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type expr(exprSEXP);
    Rcpp::traits::input_parameter< List >::type gene_sets(gene_setsSEXP);
    Rcpp::traits::input_parameter< bool >::type max_diff(max_diffSEXP);
    Rcpp::traits::input_parameter< bool >::type abs_ranking(abs_rankingSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type chunk_size(chunk_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(gsva_gaussian_dense(expr, gene_sets, max_diff, abs_ranking, tau, chunk_size));
    return rcpp_result_gen;
END_RCPP
}
// gsva_poisson_dense
NumericMatrix gsva_poisson_dense(S4 expr, List gene_sets, bool max_diff, bool abs_ranking, double tau, int chunk_size);
RcppExport SEXP _scop_gsva_poisson_dense(SEXP exprSEXP, SEXP gene_setsSEXP, SEXP max_diffSEXP, SEXP abs_rankingSEXP, SEXP tauSEXP, SEXP chunk_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type expr(exprSEXP);
    Rcpp::traits::input_parameter< List >::type gene_sets(gene_setsSEXP);
    Rcpp::traits::input_parameter< bool >::type max_diff(max_diffSEXP);
    Rcpp::traits::input_parameter< bool >::type abs_ranking(abs_rankingSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type chunk_size(chunk_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(gsva_poisson_dense(expr, gene_sets, max_diff, abs_ranking, tau, chunk_size));
    return rcpp_result_gen;
END_RCPP
}
// knn_topk_cpp
List knn_topk_cpp(NumericMatrix reference, NumericMatrix query, int k, std::string metric, bool exclude_self, int n_threads);
RcppExport SEXP _scop_knn_topk_cpp(SEXP referenceSEXP, SEXP querySEXP, SEXP kSEXP, SEXP metricSEXP, SEXP exclude_selfSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type reference(referenceSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type query(querySEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< std::string >::type metric(metricSEXP);
    Rcpp::traits::input_parameter< bool >::type exclude_self(exclude_selfSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(knn_topk_cpp(reference, query, k, metric, exclude_self, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// wilcox_rank_sum_sparse
NumericVector wilcox_rank_sum_sparse(S4 mat, int n_group1, double min_expression);
RcppExport SEXP _scop_wilcox_rank_sum_sparse(SEXP matSEXP, SEXP n_group1SEXP, SEXP min_expressionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type n_group1(n_group1SEXP);
    Rcpp::traits::input_parameter< double >::type min_expression(min_expressionSEXP);
    rcpp_result_gen = Rcpp::wrap(wilcox_rank_sum_sparse(mat, n_group1, min_expression));
    return rcpp_result_gen;
END_RCPP
}
// wilcox_rank_sum_sparse_all_cells
NumericVector wilcox_rank_sum_sparse_all_cells(S4 mat, int n_group1);
RcppExport SEXP _scop_wilcox_rank_sum_sparse_all_cells(SEXP matSEXP, SEXP n_group1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type n_group1(n_group1SEXP);
    rcpp_result_gen = Rcpp::wrap(wilcox_rank_sum_sparse_all_cells(mat, n_group1));
    return rcpp_result_gen;
END_RCPP
}
// sparse_topk_by_column
List sparse_topk_by_column(S4 mat, int k, bool decreasing);
RcppExport SEXP _scop_sparse_topk_by_column(SEXP matSEXP, SEXP kSEXP, SEXP decreasingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type decreasing(decreasingSEXP);
    rcpp_result_gen = Rcpp::wrap(sparse_topk_by_column(mat, k, decreasing));
    return rcpp_result_gen;
END_RCPP
}
// dense_topk_by_column
List dense_topk_by_column(NumericMatrix mat, int k, bool decreasing);
RcppExport SEXP _scop_dense_topk_by_column(SEXP matSEXP, SEXP kSEXP, SEXP decreasingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type decreasing(decreasingSEXP);
    rcpp_result_gen = Rcpp::wrap(dense_topk_by_column(mat, k, decreasing));
    return rcpp_result_gen;
END_RCPP
}
// paga_connectivities_cpp
List paga_connectivities_cpp(IntegerMatrix knn_idx, IntegerVector groups, int n_groups);
RcppExport SEXP _scop_paga_connectivities_cpp(SEXP knn_idxSEXP, SEXP groupsSEXP, SEXP n_groupsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type knn_idx(knn_idxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< int >::type n_groups(n_groupsSEXP);
    rcpp_result_gen = Rcpp::wrap(paga_connectivities_cpp(knn_idx, groups, n_groups));
    return rcpp_result_gen;
END_RCPP
}
// proportion_bootstrap_log2fd
NumericVector proportion_bootstrap_log2fd(NumericVector v1, NumericVector v2, int n_bootstrap, double pseudocount, bool verbose);
RcppExport SEXP _scop_proportion_bootstrap_log2fd(SEXP v1SEXP, SEXP v2SEXP, SEXP n_bootstrapSEXP, SEXP pseudocountSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type v1(v1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v2(v2SEXP);
    Rcpp::traits::input_parameter< int >::type n_bootstrap(n_bootstrapSEXP);
    Rcpp::traits::input_parameter< double >::type pseudocount(pseudocountSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(proportion_bootstrap_log2fd(v1, v2, n_bootstrap, pseudocount, verbose));
    return rcpp_result_gen;
END_RCPP
}
// proportion_bootstrap_stats
List proportion_bootstrap_stats(NumericVector v1, NumericVector v2, int n_bootstrap, double pseudocount, bool verbose);
RcppExport SEXP _scop_proportion_bootstrap_stats(SEXP v1SEXP, SEXP v2SEXP, SEXP n_bootstrapSEXP, SEXP pseudocountSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type v1(v1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v2(v2SEXP);
    Rcpp::traits::input_parameter< int >::type n_bootstrap(n_bootstrapSEXP);
    Rcpp::traits::input_parameter< double >::type pseudocount(pseudocountSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(proportion_bootstrap_stats(v1, v2, n_bootstrap, pseudocount, verbose));
    return rcpp_result_gen;
END_RCPP
}
// pseudotime_velocity_knn
NumericMatrix pseudotime_velocity_knn(NumericMatrix x_emb, NumericVector pseudotime, IntegerMatrix neighbors, bool normalize);
RcppExport SEXP _scop_pseudotime_velocity_knn(SEXP x_embSEXP, SEXP pseudotimeSEXP, SEXP neighborsSEXP, SEXP normalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x_emb(x_embSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pseudotime(pseudotimeSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type neighbors(neighborsSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(pseudotime_velocity_knn(x_emb, pseudotime, neighbors, normalize));
    return rcpp_result_gen;
END_RCPP
}
// pseudotime_velocity_gradient
NumericMatrix pseudotime_velocity_gradient(NumericMatrix x_emb, NumericVector pseudotime, IntegerMatrix neighbors, double smooth, bool normalize);
RcppExport SEXP _scop_pseudotime_velocity_gradient(SEXP x_embSEXP, SEXP pseudotimeSEXP, SEXP neighborsSEXP, SEXP smoothSEXP, SEXP normalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x_emb(x_embSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pseudotime(pseudotimeSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type neighbors(neighborsSEXP);
    Rcpp::traits::input_parameter< double >::type smooth(smoothSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(pseudotime_velocity_gradient(x_emb, pseudotime, neighbors, smooth, normalize));
    return rcpp_result_gen;
END_RCPP
}
// grnboost_tree
DataFrame grnboost_tree(NumericMatrix expr, IntegerVector regulator_idx, IntegerVector target_idx, int n_rounds, double learning_rate, int max_edges_per_target, int max_depth, double max_features, double subsample, int early_stop_window_length, int random_seed, bool exclude_self);
RcppExport SEXP _scop_grnboost_tree(SEXP exprSEXP, SEXP regulator_idxSEXP, SEXP target_idxSEXP, SEXP n_roundsSEXP, SEXP learning_rateSEXP, SEXP max_edges_per_targetSEXP, SEXP max_depthSEXP, SEXP max_featuresSEXP, SEXP subsampleSEXP, SEXP early_stop_window_lengthSEXP, SEXP random_seedSEXP, SEXP exclude_selfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type expr(exprSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type regulator_idx(regulator_idxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type target_idx(target_idxSEXP);
    Rcpp::traits::input_parameter< int >::type n_rounds(n_roundsSEXP);
    Rcpp::traits::input_parameter< double >::type learning_rate(learning_rateSEXP);
    Rcpp::traits::input_parameter< int >::type max_edges_per_target(max_edges_per_targetSEXP);
    Rcpp::traits::input_parameter< int >::type max_depth(max_depthSEXP);
    Rcpp::traits::input_parameter< double >::type max_features(max_featuresSEXP);
    Rcpp::traits::input_parameter< double >::type subsample(subsampleSEXP);
    Rcpp::traits::input_parameter< int >::type early_stop_window_length(early_stop_window_lengthSEXP);
    Rcpp::traits::input_parameter< int >::type random_seed(random_seedSEXP);
    Rcpp::traits::input_parameter< bool >::type exclude_self(exclude_selfSEXP);
    rcpp_result_gen = Rcpp::wrap(grnboost_tree(expr, regulator_idx, target_idx, n_rounds, learning_rate, max_edges_per_target, max_depth, max_features, subsample, early_stop_window_length, random_seed, exclude_self));
    return rcpp_result_gen;
END_RCPP
}
// scenic_ctx_recovery
NumericMatrix scenic_ctx_recovery(IntegerMatrix ranks, NumericVector weights, int rank_threshold);
RcppExport SEXP _scop_scenic_ctx_recovery(SEXP ranksSEXP, SEXP weightsSEXP, SEXP rank_thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type ranks(ranksSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type rank_threshold(rank_thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(scenic_ctx_recovery(ranks, weights, rank_threshold));
    return rcpp_result_gen;
END_RCPP
}
// scenic_ctx_auc_nes
List scenic_ctx_auc_nes(IntegerMatrix ranks, double nes_threshold, int rank_cutoff);
RcppExport SEXP _scop_scenic_ctx_auc_nes(SEXP ranksSEXP, SEXP nes_thresholdSEXP, SEXP rank_cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type ranks(ranksSEXP);
    Rcpp::traits::input_parameter< double >::type nes_threshold(nes_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type rank_cutoff(rank_cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(scenic_ctx_auc_nes(ranks, nes_threshold, rank_cutoff));
    return rcpp_result_gen;
END_RCPP
}
// scenicplus_region_gene_cor
NumericVector scenicplus_region_gene_cor(NumericMatrix atac_log, NumericMatrix rna_log, IntegerVector region_idx, IntegerVector gene_idx);
RcppExport SEXP _scop_scenicplus_region_gene_cor(SEXP atac_logSEXP, SEXP rna_logSEXP, SEXP region_idxSEXP, SEXP gene_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type atac_log(atac_logSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type rna_log(rna_logSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type region_idx(region_idxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type gene_idx(gene_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(scenicplus_region_gene_cor(atac_log, rna_log, region_idx, gene_idx));
    return rcpp_result_gen;
END_RCPP
}
// scenicplus_triplets_cpp
DataFrame scenicplus_triplets_cpp(CharacterVector tf_gene_tf, CharacterVector tf_gene_target, NumericVector tf_gene_importance, CharacterVector region_gene_region, CharacterVector region_gene_gene, NumericVector region_gene_score, CharacterVector tf_region_tf, CharacterVector tf_region_region, NumericVector tf_region_score);
RcppExport SEXP _scop_scenicplus_triplets_cpp(SEXP tf_gene_tfSEXP, SEXP tf_gene_targetSEXP, SEXP tf_gene_importanceSEXP, SEXP region_gene_regionSEXP, SEXP region_gene_geneSEXP, SEXP region_gene_scoreSEXP, SEXP tf_region_tfSEXP, SEXP tf_region_regionSEXP, SEXP tf_region_scoreSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type tf_gene_tf(tf_gene_tfSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type tf_gene_target(tf_gene_targetSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tf_gene_importance(tf_gene_importanceSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type region_gene_region(region_gene_regionSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type region_gene_gene(region_gene_geneSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type region_gene_score(region_gene_scoreSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type tf_region_tf(tf_region_tfSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type tf_region_region(tf_region_regionSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tf_region_score(tf_region_scoreSEXP);
    rcpp_result_gen = Rcpp::wrap(scenicplus_triplets_cpp(tf_gene_tf, tf_gene_target, tf_gene_importance, region_gene_region, region_gene_gene, region_gene_score, tf_region_tf, tf_region_region, tf_region_score));
    return rcpp_result_gen;
END_RCPP
}
// scvelo_stochastic_embedding_cpp
List scvelo_stochastic_embedding_cpp(NumericMatrix spliced, NumericMatrix unspliced, IntegerMatrix knn_idx, NumericMatrix embedding);
RcppExport SEXP _scop_scvelo_stochastic_embedding_cpp(SEXP splicedSEXP, SEXP unsplicedSEXP, SEXP knn_idxSEXP, SEXP embeddingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type spliced(splicedSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type unspliced(unsplicedSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type knn_idx(knn_idxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type embedding(embeddingSEXP);
    rcpp_result_gen = Rcpp::wrap(scvelo_stochastic_embedding_cpp(spliced, unspliced, knn_idx, embedding));
    return rcpp_result_gen;
END_RCPP
}
// sctenifold_pcnet_covariance_raw
NumericMatrix sctenifold_pcnet_covariance_raw(NumericMatrix x, int n_comp, int ncv, int maxit, double tol, int n_threads);
RcppExport SEXP _scop_sctenifold_pcnet_covariance_raw(SEXP xSEXP, SEXP n_compSEXP, SEXP ncvSEXP, SEXP maxitSEXP, SEXP tolSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n_comp(n_compSEXP);
    Rcpp::traits::input_parameter< int >::type ncv(ncvSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(sctenifold_pcnet_covariance_raw(x, n_comp, ncv, maxit, tol, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// sctenifold_pcnet_covariance_sparse
S4 sctenifold_pcnet_covariance_sparse(NumericMatrix x, int n_comp, bool scale_scores, bool symmetric, double q, int ncv, int maxit, double tol, int n_threads);
RcppExport SEXP _scop_sctenifold_pcnet_covariance_sparse(SEXP xSEXP, SEXP n_compSEXP, SEXP scale_scoresSEXP, SEXP symmetricSEXP, SEXP qSEXP, SEXP ncvSEXP, SEXP maxitSEXP, SEXP tolSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n_comp(n_compSEXP);
    Rcpp::traits::input_parameter< bool >::type scale_scores(scale_scoresSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type ncv(ncvSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(sctenifold_pcnet_covariance_sparse(x, n_comp, scale_scores, symmetric, q, ncv, maxit, tol, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// sctenifold_tensor_decomposition
NumericMatrix sctenifold_tensor_decomposition(List x_list, List init_u, int max_iter, double tol, bool verbose);
RcppExport SEXP _scop_sctenifold_tensor_decomposition(SEXP x_listSEXP, SEXP init_uSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x_list(x_listSEXP);
    Rcpp::traits::input_parameter< List >::type init_u(init_uSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(sctenifold_tensor_decomposition(x_list, init_u, max_iter, tol, verbose));
    return rcpp_result_gen;
END_RCPP
}
// sctenifold_strict_direction
NumericMatrix sctenifold_strict_direction(NumericMatrix x, double lambda);
RcppExport SEXP _scop_sctenifold_strict_direction(SEXP xSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(sctenifold_strict_direction(x, lambda));
    return rcpp_result_gen;
END_RCPP
}
// sctenifold_manifold_matrix
NumericMatrix sctenifold_manifold_matrix(NumericMatrix x, NumericMatrix y);
RcppExport SEXP _scop_sctenifold_manifold_matrix(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(sctenifold_manifold_matrix(x, y));
    return rcpp_result_gen;
END_RCPP
}
// sctenifold_pair_distances
NumericVector sctenifold_pair_distances(NumericMatrix aligned);
RcppExport SEXP _scop_sctenifold_pair_distances(SEXP alignedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type aligned(alignedSEXP);
    rcpp_result_gen = Rcpp::wrap(sctenifold_pair_distances(aligned));
    return rcpp_result_gen;
END_RCPP
}
// scibet_fit_predict
List scibet_fit_predict(NumericMatrix ref, NumericMatrix query, IntegerVector labels, int n_labels, int n_top, int additional_per_label);
RcppExport SEXP _scop_scibet_fit_predict(SEXP refSEXP, SEXP querySEXP, SEXP labelsSEXP, SEXP n_labelsSEXP, SEXP n_topSEXP, SEXP additional_per_labelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type ref(refSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type query(querySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< int >::type n_labels(n_labelsSEXP);
    Rcpp::traits::input_parameter< int >::type n_top(n_topSEXP);
    Rcpp::traits::input_parameter< int >::type additional_per_label(additional_per_labelSEXP);
    rcpp_result_gen = Rcpp::wrap(scibet_fit_predict(ref, query, labels, n_labels, n_top, additional_per_label));
    return rcpp_result_gen;
END_RCPP
}
// scibet_fit_predict_sparse
List scibet_fit_predict_sparse(S4 ref, S4 query, IntegerVector labels, int n_labels, int n_top, int additional_per_label);
RcppExport SEXP _scop_scibet_fit_predict_sparse(SEXP refSEXP, SEXP querySEXP, SEXP labelsSEXP, SEXP n_labelsSEXP, SEXP n_topSEXP, SEXP additional_per_labelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type ref(refSEXP);
    Rcpp::traits::input_parameter< S4 >::type query(querySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< int >::type n_labels(n_labelsSEXP);
    Rcpp::traits::input_parameter< int >::type n_top(n_topSEXP);
    Rcpp::traits::input_parameter< int >::type additional_per_label(additional_per_labelSEXP);
    rcpp_result_gen = Rcpp::wrap(scibet_fit_predict_sparse(ref, query, labels, n_labels, n_top, additional_per_label));
    return rcpp_result_gen;
END_RCPP
}
// scibet_predict
NumericMatrix scibet_predict(NumericMatrix query, NumericMatrix core, IntegerVector feature_index);
RcppExport SEXP _scop_scibet_predict(SEXP querySEXP, SEXP coreSEXP, SEXP feature_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type query(querySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type core(coreSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type feature_index(feature_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(scibet_predict(query, core, feature_index));
    return rcpp_result_gen;
END_RCPP
}
// scaleC
List scaleC(Eigen::MatrixXd X);
RcppExport SEXP _scop_scaleC(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(scaleC(X));
    return rcpp_result_gen;
END_RCPP
}
// OmegaC
List OmegaC(Eigen::MatrixXd& Omega, Eigen::VectorXi& sgn);
RcppExport SEXP _scop_OmegaC(SEXP OmegaSEXP, SEXP sgnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd& >::type Omega(OmegaSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi& >::type sgn(sgnSEXP);
    rcpp_result_gen = Rcpp::wrap(OmegaC(Omega, sgn));
    return rcpp_result_gen;
END_RCPP
}
// OmegaSC
List OmegaSC(Eigen::SparseMatrix<double>& OmegaS, Eigen::VectorXi& sgn);
RcppExport SEXP _scop_OmegaSC(SEXP OmegaSSEXP, SEXP sgnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::SparseMatrix<double>& >::type OmegaS(OmegaSSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi& >::type sgn(sgnSEXP);
    rcpp_result_gen = Rcpp::wrap(OmegaSC(OmegaS, sgn));
    return rcpp_result_gen;
END_RCPP
}
// maxLambdaLmC
double maxLambdaLmC(Eigen::MatrixXd X, Eigen::VectorXd y, double alpha, Eigen::VectorXd wbeta, int N0, int p);
RcppExport SEXP _scop_maxLambdaLmC(SEXP XSEXP, SEXP ySEXP, SEXP alphaSEXP, SEXP wbetaSEXP, SEXP N0SEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type wbeta(wbetaSEXP);
    Rcpp::traits::input_parameter< int >::type N0(N0SEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(maxLambdaLmC(X, y, alpha, wbeta, N0, p));
    return rcpp_result_gen;
END_RCPP
}
// cvTrimLmC
Eigen::VectorXd cvTrimLmC(Eigen::VectorXd beta, int nn, int nn2, Eigen::VectorXi loco, Eigen::MatrixXd XF, Eigen::VectorXd yF, int NF, double a0);
RcppExport SEXP _scop_cvTrimLmC(SEXP betaSEXP, SEXP nnSEXP, SEXP nn2SEXP, SEXP locoSEXP, SEXP XFSEXP, SEXP yFSEXP, SEXP NFSEXP, SEXP a0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type nn(nnSEXP);
    Rcpp::traits::input_parameter< int >::type nn2(nn2SEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type loco(locoSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type XF(XFSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type yF(yFSEXP);
    Rcpp::traits::input_parameter< int >::type NF(NFSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    rcpp_result_gen = Rcpp::wrap(cvTrimLmC(beta, nn, nn2, loco, XF, yF, NF, a0));
    return rcpp_result_gen;
END_RCPP
}
// EnetLmC
List EnetLmC(Eigen::MatrixXd X, Eigen::VectorXd y, double alpha, Eigen::VectorXd lambda, int nlambda, int ilambda, Eigen::VectorXd wbeta, int p, int N0, double thresh, int maxit, double thresh2);
RcppExport SEXP _scop_EnetLmC(SEXP XSEXP, SEXP ySEXP, SEXP alphaSEXP, SEXP lambdaSEXP, SEXP nlambdaSEXP, SEXP ilambdaSEXP, SEXP wbetaSEXP, SEXP pSEXP, SEXP N0SEXP, SEXP threshSEXP, SEXP maxitSEXP, SEXP thresh2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type nlambda(nlambdaSEXP);
    Rcpp::traits::input_parameter< int >::type ilambda(ilambdaSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type wbeta(wbetaSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type N0(N0SEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type thresh2(thresh2SEXP);
    rcpp_result_gen = Rcpp::wrap(EnetLmC(X, y, alpha, lambda, nlambda, ilambda, wbeta, p, N0, thresh, maxit, thresh2));
    return rcpp_result_gen;
END_RCPP
}
// cvEnetLmC
List cvEnetLmC(Eigen::MatrixXd X, Eigen::VectorXd y, double alpha, Eigen::VectorXd lambda, int nlambda, Eigen::VectorXd wbeta, int N, int p, double thresh, int maxit, Eigen::MatrixXd XF, Eigen::VectorXd yF, int NF, double thresh2);
RcppExport SEXP _scop_cvEnetLmC(SEXP XSEXP, SEXP ySEXP, SEXP alphaSEXP, SEXP lambdaSEXP, SEXP nlambdaSEXP, SEXP wbetaSEXP, SEXP NSEXP, SEXP pSEXP, SEXP threshSEXP, SEXP maxitSEXP, SEXP XFSEXP, SEXP yFSEXP, SEXP NFSEXP, SEXP thresh2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type nlambda(nlambdaSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type wbeta(wbetaSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type XF(XFSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type yF(yFSEXP);
    Rcpp::traits::input_parameter< int >::type NF(NFSEXP);
    Rcpp::traits::input_parameter< double >::type thresh2(thresh2SEXP);
    rcpp_result_gen = Rcpp::wrap(cvEnetLmC(X, y, alpha, lambda, nlambda, wbeta, N, p, thresh, maxit, XF, yF, NF, thresh2));
    return rcpp_result_gen;
END_RCPP
}
// NetLmC
List NetLmC(Eigen::MatrixXd& X, Eigen::VectorXd& y, double alpha, Eigen::VectorXd lambda, int nlambda, int ilambda, Eigen::VectorXd wbeta, Eigen::SparseMatrix<double>& Omega, Eigen::MatrixXd loc, Eigen::VectorXi nadj, int p, int N0, double thresh, int maxit, double thresh2);
RcppExport SEXP _scop_NetLmC(SEXP XSEXP, SEXP ySEXP, SEXP alphaSEXP, SEXP lambdaSEXP, SEXP nlambdaSEXP, SEXP ilambdaSEXP, SEXP wbetaSEXP, SEXP OmegaSEXP, SEXP locSEXP, SEXP nadjSEXP, SEXP pSEXP, SEXP N0SEXP, SEXP threshSEXP, SEXP maxitSEXP, SEXP thresh2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type nlambda(nlambdaSEXP);
    Rcpp::traits::input_parameter< int >::type ilambda(ilambdaSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type wbeta(wbetaSEXP);
    Rcpp::traits::input_parameter< Eigen::SparseMatrix<double>& >::type Omega(OmegaSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type loc(locSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type nadj(nadjSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type N0(N0SEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type thresh2(thresh2SEXP);
    rcpp_result_gen = Rcpp::wrap(NetLmC(X, y, alpha, lambda, nlambda, ilambda, wbeta, Omega, loc, nadj, p, N0, thresh, maxit, thresh2));
    return rcpp_result_gen;
END_RCPP
}
// cvNetLmC
List cvNetLmC(Eigen::MatrixXd& X, Eigen::VectorXd& y, double alpha, Eigen::VectorXd lambda, int nlambda, Eigen::VectorXd wbeta, Eigen::SparseMatrix<double>& Omega, Eigen::MatrixXd loc, Eigen::VectorXi nadj, int N, int p, double thresh, int maxit, Eigen::MatrixXd XF, Eigen::VectorXd yF, int NF, double thresh2);
RcppExport SEXP _scop_cvNetLmC(SEXP XSEXP, SEXP ySEXP, SEXP alphaSEXP, SEXP lambdaSEXP, SEXP nlambdaSEXP, SEXP wbetaSEXP, SEXP OmegaSEXP, SEXP locSEXP, SEXP nadjSEXP, SEXP NSEXP, SEXP pSEXP, SEXP threshSEXP, SEXP maxitSEXP, SEXP XFSEXP, SEXP yFSEXP, SEXP NFSEXP, SEXP thresh2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type nlambda(nlambdaSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type wbeta(wbetaSEXP);
    Rcpp::traits::input_parameter< Eigen::SparseMatrix<double>& >::type Omega(OmegaSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type loc(locSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type nadj(nadjSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type XF(XFSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type yF(yFSEXP);
    Rcpp::traits::input_parameter< int >::type NF(NFSEXP);
    Rcpp::traits::input_parameter< double >::type thresh2(thresh2SEXP);
    rcpp_result_gen = Rcpp::wrap(cvNetLmC(X, y, alpha, lambda, nlambda, wbeta, Omega, loc, nadj, N, p, thresh, maxit, XF, yF, NF, thresh2));
    return rcpp_result_gen;
END_RCPP
}
// maxLambdaCoxC
double maxLambdaCoxC(Eigen::MatrixXd X, Eigen::VectorXd tevent, int N, Eigen::VectorXi nevent, Eigen::VectorXi nevent1, Eigen::VectorXi loc1, int n, double alpha, Eigen::VectorXd wbeta, int N0, int p);
RcppExport SEXP _scop_maxLambdaCoxC(SEXP XSEXP, SEXP teventSEXP, SEXP NSEXP, SEXP neventSEXP, SEXP nevent1SEXP, SEXP loc1SEXP, SEXP nSEXP, SEXP alphaSEXP, SEXP wbetaSEXP, SEXP N0SEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type tevent(teventSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type nevent(neventSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type nevent1(nevent1SEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type loc1(loc1SEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type wbeta(wbetaSEXP);
    Rcpp::traits::input_parameter< int >::type N0(N0SEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(maxLambdaCoxC(X, tevent, N, nevent, nevent1, loc1, n, alpha, wbeta, N0, p));
    return rcpp_result_gen;
END_RCPP
}
// pletaCm
double pletaCm(Eigen::VectorXd& xb, Eigen::VectorXd& exb, Eigen::VectorXi& nevent, Eigen::VectorXi& nevent1, Eigen::VectorXi& loc1, int& n, int& ifast, int& itwo);
RcppExport SEXP _scop_pletaCm(SEXP xbSEXP, SEXP exbSEXP, SEXP neventSEXP, SEXP nevent1SEXP, SEXP loc1SEXP, SEXP nSEXP, SEXP ifastSEXP, SEXP itwoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type xb(xbSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type exb(exbSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi& >::type nevent(neventSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi& >::type nevent1(nevent1SEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi& >::type loc1(loc1SEXP);
    Rcpp::traits::input_parameter< int& >::type n(nSEXP);
    Rcpp::traits::input_parameter< int& >::type ifast(ifastSEXP);
    Rcpp::traits::input_parameter< int& >::type itwo(itwoSEXP);
    rcpp_result_gen = Rcpp::wrap(pletaCm(xb, exb, nevent, nevent1, loc1, n, ifast, itwo));
    return rcpp_result_gen;
END_RCPP
}
// cvTrimCoxC
Eigen::VectorXd cvTrimCoxC(Eigen::VectorXd beta, int nn, int nn2, Eigen::VectorXi loco, Eigen::MatrixXd XF, int NF, Eigen::VectorXi neventF, Eigen::VectorXi nevent1F, Eigen::VectorXi loc1F, int nF, Eigen::MatrixXd X, int N, Eigen::VectorXi nevent, Eigen::VectorXi nevent1, Eigen::VectorXi loc1, int n, int ifast, int itwo);
RcppExport SEXP _scop_cvTrimCoxC(SEXP betaSEXP, SEXP nnSEXP, SEXP nn2SEXP, SEXP locoSEXP, SEXP XFSEXP, SEXP NFSEXP, SEXP neventFSEXP, SEXP nevent1FSEXP, SEXP loc1FSEXP, SEXP nFSEXP, SEXP XSEXP, SEXP NSEXP, SEXP neventSEXP, SEXP nevent1SEXP, SEXP loc1SEXP, SEXP nSEXP, SEXP ifastSEXP, SEXP itwoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type nn(nnSEXP);
    Rcpp::traits::input_parameter< int >::type nn2(nn2SEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type loco(locoSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type XF(XFSEXP);
    Rcpp::traits::input_parameter< int >::type NF(NFSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type neventF(neventFSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type nevent1F(nevent1FSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type loc1F(loc1FSEXP);
    Rcpp::traits::input_parameter< int >::type nF(nFSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type nevent(neventSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type nevent1(nevent1SEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type loc1(loc1SEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type ifast(ifastSEXP);
    Rcpp::traits::input_parameter< int >::type itwo(itwoSEXP);
    rcpp_result_gen = Rcpp::wrap(cvTrimCoxC(beta, nn, nn2, loco, XF, NF, neventF, nevent1F, loc1F, nF, X, N, nevent, nevent1, loc1, n, ifast, itwo));
    return rcpp_result_gen;
END_RCPP
}
// EnetCoxC
List EnetCoxC(Eigen::MatrixXd X, Eigen::VectorXd tevent, double alpha, Eigen::VectorXd lambda, int nlambda, int ilambda, Eigen::VectorXd wbeta, int N, Eigen::VectorXi nevent, Eigen::VectorXi nevent1, Eigen::VectorXi loc1, int n, int p, int N0, double thresh, int maxit, int ifast);
RcppExport SEXP _scop_EnetCoxC(SEXP XSEXP, SEXP teventSEXP, SEXP alphaSEXP, SEXP lambdaSEXP, SEXP nlambdaSEXP, SEXP ilambdaSEXP, SEXP wbetaSEXP, SEXP NSEXP, SEXP neventSEXP, SEXP nevent1SEXP, SEXP loc1SEXP, SEXP nSEXP, SEXP pSEXP, SEXP N0SEXP, SEXP threshSEXP, SEXP maxitSEXP, SEXP ifastSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type tevent(teventSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type nlambda(nlambdaSEXP);
    Rcpp::traits::input_parameter< int >::type ilambda(ilambdaSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type wbeta(wbetaSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type nevent(neventSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type nevent1(nevent1SEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type loc1(loc1SEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type N0(N0SEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< int >::type ifast(ifastSEXP);
    rcpp_result_gen = Rcpp::wrap(EnetCoxC(X, tevent, alpha, lambda, nlambda, ilambda, wbeta, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast));
    return rcpp_result_gen;
END_RCPP
}
// cvEnetCoxC
List cvEnetCoxC(Eigen::MatrixXd X, Eigen::VectorXd tevent, double alpha, Eigen::VectorXd lambda, int nlambda, Eigen::VectorXd wbeta, int N, Eigen::VectorXi nevent, Eigen::VectorXi nevent1, Eigen::VectorXi loc1, int n, int p, int N0, double thresh, int maxit, int ifast, Eigen::MatrixXd XF, int NF, Eigen::VectorXi neventF, Eigen::VectorXi nevent1F, Eigen::VectorXi loc1F, int nF);
RcppExport SEXP _scop_cvEnetCoxC(SEXP XSEXP, SEXP teventSEXP, SEXP alphaSEXP, SEXP lambdaSEXP, SEXP nlambdaSEXP, SEXP wbetaSEXP, SEXP NSEXP, SEXP neventSEXP, SEXP nevent1SEXP, SEXP loc1SEXP, SEXP nSEXP, SEXP pSEXP, SEXP N0SEXP, SEXP threshSEXP, SEXP maxitSEXP, SEXP ifastSEXP, SEXP XFSEXP, SEXP NFSEXP, SEXP neventFSEXP, SEXP nevent1FSEXP, SEXP loc1FSEXP, SEXP nFSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type tevent(teventSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type nlambda(nlambdaSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type wbeta(wbetaSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type nevent(neventSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type nevent1(nevent1SEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type loc1(loc1SEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type N0(N0SEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< int >::type ifast(ifastSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type XF(XFSEXP);
    Rcpp::traits::input_parameter< int >::type NF(NFSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type neventF(neventFSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type nevent1F(nevent1FSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type loc1F(loc1FSEXP);
    Rcpp::traits::input_parameter< int >::type nF(nFSEXP);
    rcpp_result_gen = Rcpp::wrap(cvEnetCoxC(X, tevent, alpha, lambda, nlambda, wbeta, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast, XF, NF, neventF, nevent1F, loc1F, nF));
    return rcpp_result_gen;
END_RCPP
}
// NetCoxC
List NetCoxC(Eigen::MatrixXd& X, Eigen::VectorXd tevent, double alpha, Eigen::VectorXd lambda, int nlambda, int ilambda, Eigen::VectorXd wbeta, Eigen::SparseMatrix<double>& Omega, Eigen::MatrixXd loc, Eigen::VectorXi nadj, int N, Eigen::VectorXi nevent, Eigen::VectorXi nevent1, Eigen::VectorXi loc1, int n, int p, int N0, double thresh, int maxit, int ifast);
RcppExport SEXP _scop_NetCoxC(SEXP XSEXP, SEXP teventSEXP, SEXP alphaSEXP, SEXP lambdaSEXP, SEXP nlambdaSEXP, SEXP ilambdaSEXP, SEXP wbetaSEXP, SEXP OmegaSEXP, SEXP locSEXP, SEXP nadjSEXP, SEXP NSEXP, SEXP neventSEXP, SEXP nevent1SEXP, SEXP loc1SEXP, SEXP nSEXP, SEXP pSEXP, SEXP N0SEXP, SEXP threshSEXP, SEXP maxitSEXP, SEXP ifastSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type tevent(teventSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type nlambda(nlambdaSEXP);
    Rcpp::traits::input_parameter< int >::type ilambda(ilambdaSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type wbeta(wbetaSEXP);
    Rcpp::traits::input_parameter< Eigen::SparseMatrix<double>& >::type Omega(OmegaSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type loc(locSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type nadj(nadjSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type nevent(neventSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type nevent1(nevent1SEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type loc1(loc1SEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type N0(N0SEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< int >::type ifast(ifastSEXP);
    rcpp_result_gen = Rcpp::wrap(NetCoxC(X, tevent, alpha, lambda, nlambda, ilambda, wbeta, Omega, loc, nadj, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast));
    return rcpp_result_gen;
END_RCPP
}
// cvNetCoxC
List cvNetCoxC(Eigen::MatrixXd& X, Eigen::VectorXd tevent, double alpha, Eigen::VectorXd lambda, int nlambda, Eigen::VectorXd wbeta, Eigen::SparseMatrix<double>& Omega, Eigen::MatrixXd loc, Eigen::VectorXi nadj, int N, Eigen::VectorXi nevent, Eigen::VectorXi nevent1, Eigen::VectorXi loc1, int n, int p, int N0, double thresh, int maxit, int ifast, Eigen::MatrixXd XF, int NF, Eigen::VectorXi neventF, Eigen::VectorXi nevent1F, Eigen::VectorXi loc1F, int nF);
RcppExport SEXP _scop_cvNetCoxC(SEXP XSEXP, SEXP teventSEXP, SEXP alphaSEXP, SEXP lambdaSEXP, SEXP nlambdaSEXP, SEXP wbetaSEXP, SEXP OmegaSEXP, SEXP locSEXP, SEXP nadjSEXP, SEXP NSEXP, SEXP neventSEXP, SEXP nevent1SEXP, SEXP loc1SEXP, SEXP nSEXP, SEXP pSEXP, SEXP N0SEXP, SEXP threshSEXP, SEXP maxitSEXP, SEXP ifastSEXP, SEXP XFSEXP, SEXP NFSEXP, SEXP neventFSEXP, SEXP nevent1FSEXP, SEXP loc1FSEXP, SEXP nFSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type tevent(teventSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type nlambda(nlambdaSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type wbeta(wbetaSEXP);
    Rcpp::traits::input_parameter< Eigen::SparseMatrix<double>& >::type Omega(OmegaSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type loc(locSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type nadj(nadjSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type nevent(neventSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type nevent1(nevent1SEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type loc1(loc1SEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type N0(N0SEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< int >::type ifast(ifastSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type XF(XFSEXP);
    Rcpp::traits::input_parameter< int >::type NF(NFSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type neventF(neventFSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type nevent1F(nevent1FSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type loc1F(loc1FSEXP);
    Rcpp::traits::input_parameter< int >::type nF(nFSEXP);
    rcpp_result_gen = Rcpp::wrap(cvNetCoxC(X, tevent, alpha, lambda, nlambda, wbeta, Omega, loc, nadj, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast, XF, NF, neventF, nevent1F, loc1F, nF));
    return rcpp_result_gen;
END_RCPP
}
// maxLambdaLogC
double maxLambdaLogC(Eigen::MatrixXd X, Eigen::VectorXd Z, double alpha, Eigen::VectorXd wbeta, int N0, int p);
RcppExport SEXP _scop_maxLambdaLogC(SEXP XSEXP, SEXP ZSEXP, SEXP alphaSEXP, SEXP wbetaSEXP, SEXP N0SEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type wbeta(wbetaSEXP);
    Rcpp::traits::input_parameter< int >::type N0(N0SEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(maxLambdaLogC(X, Z, alpha, wbeta, N0, p));
    return rcpp_result_gen;
END_RCPP
}
// cvTrimLogC
Eigen::VectorXd cvTrimLogC(Eigen::VectorXd beta, int nn, int nn2, Eigen::VectorXi loco, Eigen::MatrixXd XF, Eigen::VectorXd yF, int NF, double threshP);
RcppExport SEXP _scop_cvTrimLogC(SEXP betaSEXP, SEXP nnSEXP, SEXP nn2SEXP, SEXP locoSEXP, SEXP XFSEXP, SEXP yFSEXP, SEXP NFSEXP, SEXP threshPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type nn(nnSEXP);
    Rcpp::traits::input_parameter< int >::type nn2(nn2SEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type loco(locoSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type XF(XFSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type yF(yFSEXP);
    Rcpp::traits::input_parameter< int >::type NF(NFSEXP);
    Rcpp::traits::input_parameter< double >::type threshP(threshPSEXP);
    rcpp_result_gen = Rcpp::wrap(cvTrimLogC(beta, nn, nn2, loco, XF, yF, NF, threshP));
    return rcpp_result_gen;
END_RCPP
}
// EnetLogC
List EnetLogC(Eigen::MatrixXd X, Eigen::VectorXd y, double alpha, Eigen::VectorXd lambda, int nlambda, int ilambda, Eigen::ArrayXd wbeta, Eigen::ArrayXd wbetai, int p, int N0, double thresh, int maxit, double threshP);
RcppExport SEXP _scop_EnetLogC(SEXP XSEXP, SEXP ySEXP, SEXP alphaSEXP, SEXP lambdaSEXP, SEXP nlambdaSEXP, SEXP ilambdaSEXP, SEXP wbetaSEXP, SEXP wbetaiSEXP, SEXP pSEXP, SEXP N0SEXP, SEXP threshSEXP, SEXP maxitSEXP, SEXP threshPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type nlambda(nlambdaSEXP);
    Rcpp::traits::input_parameter< int >::type ilambda(ilambdaSEXP);
    Rcpp::traits::input_parameter< Eigen::ArrayXd >::type wbeta(wbetaSEXP);
    Rcpp::traits::input_parameter< Eigen::ArrayXd >::type wbetai(wbetaiSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type N0(N0SEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type threshP(threshPSEXP);
    rcpp_result_gen = Rcpp::wrap(EnetLogC(X, y, alpha, lambda, nlambda, ilambda, wbeta, wbetai, p, N0, thresh, maxit, threshP));
    return rcpp_result_gen;
END_RCPP
}
// cvEnetLogC
List cvEnetLogC(Eigen::MatrixXd X, Eigen::VectorXd y, double alpha, Eigen::VectorXd lambda, int nlambda, Eigen::ArrayXd wbeta, Eigen::ArrayXd wbetai, int p, int N0, double thresh, int maxit, Eigen::MatrixXd XF, Eigen::VectorXd yF, int NF, double threshP);
RcppExport SEXP _scop_cvEnetLogC(SEXP XSEXP, SEXP ySEXP, SEXP alphaSEXP, SEXP lambdaSEXP, SEXP nlambdaSEXP, SEXP wbetaSEXP, SEXP wbetaiSEXP, SEXP pSEXP, SEXP N0SEXP, SEXP threshSEXP, SEXP maxitSEXP, SEXP XFSEXP, SEXP yFSEXP, SEXP NFSEXP, SEXP threshPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type nlambda(nlambdaSEXP);
    Rcpp::traits::input_parameter< Eigen::ArrayXd >::type wbeta(wbetaSEXP);
    Rcpp::traits::input_parameter< Eigen::ArrayXd >::type wbetai(wbetaiSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type N0(N0SEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type XF(XFSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type yF(yFSEXP);
    Rcpp::traits::input_parameter< int >::type NF(NFSEXP);
    Rcpp::traits::input_parameter< double >::type threshP(threshPSEXP);
    rcpp_result_gen = Rcpp::wrap(cvEnetLogC(X, y, alpha, lambda, nlambda, wbeta, wbetai, p, N0, thresh, maxit, XF, yF, NF, threshP));
    return rcpp_result_gen;
END_RCPP
}
// NetLogC
List NetLogC(Eigen::MatrixXd X, Eigen::VectorXd y, double alpha, Eigen::VectorXd lambda, int nlambda, int ilambda, Eigen::ArrayXd wbeta, Eigen::ArrayXd wbetai, Eigen::SparseMatrix<double>& Omega, Eigen::MatrixXd loc, Eigen::VectorXi nadj, int p, int N0, double thresh, int maxit, double threshP);
RcppExport SEXP _scop_NetLogC(SEXP XSEXP, SEXP ySEXP, SEXP alphaSEXP, SEXP lambdaSEXP, SEXP nlambdaSEXP, SEXP ilambdaSEXP, SEXP wbetaSEXP, SEXP wbetaiSEXP, SEXP OmegaSEXP, SEXP locSEXP, SEXP nadjSEXP, SEXP pSEXP, SEXP N0SEXP, SEXP threshSEXP, SEXP maxitSEXP, SEXP threshPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type nlambda(nlambdaSEXP);
    Rcpp::traits::input_parameter< int >::type ilambda(ilambdaSEXP);
    Rcpp::traits::input_parameter< Eigen::ArrayXd >::type wbeta(wbetaSEXP);
    Rcpp::traits::input_parameter< Eigen::ArrayXd >::type wbetai(wbetaiSEXP);
    Rcpp::traits::input_parameter< Eigen::SparseMatrix<double>& >::type Omega(OmegaSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type loc(locSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type nadj(nadjSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type N0(N0SEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type threshP(threshPSEXP);
    rcpp_result_gen = Rcpp::wrap(NetLogC(X, y, alpha, lambda, nlambda, ilambda, wbeta, wbetai, Omega, loc, nadj, p, N0, thresh, maxit, threshP));
    return rcpp_result_gen;
END_RCPP
}
// cvNetLogC
List cvNetLogC(Eigen::MatrixXd X, Eigen::VectorXd y, double alpha, Eigen::VectorXd lambda, int nlambda, Eigen::ArrayXd wbeta, Eigen::ArrayXd wbetai, Eigen::SparseMatrix<double>& Omega, Eigen::MatrixXd loc, Eigen::VectorXi nadj, int p, int N0, double thresh, int maxit, Eigen::MatrixXd XF, Eigen::VectorXd yF, int NF, double threshP);
RcppExport SEXP _scop_cvNetLogC(SEXP XSEXP, SEXP ySEXP, SEXP alphaSEXP, SEXP lambdaSEXP, SEXP nlambdaSEXP, SEXP wbetaSEXP, SEXP wbetaiSEXP, SEXP OmegaSEXP, SEXP locSEXP, SEXP nadjSEXP, SEXP pSEXP, SEXP N0SEXP, SEXP threshSEXP, SEXP maxitSEXP, SEXP XFSEXP, SEXP yFSEXP, SEXP NFSEXP, SEXP threshPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type nlambda(nlambdaSEXP);
    Rcpp::traits::input_parameter< Eigen::ArrayXd >::type wbeta(wbetaSEXP);
    Rcpp::traits::input_parameter< Eigen::ArrayXd >::type wbetai(wbetaiSEXP);
    Rcpp::traits::input_parameter< Eigen::SparseMatrix<double>& >::type Omega(OmegaSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type loc(locSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type nadj(nadjSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type N0(N0SEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type XF(XFSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type yF(yFSEXP);
    Rcpp::traits::input_parameter< int >::type NF(NFSEXP);
    Rcpp::traits::input_parameter< double >::type threshP(threshPSEXP);
    rcpp_result_gen = Rcpp::wrap(cvNetLogC(X, y, alpha, lambda, nlambda, wbeta, wbetai, Omega, loc, nadj, p, N0, thresh, maxit, XF, yF, NF, threshP));
    return rcpp_result_gen;
END_RCPP
}
// scissor_gaussian_net_fit_cpp
List scissor_gaussian_net_fit_cpp(Eigen::MatrixXd x, Eigen::VectorXd y, Eigen::SparseMatrix<double> omega, double alpha, Nullable<NumericVector> lambda, int nlambda, Nullable<IntegerVector> foldid, bool inzero, bool isd, double thresh, int maxit, double threshP);
RcppExport SEXP _scop_scissor_gaussian_net_fit_cpp(SEXP xSEXP, SEXP ySEXP, SEXP omegaSEXP, SEXP alphaSEXP, SEXP lambdaSEXP, SEXP nlambdaSEXP, SEXP foldidSEXP, SEXP inzeroSEXP, SEXP isdSEXP, SEXP threshSEXP, SEXP maxitSEXP, SEXP threshPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type y(ySEXP);
    Rcpp::traits::input_parameter< Eigen::SparseMatrix<double> >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type nlambda(nlambdaSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type foldid(foldidSEXP);
    Rcpp::traits::input_parameter< bool >::type inzero(inzeroSEXP);
    Rcpp::traits::input_parameter< bool >::type isd(isdSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type threshP(threshPSEXP);
    rcpp_result_gen = Rcpp::wrap(scissor_gaussian_net_fit_cpp(x, y, omega, alpha, lambda, nlambda, foldid, inzero, isd, thresh, maxit, threshP));
    return rcpp_result_gen;
END_RCPP
}
// scissor_binomial_net_fit_cpp
List scissor_binomial_net_fit_cpp(Eigen::MatrixXd x, Eigen::VectorXd y, Eigen::SparseMatrix<double> omega, double alpha, Nullable<NumericVector> lambda, int nlambda, Nullable<IntegerVector> foldid, bool inzero, bool isd, double thresh, int maxit, double threshP);
RcppExport SEXP _scop_scissor_binomial_net_fit_cpp(SEXP xSEXP, SEXP ySEXP, SEXP omegaSEXP, SEXP alphaSEXP, SEXP lambdaSEXP, SEXP nlambdaSEXP, SEXP foldidSEXP, SEXP inzeroSEXP, SEXP isdSEXP, SEXP threshSEXP, SEXP maxitSEXP, SEXP threshPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type y(ySEXP);
    Rcpp::traits::input_parameter< Eigen::SparseMatrix<double> >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type nlambda(nlambdaSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type foldid(foldidSEXP);
    Rcpp::traits::input_parameter< bool >::type inzero(inzeroSEXP);
    Rcpp::traits::input_parameter< bool >::type isd(isdSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type threshP(threshPSEXP);
    rcpp_result_gen = Rcpp::wrap(scissor_binomial_net_fit_cpp(x, y, omega, alpha, lambda, nlambda, foldid, inzero, isd, thresh, maxit, threshP));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_scop_augur_subsample_cpp", (DL_FUNC) &_scop_augur_subsample_cpp, 2},
    {"_scop_bayesprism_gibbs_initial_cpp", (DL_FUNC) &_scop_bayesprism_gibbs_initial_cpp, 6},
    {"_scop_bayesprism_gibbs_final_cpp", (DL_FUNC) &_scop_bayesprism_gibbs_final_cpp, 6},
    {"_scop_cibersort_cpp", (DL_FUNC) &_scop_cibersort_cpp, 8},
    {"_scop_classification_metrics", (DL_FUNC) &_scop_classification_metrics, 4},
    {"_scop_cytospace_assign", (DL_FUNC) &_scop_cytospace_assign, 6},
    {"_scop_cytotrace2_ensemble_predict", (DL_FUNC) &_scop_cytotrace2_ensemble_predict, 4},
    {"_scop_cytotrace2_diffusion_smooth", (DL_FUNC) &_scop_cytotrace2_diffusion_smooth, 3},
    {"_scop_cytotrace2_bin_data", (DL_FUNC) &_scop_cytotrace2_bin_data, 3},
    {"_scop_cytotrace2_knn_smooth", (DL_FUNC) &_scop_cytotrace2_knn_smooth, 5},
    {"_scop_cytotrace2_main", (DL_FUNC) &_scop_cytotrace2_main, 7},
    {"_scop_aucell_auc_sparse", (DL_FUNC) &_scop_aucell_auc_sparse, 6},
    {"_scop_aucell_auc_ranked", (DL_FUNC) &_scop_aucell_auc_ranked, 3},
    {"_scop_ora_hypergeom", (DL_FUNC) &_scop_ora_hypergeom, 7},
    {"_scop_module_score_sparse", (DL_FUNC) &_scop_module_score_sparse, 3},
    {"_scop_proportion_permutation", (DL_FUNC) &_scop_proportion_permutation, 6},
    {"_scop_ssgsea_rank_dense", (DL_FUNC) &_scop_ssgsea_rank_dense, 4},
    {"_scop_zscore_dense", (DL_FUNC) &_scop_zscore_dense, 4},
    {"_scop_plage_dense", (DL_FUNC) &_scop_plage_dense, 4},
    {"_scop_gsva_gaussian_dense", (DL_FUNC) &_scop_gsva_gaussian_dense, 6},
    {"_scop_gsva_poisson_dense", (DL_FUNC) &_scop_gsva_poisson_dense, 6},
    {"_scop_knn_topk_cpp", (DL_FUNC) &_scop_knn_topk_cpp, 6},
    {"_scop_wilcox_rank_sum_sparse", (DL_FUNC) &_scop_wilcox_rank_sum_sparse, 3},
    {"_scop_wilcox_rank_sum_sparse_all_cells", (DL_FUNC) &_scop_wilcox_rank_sum_sparse_all_cells, 2},
    {"_scop_sparse_topk_by_column", (DL_FUNC) &_scop_sparse_topk_by_column, 3},
    {"_scop_dense_topk_by_column", (DL_FUNC) &_scop_dense_topk_by_column, 3},
    {"_scop_paga_connectivities_cpp", (DL_FUNC) &_scop_paga_connectivities_cpp, 3},
    {"_scop_proportion_bootstrap_log2fd", (DL_FUNC) &_scop_proportion_bootstrap_log2fd, 5},
    {"_scop_proportion_bootstrap_stats", (DL_FUNC) &_scop_proportion_bootstrap_stats, 5},
    {"_scop_pseudotime_velocity_knn", (DL_FUNC) &_scop_pseudotime_velocity_knn, 4},
    {"_scop_pseudotime_velocity_gradient", (DL_FUNC) &_scop_pseudotime_velocity_gradient, 5},
    {"_scop_grnboost_tree", (DL_FUNC) &_scop_grnboost_tree, 12},
    {"_scop_scenic_ctx_recovery", (DL_FUNC) &_scop_scenic_ctx_recovery, 3},
    {"_scop_scenic_ctx_auc_nes", (DL_FUNC) &_scop_scenic_ctx_auc_nes, 3},
    {"_scop_scenicplus_region_gene_cor", (DL_FUNC) &_scop_scenicplus_region_gene_cor, 4},
    {"_scop_scenicplus_triplets_cpp", (DL_FUNC) &_scop_scenicplus_triplets_cpp, 9},
    {"_scop_scvelo_stochastic_embedding_cpp", (DL_FUNC) &_scop_scvelo_stochastic_embedding_cpp, 4},
    {"_scop_sctenifold_pcnet_covariance_raw", (DL_FUNC) &_scop_sctenifold_pcnet_covariance_raw, 6},
    {"_scop_sctenifold_pcnet_covariance_sparse", (DL_FUNC) &_scop_sctenifold_pcnet_covariance_sparse, 9},
    {"_scop_sctenifold_tensor_decomposition", (DL_FUNC) &_scop_sctenifold_tensor_decomposition, 5},
    {"_scop_sctenifold_strict_direction", (DL_FUNC) &_scop_sctenifold_strict_direction, 2},
    {"_scop_sctenifold_manifold_matrix", (DL_FUNC) &_scop_sctenifold_manifold_matrix, 2},
    {"_scop_sctenifold_pair_distances", (DL_FUNC) &_scop_sctenifold_pair_distances, 1},
    {"_scop_scibet_fit_predict", (DL_FUNC) &_scop_scibet_fit_predict, 6},
    {"_scop_scibet_fit_predict_sparse", (DL_FUNC) &_scop_scibet_fit_predict_sparse, 6},
    {"_scop_scibet_predict", (DL_FUNC) &_scop_scibet_predict, 3},
    {"_scop_scaleC", (DL_FUNC) &_scop_scaleC, 1},
    {"_scop_OmegaC", (DL_FUNC) &_scop_OmegaC, 2},
    {"_scop_OmegaSC", (DL_FUNC) &_scop_OmegaSC, 2},
    {"_scop_maxLambdaLmC", (DL_FUNC) &_scop_maxLambdaLmC, 6},
    {"_scop_cvTrimLmC", (DL_FUNC) &_scop_cvTrimLmC, 8},
    {"_scop_EnetLmC", (DL_FUNC) &_scop_EnetLmC, 12},
    {"_scop_cvEnetLmC", (DL_FUNC) &_scop_cvEnetLmC, 14},
    {"_scop_NetLmC", (DL_FUNC) &_scop_NetLmC, 15},
    {"_scop_cvNetLmC", (DL_FUNC) &_scop_cvNetLmC, 17},
    {"_scop_maxLambdaCoxC", (DL_FUNC) &_scop_maxLambdaCoxC, 11},
    {"_scop_pletaCm", (DL_FUNC) &_scop_pletaCm, 8},
    {"_scop_cvTrimCoxC", (DL_FUNC) &_scop_cvTrimCoxC, 18},
    {"_scop_EnetCoxC", (DL_FUNC) &_scop_EnetCoxC, 17},
    {"_scop_cvEnetCoxC", (DL_FUNC) &_scop_cvEnetCoxC, 22},
    {"_scop_NetCoxC", (DL_FUNC) &_scop_NetCoxC, 20},
    {"_scop_cvNetCoxC", (DL_FUNC) &_scop_cvNetCoxC, 25},
    {"_scop_maxLambdaLogC", (DL_FUNC) &_scop_maxLambdaLogC, 6},
    {"_scop_cvTrimLogC", (DL_FUNC) &_scop_cvTrimLogC, 8},
    {"_scop_EnetLogC", (DL_FUNC) &_scop_EnetLogC, 13},
    {"_scop_cvEnetLogC", (DL_FUNC) &_scop_cvEnetLogC, 15},
    {"_scop_NetLogC", (DL_FUNC) &_scop_NetLogC, 16},
    {"_scop_cvNetLogC", (DL_FUNC) &_scop_cvNetLogC, 18},
    {"_scop_scissor_gaussian_net_fit_cpp", (DL_FUNC) &_scop_scissor_gaussian_net_fit_cpp, 12},
    {"_scop_scissor_binomial_net_fit_cpp", (DL_FUNC) &_scop_scissor_binomial_net_fit_cpp, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_scop(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
