#' @title Cluster tree plot
#'
#' @description
#' Visualize how cells move between clusters across multiple Seurat clustering
#' resolutions.
#'
#' @md
#' @inheritParams FeatureDimPlot
#' @param cluster_cols Metadata columns containing clustering results at
#' different resolutions. If `NULL`, columns generated by
#' `Seurat::FindClusters(resolution = c(...))` are detected automatically.
#' @param prefix Optional prefix used to filter automatically detected
#' clustering columns, for example `"RNA_snn"`.
#' @param resolutions Optional numeric vector used to filter automatically
#' detected resolutions.
#' @param edge_threshold Minimum incoming proportion required to draw an edge.
#' Edges below this threshold are still available when `return_data = TRUE`.
#' @param node_palette,node_palcolor Palette used for node colors.
#' @param edge_palette,edge_palcolor Palette used for edge colors.
#' @param node_size Numeric range used for node sizes.
#' @param edge_size Numeric range used for edge widths.
#' @param return_data Whether to return plot data along with the plot.
#'
#' @return A `ggplot`, `patchwork`, list of `ggplot` objects, or a list with
#' plot data when `return_data = TRUE`.
#' @export
#'
#' @examples
#' \dontrun{
#' data(pancreas_sub)
#' pancreas_sub <- standard_scop(pancreas_sub, verbose = FALSE)
#' pancreas_sub <- Seurat::FindClusters(
#'   pancreas_sub,
#'   resolution = seq(0.2, 1, by = 0.2),
#'   verbose = FALSE
#' )
#' ClusterTreePlot(pancreas_sub)
#'
#' ClusterTreePlot(
#'   pancreas_sub,
#'   features = c("Ins1", "Gcg")
#' )
#' }
ClusterTreePlot <- function(
  srt,
  cluster_cols = NULL,
  prefix = NULL,
  resolutions = NULL,
  features = NULL,
  assay = NULL,
  layer = "data",
  edge_threshold = 0,
  node_palette = "Spectral",
  node_palcolor = NULL,
  edge_palette = "YlOrRd",
  edge_palcolor = NULL,
  node_size = c(3, 10),
  edge_size = c(0.25, 1.8),
  label = TRUE,
  label.size = 3,
  label.fg = "black",
  title = "Cluster tree",
  subtitle = NULL,
  xlab = "Resolution",
  ylab = "Cluster",
  legend.position = "right",
  theme_use = "theme_scop",
  theme_args = list(),
  combine = TRUE,
  ncol = NULL,
  return_data = FALSE,
  verbose = TRUE
) {
  if (!inherits(srt, "Seurat")) {
    log_message(
      "{.arg srt} must be a {.cls Seurat} object",
      message_type = "error"
    )
  }
  cluster_info <- clustertree_resolve_cluster_cols(
    srt = srt,
    cluster_cols = cluster_cols,
    prefix = prefix,
    resolutions = resolutions,
    verbose = verbose
  )
  tree_data <- clustertree_build_data(
    meta_data = srt@meta.data,
    cluster_info = cluster_info,
    edge_threshold = edge_threshold
  )

  feature_values <- clustertree_feature_values(
    srt = srt,
    features = features,
    assay = assay,
    layer = layer,
    cluster_cols = cluster_info$column,
    verbose = verbose
  )
  feature_names <- names(feature_values)
  if (length(feature_names) == 0L) {
    plots <- list(
      ClusterTree = clustertree_single_plot(
        tree_data = tree_data,
        feature_name = NULL,
        node_palette = node_palette,
        node_palcolor = node_palcolor,
        edge_palette = edge_palette,
        edge_palcolor = edge_palcolor,
        node_size = node_size,
        edge_size = edge_size,
        label = label,
        label.size = label.size,
        label.fg = label.fg,
        title = title,
        subtitle = subtitle,
        xlab = xlab,
        ylab = ylab,
        legend.position = legend.position,
        theme_use = theme_use,
        theme_args = theme_args
      )
    )
  } else {
    plots <- lapply(feature_names, function(feature_name) {
      plot_data <- tree_data
      plot_data$nodes <- merge(
        plot_data$nodes,
        feature_values[[feature_name]],
        by = "node_id",
        all.x = TRUE,
        sort = FALSE
      )
      plot_data$nodes <- plot_data$nodes[match(tree_data$nodes$node_id, plot_data$nodes$node_id), , drop = FALSE]
      clustertree_single_plot(
        tree_data = plot_data,
        feature_name = feature_name,
        node_palette = node_palette,
        node_palcolor = node_palcolor,
        edge_palette = edge_palette,
        edge_palcolor = edge_palcolor,
        node_size = node_size,
        edge_size = edge_size,
        label = label,
        label.size = label.size,
        label.fg = label.fg,
        title = title %||% "Cluster tree",
        subtitle = subtitle,
        xlab = xlab,
        ylab = ylab,
        legend.position = legend.position,
        theme_use = theme_use,
        theme_args = theme_args
      )
    })
    names(plots) <- feature_names
  }

  plot <- clustertree_combine_plots(
    plots = plots,
    combine = combine,
    ncol = ncol
  )
  if (isTRUE(return_data)) {
    return(list(
      plot = plot,
      nodes = tree_data$nodes,
      edges = tree_data$edges,
      all_edges = tree_data$all_edges,
      cluster_info = cluster_info
    ))
  }
  plot
}

clustertree_resolve_cluster_cols <- function(
  srt,
  cluster_cols = NULL,
  prefix = NULL,
  resolutions = NULL,
  verbose = TRUE
) {
  meta_cols <- colnames(srt@meta.data)
  if (!is.null(cluster_cols)) {
    missing_cols <- setdiff(cluster_cols, meta_cols)
    if (length(missing_cols) > 0L) {
      log_message(
        "{.arg cluster_cols} not found in metadata: {.val {missing_cols}}",
        message_type = "error"
      )
    }
    info <- data.frame(
      column = cluster_cols,
      resolution = clustertree_parse_resolution(cluster_cols),
      stringsAsFactors = FALSE
    )
    info$resolution_label <- clustertree_resolution_label(info$resolution, info$column)
    info$prefix <- sub("_res\\.[^_]+$", "", info$column)
    if (nrow(info) < 2L) {
      log_message(
        "At least two clustering resolution columns are required for {.fn ClusterTreePlot}.",
        message_type = "error"
      )
    }
    return(info)
  }

  detected <- meta_cols[grepl("(_snn|_SNN)_res\\.[0-9]+(\\.[0-9]+)?$", meta_cols)]
  if (!is.null(prefix)) {
    prefix_keep <- vapply(
      prefix,
      function(prefix_i) {
        startsWith(detected, paste0(prefix_i, "_res."))
      },
      logical(length(detected))
    )
    detected <- detected[rowSums(as.matrix(prefix_keep)) > 0L]
  } else if (length(detected) > 0L) {
    detected_prefix <- sub("_res\\.[^_]+$", "", detected)
    if (length(unique(detected_prefix)) > 1L) {
      default_prefix <- paste0(SeuratObject::DefaultAssay(srt), c("_snn", "_SNN"))
      default_prefix <- default_prefix[default_prefix %in% detected_prefix]
      prefix_use <- if (length(default_prefix) > 0L) {
        default_prefix[1L]
      } else {
        prefix_table <- sort(table(detected_prefix), decreasing = TRUE)
        names(prefix_table)[1]
      }
      log_message(
        "Multiple clustering prefixes detected. Use {.val {prefix_use}} for {.fn ClusterTreePlot}. Pass {.arg prefix} to choose another prefix.",
        verbose = verbose
      )
      detected <- detected[detected_prefix == prefix_use]
    }
  }
  if (length(detected) == 0L) {
    log_message(
      "No multi-resolution Seurat clustering columns were found. Run {.fn Seurat::FindClusters} with a numeric vector in {.arg resolution}, or pass {.arg cluster_cols}.",
      message_type = "error"
    )
  }
  info <- data.frame(
    column = detected,
    resolution = clustertree_parse_resolution(detected),
    stringsAsFactors = FALSE
  )
  info <- info[!is.na(info$resolution), , drop = FALSE]
  if (!is.null(resolutions)) {
    resolution_match <- vapply(
      info$resolution,
      function(x) any(abs(x - resolutions) < sqrt(.Machine$double.eps)),
      logical(1)
    )
    info <- info[resolution_match, , drop = FALSE]
  }
  if (nrow(info) < 2L) {
    log_message(
      "At least two clustering resolution columns are required for {.fn ClusterTreePlot}.",
      message_type = "error"
    )
  }
  info <- info[order(info$resolution, info$column), , drop = FALSE]
  info$resolution_label <- clustertree_resolution_label(info$resolution, info$column)
  info$prefix <- sub("_res\\.[^_]+$", "", info$column)
  rownames(info) <- NULL
  info
}

clustertree_parse_resolution <- function(x) {
  suppressWarnings(as.numeric(sub("^.*(_snn|_SNN)_res\\.([0-9]+(\\.[0-9]+)?)$", "\\2", x)))
}

clustertree_resolution_label <- function(resolution, column) {
  ifelse(
    is.na(resolution),
    column,
    format(resolution, trim = TRUE, scientific = FALSE)
  )
}

clustertree_build_data <- function(meta_data, cluster_info, edge_threshold = 0) {
  if (!is.numeric(edge_threshold) || length(edge_threshold) != 1L || is.na(edge_threshold) || edge_threshold < 0) {
    log_message(
      "{.arg edge_threshold} must be a non-negative number",
      message_type = "error"
    )
  }
  clusters <- lapply(cluster_info$column, function(column) {
    values <- meta_data[[column]]
    values <- as.character(values)
    values[is.na(values)] <- NA_character_
    factor(values, levels = clustertree_sort_clusters(unique(values[!is.na(values)])))
  })
  names(clusters) <- cluster_info$column

  nodes <- do.call(rbind, lapply(seq_along(clusters), function(i) {
    cluster <- clusters[[i]]
    counts <- as.data.frame(table(cluster), stringsAsFactors = FALSE)
    counts <- counts[counts$Freq > 0, , drop = FALSE]
    data.frame(
      node_id = paste(cluster_info$column[i], counts$cluster, sep = "::"),
      column = cluster_info$column[i],
      resolution = cluster_info$resolution[i],
      resolution_label = cluster_info$resolution_label[i],
      resolution_index = i,
      cluster = as.character(counts$cluster),
      size = as.numeric(counts$Freq),
      x = i,
      y = NA_real_,
      stringsAsFactors = FALSE
    )
  }))

  edges <- do.call(rbind, lapply(seq_len(length(clusters) - 1L), function(i) {
    from <- clusters[[i]]
    to <- clusters[[i + 1L]]
    keep <- !is.na(from) & !is.na(to)
    tab <- as.data.frame(table(from[keep], to[keep]), stringsAsFactors = FALSE)
    colnames(tab) <- c("from_cluster", "to_cluster", "count")
    tab <- tab[tab$count > 0, , drop = FALSE]
    from_size <- tapply(rep(1, sum(keep)), as.character(from[keep]), sum)
    to_size <- tapply(rep(1, sum(keep)), as.character(to[keep]), sum)
    data.frame(
      from_node = paste(cluster_info$column[i], tab$from_cluster, sep = "::"),
      to_node = paste(cluster_info$column[i + 1L], tab$to_cluster, sep = "::"),
      from_column = cluster_info$column[i],
      to_column = cluster_info$column[i + 1L],
      from_resolution = cluster_info$resolution[i],
      to_resolution = cluster_info$resolution[i + 1L],
      from_cluster = as.character(tab$from_cluster),
      to_cluster = as.character(tab$to_cluster),
      count = as.numeric(tab$count),
      from_size = as.numeric(from_size[as.character(tab$from_cluster)]),
      to_size = as.numeric(to_size[as.character(tab$to_cluster)]),
      stringsAsFactors = FALSE
    )
  }))
  edges$in_prop <- edges$count / edges$to_size
  edges$out_prop <- edges$count / edges$from_size

  nodes <- clustertree_layout_nodes(nodes = nodes, edges = edges)
  all_edges <- clustertree_attach_edge_coords(edges = edges, nodes = nodes)
  visible_edges <- all_edges[all_edges$in_prop >= edge_threshold, , drop = FALSE]
  list(nodes = nodes, edges = visible_edges, all_edges = all_edges)
}

clustertree_sort_clusters <- function(x) {
  x <- as.character(x)
  num <- suppressWarnings(as.numeric(x))
  if (all(!is.na(num))) {
    return(x[order(num, x)])
  }
  x[order(x)]
}

clustertree_layout_nodes <- function(nodes, edges) {
  level_ids <- sort(unique(nodes$resolution_index))
  for (level_id in level_ids) {
    idx <- which(nodes$resolution_index == level_id)
    if (level_id == min(level_ids)) {
      node_order <- idx[order(match(nodes$cluster[idx], clustertree_sort_clusters(nodes$cluster[idx])))]
      nodes$y[node_order] <- rev(seq_along(node_order))
      next
    }
    incoming <- edges[edges$to_node %in% nodes$node_id[idx], , drop = FALSE]
    parent_y <- stats::setNames(nodes$y, nodes$node_id)
    weighted_y <- vapply(nodes$node_id[idx], function(node_id) {
      edge_i <- incoming[incoming$to_node == node_id, , drop = FALSE]
      if (nrow(edge_i) == 0L) {
        return(Inf)
      }
      stats::weighted.mean(parent_y[edge_i$from_node], edge_i$count, na.rm = TRUE)
    }, numeric(1))
    node_order <- idx[order(-weighted_y, match(nodes$cluster[idx], clustertree_sort_clusters(nodes$cluster[idx])))]
    nodes$y[node_order] <- rev(seq_along(node_order))
  }
  nodes
}

clustertree_attach_edge_coords <- function(edges, nodes) {
  node_x <- stats::setNames(nodes$x, nodes$node_id)
  node_y <- stats::setNames(nodes$y, nodes$node_id)
  edges$x <- node_x[edges$from_node]
  edges$y <- node_y[edges$from_node]
  edges$xend <- node_x[edges$to_node]
  edges$yend <- node_y[edges$to_node]
  edges
}

clustertree_feature_values <- function(
  srt,
  features = NULL,
  assay = NULL,
  layer = "data",
  cluster_cols,
  verbose = TRUE
) {
  if (is.null(features)) {
    return(list())
  }
  feature_sets <- clustertree_normalize_features(features)
  assay <- assay %||% SeuratObject::DefaultAssay(srt)
  assay_features <- rownames(srt[[assay]])
  metadata_features <- colnames(srt@meta.data)

  out <- lapply(names(feature_sets), function(feature_name) {
    feature_set <- unique(feature_sets[[feature_name]])
    feature_set <- feature_set[nzchar(feature_set)]
    assay_found <- feature_set[feature_set %in% assay_features]
    metadata_candidates <- intersect(feature_set, metadata_features)
    metadata_found <- metadata_candidates[
      vapply(srt@meta.data[metadata_candidates], is.numeric, logical(1))
    ]
    features_found <- unique(c(assay_found, metadata_found))
    features_drop <- setdiff(feature_set, features_found)
    if (length(features_drop) > 0L) {
      log_message(
        "{.val {features_drop}} are not numeric metadata columns or features of {.cls Seurat}",
        message_type = "warning",
        verbose = verbose
      )
    }
    if (length(features_found) == 0L) {
      return(NULL)
    }

    values <- clustertree_get_feature_set_values(
      srt = srt,
      assay = assay,
      layer = layer,
      assay_features = assay_found,
      metadata_features = metadata_found
    )
    clustertree_aggregate_feature_values(
      values = values,
      meta_data = srt@meta.data,
      cluster_cols = cluster_cols
    )
  })
  names(out) <- names(feature_sets)
  out <- out[!vapply(out, is.null, logical(1))]
  if (length(out) == 0L) {
    log_message(
      "There are no valid marker features present.",
      message_type = "error"
    )
  }
  out
}

clustertree_normalize_features <- function(features) {
  if (is.list(features)) {
    if (is.null(names(features))) {
      names(features) <- rep("", length(features))
    }
    out <- lapply(features, function(x) {
      if (!is.character(x)) {
        log_message(
          "{.arg features} must be a character vector or a list of character vectors",
          message_type = "error"
        )
      }
      unique(as.character(x))
    })
    empty_names <- !nzchar(names(out))
    names(out)[empty_names] <- vapply(
      out[empty_names],
      function(x) paste(x, collapse = "_"),
      character(1)
    )
    return(out)
  }
  if (!is.character(features)) {
    log_message(
      "{.arg features} must be a character vector",
      message_type = "error"
    )
  }
  features <- unique(as.character(features))
  stats::setNames(as.list(features), features)
}

clustertree_get_feature_set_values <- function(
  srt,
  assay,
  layer,
  assay_features,
  metadata_features
) {
  value_list <- list()
  if (length(assay_features) > 0L) {
    expr <- GetAssayData5(srt, assay = assay, layer = layer)[assay_features, , drop = FALSE]
    if (length(assay_features) == 1L) {
      assay_values <- as.numeric(expr[assay_features, ])
    } else {
      assay_values <- Matrix::colMeans(expr)
    }
    names(assay_values) <- colnames(expr)
    value_list$assay <- assay_values
  }
  if (length(metadata_features) > 0L) {
    metadata_values <- as.matrix(srt@meta.data[, metadata_features, drop = FALSE])
    metadata_values <- if (ncol(metadata_values) == 1L) {
      as.numeric(metadata_values[, 1L])
    } else {
      rowMeans(metadata_values, na.rm = TRUE)
    }
    names(metadata_values) <- rownames(srt@meta.data)
    value_list$metadata <- metadata_values
  }
  cells <- Reduce(intersect, lapply(value_list, names))
  cells <- unlist(lapply(value_list, function(x) names(x)[names(x) %in% cells]), use.names = FALSE)
  cells <- unique(cells)
  if (length(value_list) == 1L) {
    return(value_list[[1L]][cells])
  }
  values <- vapply(value_list, function(x) x[cells], numeric(length(cells)))
  stats::setNames(rowMeans(values, na.rm = TRUE), cells)
}

clustertree_aggregate_feature_values <- function(values, meta_data, cluster_cols) {
  cells <- names(values)
  cells <- cells[cells %in% rownames(meta_data)]
  values <- values[cells]
  feature_nodes <- do.call(rbind, lapply(cluster_cols, function(column) {
    cluster <- as.character(meta_data[cells, column, drop = TRUE])
    keep <- !is.na(cluster) & !is.na(values)
    value <- stats::aggregate(
      values[keep],
      by = list(cluster = cluster[keep]),
      FUN = mean,
      na.rm = TRUE
    )
    colnames(value)[2] <- "feature_value"
    value$node_id <- paste(column, value$cluster, sep = "::")
    value[, c("node_id", "feature_value"), drop = FALSE]
  }))
  feature_nodes
}

clustertree_single_plot <- function(
  tree_data,
  feature_name = NULL,
  node_palette = "Spectral",
  node_palcolor = NULL,
  edge_palette = "YlOrRd",
  edge_palcolor = NULL,
  node_size = c(3, 10),
  edge_size = c(0.25, 1.8),
  label = TRUE,
  label.size = 3,
  label.fg = "black",
  title = "Cluster tree",
  subtitle = NULL,
  xlab = "Resolution",
  ylab = "Cluster",
  legend.position = "right",
  theme_use = "theme_scop",
  theme_args = list()
) {
  if (identical(theme_use, "theme_scop")) {
    theme_use <- "theme_this"
  }
  nodes <- tree_data$nodes
  edges <- tree_data$edges
  edge_cols <- palette_colors(
    palette = edge_palette,
    palcolor = edge_palcolor,
    n = 9
  )
  p <- ggplot2::ggplot() +
    ggplot2::geom_segment(
      data = edges,
      ggplot2::aes(
        x = .data$x,
        y = .data$y,
        xend = .data$xend,
        yend = .data$yend,
        linewidth = .data$count,
        color = .data$count,
        alpha = .data$in_prop
      ),
      lineend = "round",
      arrow = grid::arrow(length = grid::unit(0.08, "inches"), type = "closed"),
      show.legend = TRUE
    ) +
    ggplot2::scale_linewidth_continuous(name = "Cells", range = edge_size) +
    ggplot2::scale_color_gradientn(name = "Cells", colours = edge_cols) +
    ggplot2::scale_alpha_continuous(name = "Incoming", range = c(0.15, 0.95)) +
    ggplot2::scale_size_continuous(name = "Cluster size", range = node_size) +
    ggplot2::scale_x_continuous(
      breaks = unique(nodes$x),
      labels = unique(nodes$resolution_label),
      expand = ggplot2::expansion(mult = c(0.08, 0.08))
    ) +
    ggplot2::scale_y_continuous(expand = ggplot2::expansion(mult = c(0.08, 0.08))) +
    ggplot2::labs(
      title = title,
      subtitle = subtitle %||% feature_name,
      x = xlab,
      y = ylab
    )
  if (is.null(feature_name)) {
    node_cols <- palette_colors(
      unique(nodes$resolution_label),
      palette = node_palette,
      palcolor = node_palcolor
    )
    p <- p +
      ggplot2::geom_point(
        data = nodes,
        ggplot2::aes(
          x = .data$x,
          y = .data$y,
          size = .data$size,
          fill = .data$resolution_label
        ),
        shape = 21,
        color = "white",
        stroke = 0.6
      ) +
      ggplot2::scale_fill_manual(name = "Resolution", values = node_cols)
  } else {
    node_cols <- palette_colors(
      palette = node_palette,
      palcolor = node_palcolor,
      n = 9
    )
    p <- p +
      ggplot2::geom_point(
        data = nodes,
        ggplot2::aes(
          x = .data$x,
          y = .data$y,
          size = .data$size,
          fill = .data$feature_value
        ),
        shape = 21,
        color = "white",
        stroke = 0.6
      ) +
      ggplot2::scale_fill_gradientn(
        name = feature_name,
        colours = node_cols,
        na.value = "grey85"
      )
  }
  if (isTRUE(label)) {
    p <- p +
      ggplot2::geom_text(
        data = nodes,
        ggplot2::aes(x = .data$x, y = .data$y, label = .data$cluster),
        size = label.size,
        color = label.fg,
        show.legend = FALSE
      )
  }
  p +
    do.call(theme_use, theme_args) +
    ggplot2::theme(
      legend.position = legend.position,
      panel.grid.minor = ggplot2::element_blank()
    )
}

clustertree_combine_plots <- function(plots, combine = TRUE, ncol = NULL) {
  if (length(plots) == 1L) {
    return(plots[[1L]])
  }
  if (isFALSE(combine)) {
    return(plots)
  }
  check_r("patchwork", verbose = FALSE)
  patchwork::wrap_plots(plotlist = plots, ncol = ncol)
}
