#' @title Cluster tree plot
#'
#' @description
#' Visualize how cells move between clusters across multiple Seurat clustering
#' resolutions. In the default direction, nodes are bottom-aligned so the tree
#' expands from lower left to upper right; the direction can be reversed or
#' transposed. Automatically detected resolutions are ordered numerically;
#' explicit `cluster_cols` keep the supplied order.
#'
#' @md
#' @inheritParams FeatureDimPlot
#' @inheritParams scop-params
#' @param cluster_cols Metadata columns containing clustering results at
#' different resolutions. If `NULL`, columns generated by
#' `Seurat::FindClusters(resolution = c(...))` are detected automatically.
#' @param prefix Optional prefix used to filter automatically detected
#' clustering columns, for example `"RNA_snn"`.
#' @param resolutions Optional numeric vector used to filter automatically
#' detected resolutions.
#' @param edge_threshold Minimum incoming proportion required to draw an edge.
#' Edges below this threshold are still available when `return_data = TRUE`.
#' @param node_palette,node_palcolor Palette used for node colors.
#' @param edge_palette,edge_palcolor Palette used for edge colors.
#' @param node_size Numeric range used for node sizes.
#' @param edge_size Numeric range used for edge widths.
#' @param label Whether to draw cluster IDs inside nodes.
#' @param label.size,label.fg Size and color of cluster-ID labels.
#' `label.fg = "auto"` chooses black or white for each node from its fill.
#' @param family Font family used for node labels, axes, titles, and legends.
#' @param direction Tree direction: `"left-to-right"`, `"right-to-left"`,
#' `"top-to-bottom"`, or `"bottom-to-top"`.
#' @param title Plot title. `NULL` (the default) hides the redundant overall
#' cluster-tree title; feature names are still shown as panel subtitles.
#' @param subtitle Optional plot subtitle. When features are supplied and
#' `subtitle = NULL`, the feature or feature-set name is used.
#' @param xlab,ylab Axis titles.
#' @param legend.position The position of the legend. The default is `"auto"`:
#' horizontal trees place a compact guide row above the panel, aligned to the
#' starting side, while vertical trees place guides on the right. Use
#' `"inside"` to force an in-panel legend.
#' @param theme_use,theme_args Plot theme and additional theme arguments.
#' @param return_data Whether to return plot data along with the plot.
#'
#' @return A `ggplot`, `patchwork`, list of `ggplot` objects, or a list with
#' plot data when `return_data = TRUE`.
#' @export
#'
#' @examples
#' \dontrun{
#' data(pancreas_sub)
#' pancreas_sub <- RunStandardWorkflow(pancreas_sub, verbose = FALSE)
#' pancreas_sub <- Seurat::FindNeighbors(
#'   pancreas_sub,
#'   dims = 1:20,
#'   verbose = FALSE
#' )
#' pancreas_sub <- Seurat::FindClusters(
#'   pancreas_sub,
#'   resolution = seq(0.2, 1, by = 0.2),
#'   verbose = FALSE
#' )
#' ClusterTreePlot(pancreas_sub)
#'
#' ClusterTreePlot(
#'   pancreas_sub,
#'   features = c("Ins1", "Gcg")
#' )
#' }
ClusterTreePlot <- function(
  srt,
  cluster_cols = NULL,
  prefix = NULL,
  resolutions = NULL,
  features = NULL,
  assay = NULL,
  layer = "data",
  edge_threshold = 0,
  node_palette = "Spectral",
  node_palcolor = NULL,
  edge_palette = "YlOrRd",
  edge_palcolor = NULL,
  node_size = c(4, 8.5),
  edge_size = c(0.35, 2),
  label = TRUE,
  label.size = 2.8,
  label.fg = "auto",
  title = NULL,
  subtitle = NULL,
  xlab = "Resolution",
  ylab = "Cluster",
  legend.position = "auto",
  theme_use = "theme_scop",
  theme_args = list(),
  combine = TRUE,
  ncol = NULL,
  return_data = FALSE,
  verbose = TRUE,
  family = "Arial",
  direction = c(
    "left-to-right",
    "right-to-left",
    "top-to-bottom",
    "bottom-to-top"
  )
) {
  if (!inherits(srt, "Seurat")) {
    log_message(
      "{.arg srt} must be a {.cls Seurat} object",
      message_type = "error"
    )
  }
  direction <- match.arg(direction)
  cluster_info <- clustertree_resolve_cluster_cols(
    srt = srt,
    cluster_cols = cluster_cols,
    prefix = prefix,
    resolutions = resolutions,
    verbose = verbose
  )
  tree_data <- clustertree_build_data(
    meta_data = srt@meta.data,
    cluster_info = cluster_info,
    edge_threshold = edge_threshold,
    node_size = node_size
  )
  legend.position <- clustertree_resolve_legend_position(
    legend.position = legend.position,
    nodes = tree_data$nodes,
    direction = direction
  )

  feature_values <- clustertree_feature_values(
    srt = srt,
    features = features,
    assay = assay,
    layer = layer,
    cluster_cols = cluster_info$column,
    verbose = verbose
  )
  feature_names <- names(feature_values)
  if (length(feature_names) == 0L) {
    plots <- list(
      ClusterTree = clustertree_single_plot(
        tree_data = tree_data,
        feature_name = NULL,
        node_palette = node_palette,
        node_palcolor = node_palcolor,
        edge_palette = edge_palette,
        edge_palcolor = edge_palcolor,
        node_size = node_size,
        edge_size = edge_size,
        label = label,
        label.size = label.size,
        label.fg = label.fg,
        family = family,
        title = title,
        subtitle = subtitle,
        xlab = xlab,
        ylab = ylab,
        legend.position = legend.position,
        theme_use = theme_use,
        theme_args = theme_args,
        show_shared_guides = TRUE,
        direction = direction
      )
    )
  } else {
    plots <- lapply(seq_along(feature_names), function(feature_index) {
      feature_name <- feature_names[feature_index]
      plot_data <- tree_data
      plot_data$nodes <- merge(
        plot_data$nodes,
        feature_values[[feature_name]],
        by = "node_id",
        all.x = TRUE,
        sort = FALSE
      )
      plot_data$nodes <- plot_data$nodes[match(tree_data$nodes$node_id, plot_data$nodes$node_id), , drop = FALSE]
      clustertree_single_plot(
        tree_data = plot_data,
        feature_name = feature_name,
        node_palette = node_palette,
        node_palcolor = node_palcolor,
        edge_palette = edge_palette,
        edge_palcolor = edge_palcolor,
        node_size = node_size,
        edge_size = edge_size,
        label = label,
        label.size = label.size,
        label.fg = label.fg,
        family = family,
        title = title,
        subtitle = subtitle,
        xlab = xlab,
        ylab = ylab,
        legend.position = legend.position,
        theme_use = theme_use,
        theme_args = theme_args,
        show_shared_guides = !isTRUE(combine) ||
          length(feature_names) == 1L ||
          feature_index == 1L,
        direction = direction
      )
    })
    names(plots) <- feature_names
  }

  plot <- clustertree_combine_plots(
    plots = plots,
    combine = combine,
    ncol = ncol,
    legend.position = legend.position,
    family = family,
    direction = direction
  )
  if (isTRUE(return_data)) {
    return(list(
      plot = plot,
      nodes = tree_data$nodes,
      edges = tree_data$edges,
      all_edges = tree_data$all_edges,
      cluster_info = cluster_info
    ))
  }
  plot
}

clustertree_resolve_cluster_cols <- function(
  srt,
  cluster_cols = NULL,
  prefix = NULL,
  resolutions = NULL,
  verbose = TRUE
) {
  meta_cols <- colnames(srt@meta.data)
  if (!is.null(cluster_cols)) {
    missing_cols <- setdiff(cluster_cols, meta_cols)
    if (length(missing_cols) > 0L) {
      log_message(
        "{.arg cluster_cols} not found in metadata: {.val {missing_cols}}",
        message_type = "error"
      )
    }
    info <- data.frame(
      column = cluster_cols,
      resolution = clustertree_parse_resolution(cluster_cols),
      stringsAsFactors = FALSE
    )
    info$resolution_label <- clustertree_resolution_label(info$resolution, info$column)
    info$prefix <- sub("_res\\.[^_]+$", "", info$column)
    if (nrow(info) < 2L) {
      log_message(
        "At least two clustering resolution columns are required for {.fn ClusterTreePlot}.",
        message_type = "error"
      )
    }
    return(info)
  }

  detected <- meta_cols[grepl("(_snn|_SNN)_res\\.[0-9]+(\\.[0-9]+)?$", meta_cols)]
  if (!is.null(prefix)) {
    prefix_keep <- vapply(
      prefix,
      function(prefix_i) {
        startsWith(detected, paste0(prefix_i, "_res."))
      },
      logical(length(detected))
    )
    detected <- detected[rowSums(as.matrix(prefix_keep)) > 0L]
  } else if (length(detected) > 0L) {
    detected_prefix <- sub("_res\\.[^_]+$", "", detected)
    if (length(unique(detected_prefix)) > 1L) {
      default_prefix <- paste0(SeuratObject::DefaultAssay(srt), c("_snn", "_SNN"))
      default_prefix <- default_prefix[default_prefix %in% detected_prefix]
      prefix_use <- if (length(default_prefix) > 0L) {
        default_prefix[1L]
      } else {
        prefix_table <- sort(table(detected_prefix), decreasing = TRUE)
        names(prefix_table)[1]
      }
      log_message(
        "Multiple clustering prefixes detected. Use {.val {prefix_use}} for {.fn ClusterTreePlot}. Pass {.arg prefix} to choose another prefix.",
        verbose = verbose
      )
      detected <- detected[detected_prefix == prefix_use]
    }
  }
  if (length(detected) == 0L) {
    log_message(
      "No multi-resolution Seurat clustering columns were found. Run {.fn Seurat::FindClusters} with a numeric vector in {.arg resolution}, or pass {.arg cluster_cols}.",
      message_type = "error"
    )
  }
  info <- data.frame(
    column = detected,
    resolution = clustertree_parse_resolution(detected),
    stringsAsFactors = FALSE
  )
  info <- info[!is.na(info$resolution), , drop = FALSE]
  if (!is.null(resolutions)) {
    resolution_match <- vapply(
      info$resolution,
      function(x) any(abs(x - resolutions) < sqrt(.Machine$double.eps)),
      logical(1)
    )
    info <- info[resolution_match, , drop = FALSE]
  }
  if (nrow(info) < 2L) {
    log_message(
      "At least two clustering resolution columns are required for {.fn ClusterTreePlot}.",
      message_type = "error"
    )
  }
  info <- info[order(info$resolution, info$column), , drop = FALSE]
  info$resolution_label <- clustertree_resolution_label(info$resolution, info$column)
  info$prefix <- sub("_res\\.[^_]+$", "", info$column)
  rownames(info) <- NULL
  info
}

clustertree_parse_resolution <- function(x) {
  suppressWarnings(as.numeric(sub("^.*(_snn|_SNN)_res\\.([0-9]+(\\.[0-9]+)?)$", "\\2", x)))
}

clustertree_resolution_label <- function(resolution, column) {
  ifelse(
    is.na(resolution),
    column,
    format(resolution, trim = TRUE, scientific = FALSE)
  )
}

clustertree_build_data <- function(
  meta_data,
  cluster_info,
  edge_threshold = 0,
  node_size = c(4, 8.5)
) {
  if (!is.numeric(edge_threshold) || length(edge_threshold) != 1L || is.na(edge_threshold) || edge_threshold < 0) {
    log_message(
      "{.arg edge_threshold} must be a non-negative number",
      message_type = "error"
    )
  }
  clusters <- lapply(cluster_info$column, function(column) {
    values <- meta_data[[column]]
    values <- as.character(values)
    values[is.na(values)] <- NA_character_
    factor(values, levels = clustertree_sort_clusters(unique(values[!is.na(values)])))
  })
  names(clusters) <- cluster_info$column

  nodes <- do.call(rbind, lapply(seq_along(clusters), function(i) {
    cluster <- clusters[[i]]
    counts <- as.data.frame(table(cluster), stringsAsFactors = FALSE)
    counts <- counts[counts$Freq > 0, , drop = FALSE]
    data.frame(
      node_id = paste(cluster_info$column[i], counts$cluster, sep = "::"),
      column = cluster_info$column[i],
      resolution = cluster_info$resolution[i],
      resolution_label = cluster_info$resolution_label[i],
      resolution_index = i,
      cluster = as.character(counts$cluster),
      size = as.numeric(counts$Freq),
      x = i,
      y = NA_real_,
      stringsAsFactors = FALSE
    )
  }))

  edges <- do.call(rbind, lapply(seq_len(length(clusters) - 1L), function(i) {
    from <- clusters[[i]]
    to <- clusters[[i + 1L]]
    keep <- !is.na(from) & !is.na(to)
    tab <- as.data.frame(table(from[keep], to[keep]), stringsAsFactors = FALSE)
    colnames(tab) <- c("from_cluster", "to_cluster", "count")
    tab <- tab[tab$count > 0, , drop = FALSE]
    from_size <- tapply(rep(1, sum(keep)), as.character(from[keep]), sum)
    to_size <- tapply(rep(1, sum(keep)), as.character(to[keep]), sum)
    data.frame(
      from_node = paste(cluster_info$column[i], tab$from_cluster, sep = "::"),
      to_node = paste(cluster_info$column[i + 1L], tab$to_cluster, sep = "::"),
      from_column = cluster_info$column[i],
      to_column = cluster_info$column[i + 1L],
      from_resolution = cluster_info$resolution[i],
      to_resolution = cluster_info$resolution[i + 1L],
      from_cluster = as.character(tab$from_cluster),
      to_cluster = as.character(tab$to_cluster),
      count = as.numeric(tab$count),
      from_size = as.numeric(from_size[as.character(tab$from_cluster)]),
      to_size = as.numeric(to_size[as.character(tab$to_cluster)]),
      stringsAsFactors = FALSE
    )
  }))
  edges$in_prop <- edges$count / edges$to_size
  edges$out_prop <- edges$count / edges$from_size

  nodes <- clustertree_layout_nodes(
    nodes = nodes,
    edges = edges,
    node_size = node_size
  )
  all_edges <- clustertree_attach_edge_coords(edges = edges, nodes = nodes)
  visible_edges <- all_edges[all_edges$in_prop >= edge_threshold, , drop = FALSE]
  list(nodes = nodes, edges = visible_edges, all_edges = all_edges)
}

clustertree_sort_clusters <- function(x) {
  x <- as.character(x)
  num <- suppressWarnings(as.numeric(x))
  if (all(!is.na(num))) {
    return(x[order(num, x)])
  }
  x[order(x)]
}

clustertree_layout_nodes <- function(nodes, edges, node_size = c(4, 8.5)) {
  level_ids <- sort(unique(nodes$resolution_index))
  size_limits <- range(nodes$size, na.rm = TRUE)
  for (level_id in level_ids) {
    idx <- which(nodes$resolution_index == level_id)
    if (level_id == min(level_ids)) {
      node_order <- idx[order(match(nodes$cluster[idx], clustertree_sort_clusters(nodes$cluster[idx])))]
      nodes$y[node_order] <- clustertree_anchored_positions(
        sizes = nodes$size[node_order],
        size_limits = size_limits,
        node_size = node_size
      )
      next
    }
    incoming <- edges[edges$to_node %in% nodes$node_id[idx], , drop = FALSE]
    parent_y <- stats::setNames(nodes$y, nodes$node_id)
    weighted_y <- vapply(nodes$node_id[idx], function(node_id) {
      edge_i <- incoming[incoming$to_node == node_id, , drop = FALSE]
      if (nrow(edge_i) == 0L) {
        return(Inf)
      }
      stats::weighted.mean(parent_y[edge_i$from_node], edge_i$count, na.rm = TRUE)
    }, numeric(1))
    node_order <- idx[order(-weighted_y, match(nodes$cluster[idx], clustertree_sort_clusters(nodes$cluster[idx])))]
    nodes$y[node_order] <- clustertree_anchored_positions(
      sizes = nodes$size[node_order],
      size_limits = size_limits,
      node_size = node_size
    )
  }
  nodes
}

clustertree_anchored_positions <- function(
  sizes,
  size_limits,
  node_size = c(4, 8.5),
  padding = 0.18
) {
  n_nodes <- length(sizes)
  if (n_nodes <= 1L) {
    return(0)
  }
  size_span <- diff(size_limits)
  size_scaled <- if (is.finite(size_span) && size_span > 0) {
    (sizes - size_limits[1L]) / size_span
  } else {
    rep(0.5, n_nodes)
  }
  size_scaled <- pmin(1, pmax(0, size_scaled))
  diameters <- node_size[1L] + sqrt(size_scaled) * diff(node_size)
  positive_scale_sizes <- node_size[is.finite(node_size) & node_size > 0]
  baseline <- if (length(positive_scale_sizes) > 0L) {
    min(positive_scale_sizes)
  } else {
    1
  }
  relative_diameters <- diameters / baseline
  gaps <- 0.5 * (
    relative_diameters[-n_nodes] + relative_diameters[-1L]
  ) + padding
  rev(c(0, cumsum(rev(gaps))))
}

clustertree_attach_edge_coords <- function(edges, nodes) {
  node_x <- stats::setNames(nodes$x, nodes$node_id)
  node_y <- stats::setNames(nodes$y, nodes$node_id)
  edges$x <- node_x[edges$from_node]
  edges$y <- node_y[edges$from_node]
  edges$xend <- node_x[edges$to_node]
  edges$yend <- node_y[edges$to_node]
  edges
}

clustertree_feature_values <- function(
  srt,
  features = NULL,
  assay = NULL,
  layer = "data",
  cluster_cols,
  verbose = TRUE
) {
  if (is.null(features)) {
    return(list())
  }
  feature_sets <- clustertree_normalize_features(features)
  assay <- assay %||% SeuratObject::DefaultAssay(srt)
  assay_features <- rownames(srt[[assay]])
  metadata_features <- colnames(srt@meta.data)

  out <- lapply(names(feature_sets), function(feature_name) {
    feature_set <- unique(feature_sets[[feature_name]])
    feature_set <- feature_set[nzchar(feature_set)]
    assay_found <- feature_set[feature_set %in% assay_features]
    metadata_candidates <- intersect(feature_set, metadata_features)
    metadata_found <- metadata_candidates[
      vapply(srt@meta.data[metadata_candidates], is.numeric, logical(1))
    ]
    features_found <- unique(c(assay_found, metadata_found))
    features_drop <- setdiff(feature_set, features_found)
    if (length(features_drop) > 0L) {
      log_message(
        "{.val {features_drop}} are not numeric metadata columns or features of {.cls Seurat}",
        message_type = "warning",
        verbose = verbose
      )
    }
    if (length(features_found) == 0L) {
      return(NULL)
    }

    values <- clustertree_get_feature_set_values(
      srt = srt,
      assay = assay,
      layer = layer,
      assay_features = assay_found,
      metadata_features = metadata_found
    )
    clustertree_aggregate_feature_values(
      values = values,
      meta_data = srt@meta.data,
      cluster_cols = cluster_cols
    )
  })
  names(out) <- names(feature_sets)
  out <- out[!vapply(out, is.null, logical(1))]
  if (length(out) == 0L) {
    log_message(
      "There are no valid marker features present.",
      message_type = "error"
    )
  }
  out
}

clustertree_normalize_features <- function(features) {
  if (is.list(features)) {
    if (is.null(names(features))) {
      names(features) <- rep("", length(features))
    }
    out <- lapply(features, function(x) {
      if (!is.character(x)) {
        log_message(
          "{.arg features} must be a character vector or a list of character vectors",
          message_type = "error"
        )
      }
      unique(as.character(x))
    })
    empty_names <- !nzchar(names(out))
    names(out)[empty_names] <- vapply(
      out[empty_names],
      function(x) paste(x, collapse = "_"),
      character(1)
    )
    return(out)
  }
  if (!is.character(features)) {
    log_message(
      "{.arg features} must be a character vector",
      message_type = "error"
    )
  }
  features <- unique(as.character(features))
  stats::setNames(as.list(features), features)
}

clustertree_get_feature_set_values <- function(
  srt,
  assay,
  layer,
  assay_features,
  metadata_features
) {
  value_list <- list()
  if (length(assay_features) > 0L) {
    expr <- GetAssayData5(srt, assay = assay, layer = layer)[assay_features, , drop = FALSE]
    if (length(assay_features) == 1L) {
      assay_values <- as.numeric(expr[assay_features, ])
    } else {
      assay_values <- Matrix::colMeans(expr)
    }
    names(assay_values) <- colnames(expr)
    value_list$assay <- assay_values
  }
  if (length(metadata_features) > 0L) {
    metadata_values <- as.matrix(srt@meta.data[, metadata_features, drop = FALSE])
    metadata_values <- if (ncol(metadata_values) == 1L) {
      as.numeric(metadata_values[, 1L])
    } else {
      rowMeans(metadata_values, na.rm = TRUE)
    }
    names(metadata_values) <- rownames(srt@meta.data)
    value_list$metadata <- metadata_values
  }
  cells <- Reduce(intersect, lapply(value_list, names))
  cells <- unlist(lapply(value_list, function(x) names(x)[names(x) %in% cells]), use.names = FALSE)
  cells <- unique(cells)
  if (length(value_list) == 1L) {
    return(value_list[[1L]][cells])
  }
  values <- vapply(value_list, function(x) x[cells], numeric(length(cells)))
  stats::setNames(rowMeans(values, na.rm = TRUE), cells)
}

clustertree_aggregate_feature_values <- function(values, meta_data, cluster_cols) {
  cells <- names(values)
  cells <- cells[cells %in% rownames(meta_data)]
  values <- values[cells]
  feature_nodes <- do.call(rbind, lapply(cluster_cols, function(column) {
    cluster <- as.character(meta_data[cells, column, drop = TRUE])
    keep <- !is.na(cluster) & !is.na(values)
    value <- stats::aggregate(
      values[keep],
      by = list(cluster = cluster[keep]),
      FUN = mean,
      na.rm = TRUE
    )
    colnames(value)[2] <- "feature_value"
    value$node_id <- paste(column, value$cluster, sep = "::")
    value[, c("node_id", "feature_value"), drop = FALSE]
  }))
  feature_nodes
}

clustertree_gradient_colors <- function(values, colors, na_color = "grey85") {
  out <- rep(na_color, length(values))
  keep <- is.finite(values)
  if (!any(keep)) {
    return(out)
  }
  value_range <- range(values[keep])
  scaled <- if (diff(value_range) > 0) {
    (values[keep] - value_range[1L]) / diff(value_range)
  } else {
    rep(0.5, sum(keep))
  }
  rgb_values <- grDevices::colorRamp(colors, space = "Lab")(scaled)
  out[keep] <- grDevices::rgb(
    rgb_values[, 1L],
    rgb_values[, 2L],
    rgb_values[, 3L],
    maxColorValue = 255
  )
  out
}

clustertree_contrast_text <- function(fill_colors) {
  fill_colors[is.na(fill_colors) | !nzchar(fill_colors)] <- "grey85"
  rgb_values <- t(grDevices::col2rgb(fill_colors)) / 255
  rgb_linear <- ifelse(
    rgb_values <= 0.04045,
    rgb_values / 12.92,
    ((rgb_values + 0.055) / 1.055)^2.4
  )
  luminance <- 0.2126 * rgb_linear[, 1L] +
    0.7152 * rgb_linear[, 2L] +
    0.0722 * rgb_linear[, 3L]
  contrast_black <- (luminance + 0.05) / 0.05
  contrast_white <- 1.05 / (luminance + 0.05)
  ifelse(contrast_white >= contrast_black, "white", "black")
}

clustertree_single_plot <- function(
  tree_data,
  feature_name = NULL,
  node_palette = "Spectral",
  node_palcolor = NULL,
  edge_palette = "YlOrRd",
  edge_palcolor = NULL,
  node_size = c(4, 8.5),
  edge_size = c(0.35, 2),
  label = TRUE,
  label.size = 2.8,
  label.fg = "auto",
  family = "Arial",
  title = NULL,
  subtitle = NULL,
  xlab = "Resolution",
  ylab = "Cluster",
  legend.position = "inside",
  theme_use = "theme_scop",
  theme_args = list(),
  show_shared_guides = TRUE,
  direction = c(
    "left-to-right",
    "right-to-left",
    "top-to-bottom",
    "bottom-to-top"
  )
) {
  theme_use <- resolve_plot_theme_use(theme_use)
  direction <- match.arg(direction)
  nodes <- tree_data$nodes
  edges <- tree_data$edges
  positive_node_sizes <- node_size[is.finite(node_size) & node_size > 0]
  node_clearance <- if (length(positive_node_sizes) > 0L) {
    max(positive_node_sizes) / (2 * min(positive_node_sizes)) + 0.18
  } else {
    0.5
  }
  edge_cols <- palette_colors(
    palette = edge_palette,
    palcolor = edge_palcolor,
    n = 9
  )
  reverse_resolution <- direction %in% c("right-to-left", "top-to-bottom")
  vertical_tree <- direction %in% c("top-to-bottom", "bottom-to-top")
  resolution_scale <- if (reverse_resolution) {
    ggplot2::scale_x_reverse(
      breaks = unique(nodes$x),
      labels = unique(nodes$resolution_label),
      expand = ggplot2::expansion(mult = c(0.04, 0.07))
    )
  } else {
    ggplot2::scale_x_continuous(
      breaks = unique(nodes$x),
      labels = unique(nodes$resolution_label),
      expand = ggplot2::expansion(mult = c(0.04, 0.07))
    )
  }
  tree_coord <- if (vertical_tree) {
    ggplot2::coord_flip(clip = "off")
  } else {
    ggplot2::coord_cartesian(clip = "off")
  }
  p <- ggplot2::ggplot() +
    ggplot2::geom_segment(
      data = edges,
      ggplot2::aes(
        x = .data$x,
        y = .data$y,
        xend = .data$xend,
        yend = .data$yend,
        linewidth = .data$count,
        color = .data$in_prop
      ),
      alpha = 0.9,
      lineend = "round",
      show.legend = TRUE
    ) +
    ggplot2::scale_linewidth_continuous(
      name = "Cells moved",
      range = edge_size,
      breaks = clustertree_compact_breaks(2),
      guide = if (isTRUE(show_shared_guides)) {
        ggplot2::guide_legend(
          order = 1,
          title.position = "top",
          title.hjust = 0,
          nrow = 1,
          byrow = TRUE,
          override.aes = list(color = "black", alpha = 1)
        )
      } else {
        "none"
      }
    ) +
    ggplot2::scale_color_gradientn(
      name = "Incoming share",
      colours = edge_cols,
      limits = c(0, 1),
      breaks = c(0, 0.5, 1),
      labels = function(x) paste0(round(x * 100), "%"),
      guide = if (isTRUE(show_shared_guides)) {
        clustertree_colorbar_guide(legend.position, order = 2)
      } else {
        "none"
      }
    ) +
    ggplot2::scale_size_continuous(
      name = "Cluster size",
      range = node_size,
      breaks = clustertree_compact_breaks(2),
      guide = if (isTRUE(show_shared_guides)) {
        ggplot2::guide_legend(
          order = 3,
          title.position = "top",
          title.hjust = 0,
          nrow = 1,
          byrow = TRUE,
          override.aes = list(
            fill = "white",
            color = "black",
            alpha = 1,
            stroke = 0.45,
            linewidth = 0,
            linetype = 0
          )
        )
      } else {
        "none"
      }
    ) +
    resolution_scale +
    ggplot2::scale_y_continuous(
      breaks = NULL,
      expand = ggplot2::expansion(
        mult = c(0.035, 0.08),
        add = c(node_clearance, node_clearance)
      )
    ) +
    tree_coord +
    ggplot2::labs(
      title = title,
      subtitle = subtitle %||% feature_name,
      x = xlab,
      y = ylab
    )
  if (is.null(feature_name)) {
    node_cols <- palette_colors(
      unique(nodes$resolution_label),
      palette = node_palette,
      palcolor = node_palcolor
    )
    node_fill <- node_cols[match(
      nodes$resolution_label,
      unique(nodes$resolution_label)
    )]
    p <- p +
      ggplot2::geom_point(
        data = nodes,
        ggplot2::aes(
          x = .data$x,
          y = .data$y,
          size = .data$size,
          fill = .data$resolution_label
        ),
        shape = 21,
        color = "white",
        stroke = 0.8
      ) +
      ggplot2::scale_fill_manual(
        name = "Resolution",
        values = node_cols,
        guide = "none"
      )
  } else {
    node_cols <- palette_colors(
      palette = node_palette,
      palcolor = node_palcolor,
      n = 9
    )
    node_fill <- clustertree_gradient_colors(
      values = nodes$feature_value,
      colors = node_cols,
      na_color = "grey85"
    )
    p <- p +
      ggplot2::geom_point(
        data = nodes,
        ggplot2::aes(
          x = .data$x,
          y = .data$y,
          size = .data$size,
          fill = .data$feature_value
        ),
        shape = 21,
        color = "white",
        stroke = 0.8
      ) +
      ggplot2::scale_fill_gradientn(
        name = if (
          clustertree_is_compact_legend(legend.position) && is.null(subtitle)
        ) {
          NULL
        } else {
          feature_name
        },
        colours = node_cols,
        na.value = "grey85",
        breaks = clustertree_compact_breaks(3),
        guide = clustertree_colorbar_guide(legend.position, order = 4)
      )
  }
  nodes$.label_color <- if (identical(label.fg, "auto")) {
    clustertree_contrast_text(node_fill)
  } else {
    rep_len(as.character(label.fg), nrow(nodes))
  }
  if (isTRUE(label)) {
    for (label_color in unique(nodes$.label_color)) {
      label_nodes <- nodes[nodes$.label_color == label_color, , drop = FALSE]
      p <- p +
        ggplot2::geom_text(
          data = label_nodes,
          ggplot2::aes(x = .data$x, y = .data$y, label = .data$cluster),
          size = label.size,
          color = label_color,
          family = family,
          show.legend = FALSE
        )
    }
  }
  p +
    do.call(theme_use, theme_args) +
    clustertree_legend_theme(
      legend.position,
      family = family,
      direction = direction
    )
}

clustertree_is_horizontal_legend <- function(legend.position) {
  is.character(legend.position) &&
    length(legend.position) == 1L &&
    legend.position %in% c("bottom", "top", "top-left", "top-right")
}

clustertree_is_inside_legend <- function(legend.position) {
  is.character(legend.position) &&
    length(legend.position) == 1L &&
    identical(legend.position, "inside")
}

clustertree_is_corner_legend <- function(legend.position) {
  is.character(legend.position) &&
    length(legend.position) == 1L &&
    legend.position %in% c("top-left", "top-right")
}

clustertree_is_compact_legend <- function(legend.position) {
  clustertree_is_inside_legend(legend.position) ||
    clustertree_is_corner_legend(legend.position)
}

clustertree_resolve_legend_position <- function(
  legend.position,
  nodes = NULL,
  direction = "left-to-right"
) {
  if (!identical(legend.position, "auto")) {
    return(legend.position)
  }
  switch(
    direction,
    "left-to-right" = "top-left",
    "right-to-left" = "top-right",
    "top-to-bottom" = "right",
    "bottom-to-top" = "right",
    "right"
  )
}

clustertree_legend_anchor <- function(direction = "left-to-right") {
  switch(
    direction,
    "left-to-right" = list(
      position = c(0.022, 0.978),
      justification = c(0, 1)
    ),
    "right-to-left" = list(
      position = c(0.978, 0.978),
      justification = c(1, 1)
    ),
    "top-to-bottom" = list(
      position = c(0.978, 0.978),
      justification = c(1, 1)
    ),
    "bottom-to-top" = list(
      position = c(0.978, 0.022),
      justification = c(1, 0)
    ),
    list(position = c(0.022, 0.978), justification = c(0, 1))
  )
}

clustertree_compact_breaks <- function(n = 3L) {
  force(n)
  function(limits) {
    limits <- as.numeric(limits)
    limits <- limits[is.finite(limits)]
    if (length(limits) == 0L) {
      return(numeric())
    }
    limits <- range(limits)
    if (diff(limits) == 0) {
      return(limits[1L])
    }
    breaks <- pretty(limits, n = n)
    breaks <- breaks[breaks >= limits[1L] & breaks <= limits[2L]]
    if (length(breaks) <= n) {
      return(breaks)
    }
    breaks[unique(round(seq(1, length(breaks), length.out = n)))]
  }
}

clustertree_colorbar_guide <- function(legend.position, order = 1) {
  horizontal <- clustertree_is_horizontal_legend(legend.position) ||
    clustertree_is_inside_legend(legend.position)
  corner <- clustertree_is_corner_legend(legend.position)
  ggplot2::guide_colorbar(
    order = order,
    direction = if (horizontal) "horizontal" else "vertical",
    title.position = "top",
    title.hjust = 0,
    barwidth = if (corner) {
      grid::unit(60, "pt")
    } else if (horizontal) {
      grid::unit(74, "pt")
    } else {
      grid::unit(7, "pt")
    },
    barheight = if (horizontal) grid::unit(8, "pt") else grid::unit(48, "pt")
  )
}

clustertree_legend_theme <- function(
  legend.position,
  family = "Arial",
  direction = "left-to-right"
) {
  horizontal <- clustertree_is_horizontal_legend(legend.position)
  inside <- clustertree_is_inside_legend(legend.position)
  corner <- clustertree_is_corner_legend(legend.position)
  compact <- inside || corner
  guide_horizontal <- horizontal || inside
  vertical_tree <- direction %in% c("top-to-bottom", "bottom-to-top")
  legend_anchor <- clustertree_legend_anchor(direction)
  legend_position_use <- if (corner) "top" else legend.position
  corner_justification <- if (identical(legend.position, "top-right")) {
    "right"
  } else {
    "left"
  }
  ggplot2::theme(
    text = ggplot2::element_text(family = family, color = "black"),
    plot.title = ggplot2::element_text(
      family = family,
      face = "bold",
      size = 13,
      color = "black",
      margin = ggplot2::margin(b = 4)
    ),
    plot.subtitle = ggplot2::element_text(
      family = family,
      face = "bold",
      size = 11.5,
      color = "black",
      margin = ggplot2::margin(b = 7)
    ),
    axis.title = ggplot2::element_text(
      family = family,
      face = "plain",
      size = 11,
      color = "black"
    ),
    axis.text.x = if (vertical_tree) {
      ggplot2::element_blank()
    } else {
      ggplot2::element_text(
        family = family,
        size = 10,
        color = "black",
        margin = ggplot2::margin(t = 4)
      )
    },
    legend.position = legend_position_use,
    legend.position.inside = legend_anchor$position,
    legend.direction = if (guide_horizontal) "horizontal" else "vertical",
    legend.box = if (inside) {
      "vertical"
    } else if (corner || horizontal) {
      "horizontal"
    } else {
      "vertical"
    },
    legend.justification = if (inside) {
      legend_anchor$justification
    } else if (corner) {
      corner_justification
    } else if (horizontal) {
      "center"
    } else {
      "top"
    },
    legend.justification.inside = legend_anchor$justification,
    legend.box.just = if (corner) {
      corner_justification
    } else if (inside && legend_anchor$justification[1L] == 1) {
      "right"
    } else if (horizontal) {
      "center"
    } else {
      "left"
    },
    legend.title = ggplot2::element_text(
      family = family,
      face = "bold",
      size = 9.5,
      color = "black"
    ),
    legend.text = ggplot2::element_text(
      family = family,
      size = 8.5,
      color = "black"
    ),
    legend.key.height = grid::unit(14, "pt"),
    legend.key.width = grid::unit(
      if (corner) 20 else if (guide_horizontal) 24 else 16,
      "pt"
    ),
    legend.spacing.x = grid::unit(if (corner) 3 else 5, "pt"),
    legend.spacing.y = grid::unit(if (compact) 1 else 4, "pt"),
    legend.box.spacing = grid::unit(if (compact) 0 else 6, "pt"),
    legend.margin = if (compact) {
      ggplot2::margin(t = 0, r = 0, b = 0, l = 0)
    } else {
      ggplot2::margin(t = 2, r = 2, b = 2, l = 2)
    },
    legend.box.margin = if (compact) {
      ggplot2::margin(
        t = 3,
        r = if (corner) 2 else 4,
        b = 3,
        l = if (corner) 2 else 4
      )
    } else {
      ggplot2::margin(t = 7, r = 5, b = 2, l = 5)
    },
    legend.background = ggplot2::element_blank(),
    legend.box.background = if (inside) {
      ggplot2::element_rect(
        fill = grDevices::adjustcolor("white", alpha.f = 0.96),
        color = NA
      )
    } else {
      ggplot2::element_blank()
    },
    panel.grid = ggplot2::element_blank(),
    panel.border = ggplot2::element_blank(),
    axis.line.x = if (vertical_tree) {
      ggplot2::element_blank()
    } else {
      ggplot2::element_line(color = "black", linewidth = 0.5)
    },
    axis.ticks.x = if (vertical_tree) {
      ggplot2::element_blank()
    } else {
      ggplot2::element_line(color = "black", linewidth = 0.45)
    },
    axis.ticks.length = grid::unit(3, "pt"),
    axis.line.y = if (vertical_tree) {
      ggplot2::element_line(color = "black", linewidth = 0.5)
    } else {
      ggplot2::element_blank()
    },
    axis.text.y = if (vertical_tree) {
      ggplot2::element_text(
        family = family,
        size = 10,
        color = "black",
        margin = ggplot2::margin(r = 4)
      )
    } else {
      ggplot2::element_blank()
    },
    axis.ticks.y = if (vertical_tree) {
      ggplot2::element_line(color = "black", linewidth = 0.45)
    } else {
      ggplot2::element_blank()
    },
    plot.margin = ggplot2::margin(t = 8, r = 12, b = 8, l = 8)
  )
}

clustertree_combine_plots <- function(
  plots,
  combine = TRUE,
  ncol = NULL,
  legend.position = "inside",
  family = "Arial",
  direction = "left-to-right"
) {
  if (length(plots) == 1L) {
    return(plots[[1L]])
  }
  if (isFALSE(combine)) {
    return(plots)
  }
  check_r("patchwork", verbose = FALSE)
  guides_mode <- if (clustertree_is_inside_legend(legend.position)) {
    "keep"
  } else {
    "collect"
  }
  patchwork::wrap_plots(plotlist = plots, ncol = ncol, guides = guides_mode) &
    clustertree_legend_theme(
      legend.position,
      family = family,
      direction = direction
    )
}
