#' @title Plot SCOP CNV results
#'
#' @description
#' Visualize results generated by [RunCNV()] from the unified
#' `srt@tools[[tool_name]]` schema.
#'
#' @md
#' @inheritParams CellDimPlot
#' @inheritParams SpatialSpotPlot
#' @param plot_type Plot type. `"heatmap"` draws a chromosome-ordered CNV
#' heatmap, `"dim"` shows CNV metadata on a reduction, `"spatial"` shows CNV
#' metadata on spatial coordinates, `"bar"` summarizes calls by group, and
#' `"tree"` returns a hierarchical clustering of cells or CNV clusters.
#' @param tool_name Name of the CNV tool bundle in `srt@tools`.
#' @param method Method stored under `srt@tools[[tool_name]]$methods`. If
#' `NULL`, the active method is used.
#' @param value Metadata value used by `"dim"` and `"spatial"` plots. If
#' `NULL`, `CNV_prediction` is preferred when available, otherwise `CNV_score`.
#' @param cluster_tree_by For `plot_type = "tree"`, use `"cell"` or
#' `"cluster"` level profiles.
#' @param palette,palcolor Palette passed to SCOP discrete plots and
#' annotations.
#' @param heatmap_palette,heatmap_palcolor Palette used for CNV heatmap values.
#' @param title,subtitle Plot title and subtitle for ggplot-based views.
#' @param ... Additional parameters forwarded to the underlying plotting
#' function.
#'
#' @return A plot object. For `"heatmap"`, returns a `ComplexHeatmap` object;
#' for `"tree"`, returns an `hclust` object.
#' @export
#'
#' @seealso [RunCNV]
#'
#' @examples
#' \dontrun{
#' srt <- RunCNV(srt, method = "copykat", genome = "hg38")
#'
#' CNVPlot(srt, plot_type = "heatmap", group.by = "CNV_prediction")
#' CNVPlot(srt, plot_type = "dim", value = "CNV_prediction")
#' CNVPlot(srt, plot_type = "dim", value = "CNV_score")
#' CNVPlot(srt, plot_type = "bar", group.by = "seurat_clusters")
#' CNVPlot(srt, plot_type = "tree", cluster_tree_by = "cell")
#' }
CNVPlot <- function(
  srt,
  plot_type = c("heatmap", "dim", "spatial", "bar", "tree"),
  tool_name = "CNV",
  method = NULL,
  group.by = NULL,
  reduction = NULL,
  value = NULL,
  cluster_tree_by = c("cluster", "cell"),
  palette = "Chinese",
  palcolor = NULL,
  heatmap_palette = "RdBu",
  heatmap_palcolor = NULL,
  title = NULL,
  subtitle = NULL,
  theme_use = "theme_scop",
  theme_args = list(),
  ...
) {
  cnv_assert_seurat(srt)
  plot_type <- match.arg(plot_type)
  cluster_tree_by <- match.arg(cluster_tree_by)
  bundle <- cnv_get_method_bundle(srt, tool_name = tool_name, method = method)
  method <- bundle$method %||% method %||% srt@tools[[tool_name]]$active_method

  switch(plot_type,
    heatmap = cnv_plot_heatmap(
      srt = srt,
      bundle = bundle,
      method = method,
      group.by = group.by,
      palette = palette,
      palcolor = palcolor,
      heatmap_palette = heatmap_palette,
      heatmap_palcolor = heatmap_palcolor,
      title = title,
      ...
    ),
    dim = cnv_plot_dim(
      srt = srt,
      bundle = bundle,
      method = method,
      group.by = group.by,
      reduction = reduction,
      value = value,
      palette = palette,
      palcolor = palcolor,
      title = title,
      subtitle = subtitle,
      theme_use = theme_use,
      theme_args = theme_args,
      ...
    ),
    spatial = cnv_plot_spatial(
      srt = srt,
      bundle = bundle,
      method = method,
      group.by = group.by,
      value = value,
      palette = palette,
      palcolor = palcolor,
      title = title,
      subtitle = subtitle,
      theme_use = theme_use,
      theme_args = theme_args,
      ...
    ),
    bar = cnv_plot_bar(
      srt = srt,
      bundle = bundle,
      method = method,
      group.by = group.by,
      value = value,
      palette = palette,
      palcolor = palcolor,
      title = title,
      subtitle = subtitle,
      theme_use = theme_use,
      theme_args = theme_args,
      ...
    ),
    tree = cnv_plot_tree(
      bundle = bundle,
      by = cluster_tree_by,
      ...
    )
  )
}

cnv_get_method_bundle <- function(srt, tool_name, method = NULL) {
  tool <- srt@tools[[tool_name]]
  if (is.null(tool) || is.null(tool$methods)) {
    log_message(
      "Cannot find CNV results in {.code srt@tools[[{tool_name}]]}",
      message_type = "error"
    )
  }
  method <- method %||% tool$active_method
  if (is.null(method) || !method %in% names(tool$methods)) {
    log_message(
      "{.arg method} must be one of stored CNV methods: {.val {names(tool$methods)}}",
      message_type = "error"
    )
  }
  tool$methods[[method]]
}

cnv_plot_heatmap <- function(
  srt,
  bundle,
  method,
  group.by = NULL,
  max_cells = 2000,
  heatmap_palette = "RdBu",
  heatmap_palcolor = NULL,
  palette = "Chinese",
  palcolor = NULL,
  title = NULL,
  cluster_columns = TRUE,
  cluster_rows = FALSE,
  show_row_names = FALSE,
  show_column_names = FALSE,
  use_raster = TRUE,
  ...
) {
  check_r("ComplexHeatmap", verbose = FALSE)
  check_r("circlize", verbose = FALSE)
  mat <- cnv_require_matrix(bundle)
  cells <- intersect(colnames(mat), colnames(srt))
  if (length(cells) == 0L) {
    log_message(
      "CNV matrix contains no cells present in {.arg srt}",
      message_type = "error"
    )
  }
  if (!is.null(max_cells) && length(cells) > max_cells) {
    set.seed(11)
    cells <- sample(cells, max_cells)
  }
  mat <- mat[, cells, drop = FALSE]
  bin_info <- bundle$bin_info
  if (!is.null(bin_info) && nrow(bin_info) == nrow(mat)) {
    row_order <- cnv_bin_order(bin_info)
    mat <- mat[row_order, , drop = FALSE]
    bin_info <- bin_info[row_order, , drop = FALSE]
  }
  if (is.null(bin_info) || nrow(bin_info) != nrow(mat)) {
    row_split <- NULL
  } else {
    row_split <- bin_info$chr
    row_split[is.na(row_split) | !nzchar(as.character(row_split))] <- "unknown"
    row_split <- factor(as.character(row_split), levels = unique(as.character(row_split)))
  }

  group.by <- group.by %||% cnv_default_group_col(srt, method = method)
  top_annotation <- NULL
  if (!is.null(group.by)) {
    cnv_validate_metadata(srt, group.by, "group.by")
    group_values <- srt@meta.data[cells, group.by, drop = TRUE]
    if (!is.factor(group_values)) {
      group_values <- factor(as.character(group_values), levels = unique(as.character(group_values)))
    }
    top_annotation <- ComplexHeatmap::HeatmapAnnotation(
      group = group_values,
      col = list(group = palette_colors(group_values, palette = palette, palcolor = palcolor)),
      show_annotation_name = TRUE
    )
  }

  colors <- heatmap_palcolor %||% palette_colors(palette = heatmap_palette, n = 9)
  col_fun <- circlize::colorRamp2(
    seq(-1, 1, length.out = length(colors)),
    colors
  )
  ComplexHeatmap::Heatmap(
    mat,
    name = paste0(method, " CNV"),
    col = col_fun,
    column_title = title %||% paste0(method, " CNV"),
    top_annotation = top_annotation,
    row_split = row_split,
    cluster_columns = cluster_columns,
    cluster_rows = cluster_rows,
    show_row_names = show_row_names,
    show_column_names = show_column_names,
    use_raster = use_raster,
    ...
  )
}

cnv_plot_dim <- function(
  srt,
  bundle,
  method,
  group.by = NULL,
  reduction = NULL,
  value = NULL,
  palette = "Chinese",
  palcolor = NULL,
  title = NULL,
  subtitle = NULL,
  theme_use = "theme_scop",
  theme_args = list(),
  ...
) {
  value <- value %||% cnv_default_value_col(srt, method = method)
  cnv_validate_metadata(srt, value, "value")
  value_data <- srt@meta.data[[value]]
  if (is.numeric(value_data) || is.integer(value_data)) {
    FeatureDimPlot(
      srt = srt,
      features = value,
      reduction = reduction,
      palette = palette,
      palcolor = palcolor,
      title = title %||% value,
      subtitle = subtitle,
      theme_use = theme_use,
      theme_args = theme_args,
      ...
    )
  } else {
    CellDimPlot(
      srt = srt,
      group.by = value,
      reduction = reduction,
      palette = palette,
      palcolor = palcolor,
      title = title %||% value,
      subtitle = subtitle,
      theme_use = theme_use,
      theme_args = theme_args,
      ...
    )
  }
}

cnv_plot_spatial <- function(
  srt,
  bundle,
  method,
  group.by = NULL,
  value = NULL,
  palette = "Chinese",
  palcolor = NULL,
  title = NULL,
  subtitle = NULL,
  theme_use = "theme_scop",
  theme_args = list(),
  ...
) {
  value <- value %||% group.by %||% cnv_default_value_col(srt, method = method)
  p <- SpatialSpotPlot(
    srt = srt,
    group.by = value,
    palette = palette,
    palcolor = palcolor,
    theme_use = theme_use,
    theme_args = theme_args,
    ...
  )
  if (inherits(p, "ggplot")) {
    p <- p + ggplot2::labs(title = title %||% value, subtitle = subtitle)
  }
  p
}

cnv_plot_bar <- function(
  srt,
  bundle,
  method,
  group.by = NULL,
  value = NULL,
  palette = "Chinese",
  palcolor = NULL,
  position = c("fill", "stack", "dodge"),
  title = NULL,
  subtitle = NULL,
  theme_use = "theme_scop",
  theme_args = list(),
  ...
) {
  position <- match.arg(position)
  value <- value %||% cnv_prediction_col(srt, method = method) %||% cnv_cluster_col(srt, method = method)
  if (is.null(value) || !value %in% colnames(srt@meta.data)) {
    log_message(
      "No CNV prediction or cluster metadata column is available for bar plotting",
      message_type = "error"
    )
  }
  group.by <- group.by %||% "All.cells"
  df <- srt@meta.data
  if (identical(group.by, "All.cells")) {
    df[[group.by]] <- "All.cells"
  } else {
    cnv_validate_metadata(srt, group.by, "group.by")
  }
  df <- df[, c(group.by, value), drop = FALSE]
  colnames(df) <- c("group", "value")
  df$value <- as.character(df$value)
  df$value[is.na(df$value) | !nzchar(df$value)] <- "NA"
  df$group <- as.character(df$group)
  colors <- palette_colors(unique(df$value), palette = palette, palcolor = palcolor)
  ggplot2::ggplot(df, ggplot2::aes(x = .data$group, fill = .data$value)) +
    ggplot2::geom_bar(position = position, ...) +
    ggplot2::scale_fill_manual(values = colors, name = value) +
    ggplot2::labs(
      x = group.by,
      y = if (identical(position, "fill")) "Fraction" else "Cells",
      title = title %||% "CNV composition",
      subtitle = subtitle
    ) +
    cnv_plot_theme(theme_use = theme_use, theme_args = theme_args)
}

cnv_plot_tree <- function(
  bundle,
  by = c("cluster", "cell"),
  distance = c("euclidean", "correlation"),
  hclust_method = "ward.D2",
  ...
) {
  by <- match.arg(by)
  distance <- match.arg(distance)
  mat <- cnv_require_matrix(bundle)
  if (ncol(mat) < 2L) {
    log_message(
      "CNV tree requires at least two cells",
      message_type = "error"
    )
  }
  profile <- t(mat)
  if (identical(by, "cluster")) {
    cell_info <- bundle$cell_info
    cluster <- cell_info$cluster
    names(cluster) <- cell_info$cell
    cluster <- cluster[rownames(profile)]
    if (all(is.na(cluster) | !nzchar(as.character(cluster)))) {
      log_message(
        "CNV cluster information is unavailable; use {.arg cluster_tree_by = 'cell'}",
        message_type = "error"
      )
    }
    profile <- stats::aggregate(
      profile,
      by = list(cluster = as.character(cluster)),
      FUN = mean,
      na.rm = TRUE
    )
    rownames(profile) <- profile$cluster
    profile$cluster <- NULL
    profile <- as.matrix(profile)
  }
  profile[!is.finite(profile)] <- 0
  dist_obj <- if (identical(distance, "correlation")) {
    stats::as.dist(1 - stats::cor(t(profile), use = "pairwise.complete.obs"))
  } else {
    stats::dist(profile, method = "euclidean")
  }
  stats::hclust(dist_obj, method = hclust_method, ...)
}

cnv_require_matrix <- function(bundle) {
  mat <- bundle$cnv_matrix
  if (is.null(mat)) {
    log_message(
      "CNV matrix was not stored for this result. Re-run {.fn RunCNV} with {.arg store_matrix = TRUE}",
      message_type = "error"
    )
  }
  mat <- as.matrix(mat)
  if (nrow(mat) == 0L || ncol(mat) == 0L) {
    log_message(
      "Stored CNV matrix is empty",
      message_type = "error"
    )
  }
  mat
}

cnv_default_group_col <- function(srt, method) {
  for (candidate in c(
    cnv_prediction_col(srt, method = method),
    cnv_cluster_col(srt, method = method)
  )) {
    if (is.null(candidate)) {
      next
    }
    values <- srt@meta.data[[candidate]]
    if (any(!is.na(values) & nzchar(as.character(values)))) {
      return(candidate)
    }
  }
  NULL
}

cnv_default_value_col <- function(srt, method) {
  pred <- cnv_prediction_col(srt, method = method)
  if (!is.null(pred)) {
    vals <- srt@meta.data[[pred]]
    if (any(!is.na(vals) & nzchar(as.character(vals)))) {
      return(pred)
    }
  }
  score <- cnv_score_col(srt, method = method)
  if (!is.null(score)) {
    return(score)
  }
  log_message(
    "No CNV metadata columns were found for method {.val {method}}",
    message_type = "error"
  )
}

cnv_score_col <- function(srt, method) {
  candidates <- c(paste0("CNV_", method, "_score"), "CNV_score")
  hit <- candidates[candidates %in% colnames(srt@meta.data)]
  if (length(hit) == 0L) {
    return(NULL)
  }
  hit[[1L]]
}

cnv_prediction_col <- function(srt, method) {
  candidates <- c(paste0("CNV_", method, "_prediction"), "CNV_prediction")
  hit <- candidates[candidates %in% colnames(srt@meta.data)]
  if (length(hit) == 0L) {
    return(NULL)
  }
  hit[[1L]]
}

cnv_cluster_col <- function(srt, method) {
  candidates <- c(paste0("CNV_", method, "_cluster"), "CNV_cluster")
  hit <- candidates[candidates %in% colnames(srt@meta.data)]
  if (length(hit) == 0L) {
    return(NULL)
  }
  hit[[1L]]
}

cnv_bin_order <- function(bin_info) {
  chr <- as.character(bin_info$chr %||% rep(NA_character_, nrow(bin_info)))
  chr_clean <- sub("^chr", "", chr, ignore.case = TRUE)
  chr_rank <- match(chr_clean, c(as.character(seq_len(22)), "X", "Y", "M", "MT"))
  missing_chr <- is.na(chr_rank)
  if (any(missing_chr)) {
    base_rank <- if (any(!missing_chr)) max(chr_rank[!missing_chr]) else 1000L
    chr_rank[missing_chr] <- base_rank + seq_len(sum(missing_chr))
  }
  chr_rank[!is.finite(chr_rank)] <- seq_len(length(chr_rank))[!is.finite(chr_rank)]
  start <- suppressWarnings(as.numeric(bin_info$start))
  start[!is.finite(start)] <- seq_len(length(start))[!is.finite(start)]
  order(chr_rank, start, seq_along(chr_rank), na.last = TRUE)
}

cnv_plot_theme <- function(theme_use = "theme_scop", theme_args = list()) {
  if (is.null(theme_use)) {
    return(ggplot2::theme())
  }
  if (inherits(theme_use, "theme")) {
    return(theme_use)
  }
  do.call(theme_use, theme_args)
}
