#' @title Plots for GSVA (Gene Set Variation Analysis)
#'
#' @md
#' @inheritParams CellDimPlot
#' @inheritParams GroupHeatmap
#' @inheritParams EnrichmentPlot
#' @param srt A Seurat object containing the results of RunGSVA.
#' If specified, GSVA results will be extracted from the `Seurat` object automatically.
#' If not specified, the `res` argument must be provided.
#' @param group.by A character vector specifying the grouping variable used in RunGSVA.
#' @param res GSVA results generated by RunGSVA function.
#' If provided, 'srt' and 'group.by' are ignored.
#' @param assay_name The name of the assay or tools slot containing GSVA results.
#' Default is `"GSVA"`.
#' @param plot_type The type of plot to generate.
#' Options are: `"heatmap"`, `"bar"`, `"network"`, `"enrichmap"`, `"wordcloud"`, `"comparison"`.
#' Default is `"heatmap"`. Note: `"heatmap"` uses ComplexHeatmap directly, while other types reuse EnrichmentPlot logic.
#' @param db The database name used in RunGSVA. Only used for compatibility with EnrichmentPlot.
#' Default is `NULL` (will be inferred from GSVA results or set to "GSVA").
#' @param split_by The splitting variable(s) for the plot.
#' Can be `"Database"`, `"Groups"`, or both.
#' Default is `"Database"`.
#' @param color_by The variable used for coloring.
#' Default is `"Database"`.
#' @param group_use The group(s) to be used for GSVA plot.
#' Default is `NULL` (all groups).
#' @param score_cutoff The score cutoff for the GSVA plot.
#' Default is `NULL` (no cutoff).
#'
#' @seealso
#' [RunGSVA], [EnrichmentPlot]
#'
#' @export
#'
#' @examples
#' data(pancreas_sub)
#' pancreas_sub <- standard_scop(pancreas_sub)
#' pancreas_sub <- RunGSVA(
#'   pancreas_sub,
#'   db = "GO_BP",
#'   group.by = "CellType",
#'   species = "Mus_musculus",
#'   method = "gsva",
#'   kcdf = "Gaussian"
#' )
#'
#' ht1 <- GSVAPlot(
#'   pancreas_sub,
#'   plot_type = "heatmap",
#'   group.by = "CellType",
#'   topTerm = 10,
#'   width = 1,
#'   height = 2
#' )
#'
#' ht2 <- GSVAPlot(
#'   pancreas_sub,
#'   group.by = "CellType",
#'   plot_type = "heatmap",
#'   n_split = 3,
#'   topTerm = 100,
#'   use_raster = TRUE,
#'   width = 1,
#'   height = 2
#' )
#'
#' GSVAPlot(
#'   srt = pancreas_sub,
#'   group.by = "CellType",
#'   db = "GO_BP",
#'   plot_type = "comparison",
#'   topTerm = 1
#' )
#'
#' GSVAPlot(
#'   srt = pancreas_sub,
#'   group.by = "CellType",
#'   db = "GO_BP",
#'   group_use = "Ductal",
#'   plot_type = "bar",
#'   topTerm = 5
#' )
#'
#' GSVAPlot(
#'   srt = pancreas_sub,
#'   group.by = "CellType",
#'   group_use = "Ductal",
#'   db = "GO_BP",
#'   plot_type = "network"
#' )
#'
#' GSVAPlot(
#'   srt = pancreas_sub,
#'   group.by = "CellType",
#'   group_use = "Ductal",
#'   db = "GO_BP",
#'   plot_type = "enrichmap"
#' )
#'
#' GSVAPlot(
#'   pancreas_sub,
#'   group.by = "CellType",
#'   db = "GO_BP",
#'   nrow = 2,
#'   plot_type = "wordcloud",
#'   topWord = 50
#' )
#'
#' GSVAPlot(
#'   pancreas_sub,
#'   group.by = "CellType",
#'   group_use = "Ductal",
#'   db = "GO_BP",
#'   plot_type = "wordcloud",
#'   word_type = "feature"
#' )
#'
#' pancreas_sub <- RunGSVA(
#'   pancreas_sub,
#'   assay_name = "GSVA",
#'   db = "GO_BP",
#'   species = "Mus_musculus"
#' )
#'
#' FeatureDimPlot(
#'   pancreas_sub,
#'   assay = "GSVA",
#'   features = rownames(pancreas_sub[["GSVA"]])[1:2],
#'   reduction = "umap"
#' )
#'
#' FeatureStatPlot(
#'   pancreas_sub,
#'   stat.by = rownames(pancreas_sub[["GSVA"]])[1:2],
#'   group.by = "CellType",
#'   assay = "GSVA"
#' )
#'
#' ht <- GroupHeatmap(
#'   pancreas_sub,
#'   exp_legend_title = "Z-score",
#'   features = rownames(pancreas_sub[["GSVA"]])[1:10],
#'   group.by = "CellType",
#'   assay = "GSVA",
#'   width = 1,
#'   height = 2
#' )
GSVAPlot <- function(
  srt = NULL,
  res = NULL,
  group.by = NULL,
  assay_name = "GSVA",
  db = NULL,
  plot_type = c(
    "heatmap",
    "bar",
    "network",
    "enrichmap",
    "wordcloud",
    "comparison"
  ),
  split_by = c("Database", "Groups"),
  color_by = "Database",
  group_use = NULL,
  features = NULL,
  topTerm = NULL,
  score_cutoff = NULL,
  pvalueCutoff = NULL,
  padjustCutoff = NULL,
  topWord = 100,
  word_type = c("term", "feature"),
  word_size = c(2, 8),
  network_layout = "fr",
  network_labelsize = 5,
  network_blendmode = "blend",
  network_layoutadjust = TRUE,
  network_adjscale = 60,
  network_adjiter = 100,
  enrichmap_layout = "fr",
  enrichmap_cluster = "fast_greedy",
  enrichmap_label = c("term", "feature"),
  enrichmap_labelsize = 5,
  enrlichmap_nlabel = 4,
  enrichmap_show_keyword = FALSE,
  enrichmap_mark = c("ellipse", "hull"),
  enrichmap_expand = c(0.5, 0.5),
  words_excluded = NULL,
  lineheight = 0.7,
  feature_split = NULL,
  n_split = NULL,
  split_order = NULL,
  split_method = c("kmeans", "hclust", "mfuzz"),
  decreasing = FALSE,
  fuzzification = NULL,
  cluster_rows = FALSE,
  cluster_columns = FALSE,
  cluster_row_slices = FALSE,
  show_row_names = FALSE,
  show_column_names = FALSE,
  row_names_side = "right",
  column_names_side = "bottom",
  row_names_rot = 0,
  column_names_rot = 90,
  character_width = 50,
  palette = "simspec",
  palcolor = NULL,
  group_palette = "Chinese",
  group_palcolor = NULL,
  heatmap_palette = "RdBu",
  heatmap_palcolor = NULL,
  limits = NULL,
  height = NULL,
  width = NULL,
  units = "inch",
  use_raster = NULL,
  raster_device = "png",
  raster_by_magick = FALSE,
  ht_params = list(),
  aspect.ratio = 1,
  legend.position = "right",
  legend.direction = "vertical",
  theme_use = "theme_scop",
  theme_args = list(),
  combine = TRUE,
  nrow = NULL,
  ncol = NULL,
  byrow = TRUE,
  border = TRUE,
  seed = 11
) {
  set.seed(seed)
  if (isTRUE(raster_by_magick)) {
    check_r("magick", verbose = FALSE)
  }
  plot_type <- match.arg(plot_type)
  word_type <- match.arg(word_type)
  split_method <- match.arg(split_method)
  enrichmap_label <- match.arg(enrichmap_label)
  enrichmap_mark <- match.arg(enrichmap_mark)
  words_excluded <- words_excluded %||% scop::words_excluded
  if (is.null(topTerm) && !plot_type %in% c("heatmap", "wordcloud")) {
    topTerm <- if (plot_type == "enrichmap") 100 else 6
  }

  gsva_db <- NULL
  gsva_scores <- NULL
  enrichment <- NULL
  if (is.null(res)) {
    if (is.null(srt)) {
      log_message(
        "Either {.arg srt} or {.arg res} must be provided",
        message_type = "error"
      )
    }

    tool_name <- NULL
    if (!is.null(group.by)) {
      if (paste0("GSVA_", assay_name, "_", group.by) %in% names(srt@tools)) {
        tool_name <- paste0("GSVA_", assay_name, "_", group.by)
      } else {
        possible_names <- grep(
          pattern = paste0("^GSVA_", group.by, "_"),
          x = names(srt@tools),
          value = TRUE
        )
        if (length(possible_names) > 0) {
          tool_name <- possible_names[1]
          if (length(possible_names) > 1) {
            log_message(
              "Multiple GSVA results found for {.val {group.by}}. Using {.val {tool_name}}",
              message_type = "warning"
            )
          }
        }
      }
    } else {
      possible_names <- c(
        paste0("GSVA_", assay_name),
        paste0("GSVA_", assay_name, "_", group.by)
      )
      for (name in possible_names) {
        if (name %in% names(srt@tools)) {
          tool_name <- name
          break
        }
      }
    }

    if (is.null(tool_name) || !tool_name %in% names(srt@tools)) {
      if (assay_name %in% SeuratObject::Assays(srt)) {
        gsva_scores <- GetAssayData5(srt, assay = assay_name, layer = "data")
      } else {
        log_message(
          "GSVA results not found. Please run RunGSVA first",
          message_type = "error"
        )
      }
    } else {
      gsva_result <- srt@tools[[tool_name]]
      gsva_scores <- gsva_result[["scores"]]
      enrichment <- gsva_result[["enrichment"]]
      group.by <- gsva_result[["group.by"]] %||% group.by
      gsva_db <- gsva_result[["db"]] %||% db
    }
  } else {
    if (is.list(res) && "scores" %in% names(res)) {
      gsva_scores <- res[["scores"]]
      enrichment <- res[["enrichment"]]
      group.by <- res[["group.by"]] %||% group.by
      gsva_db <- res[["db"]] %||% db
    } else if (is.matrix(res) || inherits(res, "Matrix")) {
      gsva_scores <- res
      gsva_db <- db
    } else {
      log_message(
        "Invalid {.arg res} format",
        message_type = "error"
      )
    }
  }

  if (!is.matrix(gsva_scores)) {
    gsva_scores <- as.matrix(gsva_scores)
  }

  if (is.null(gsva_db)) {
    gsva_db <- db %||% "GSVA"
  }

  if (!is.null(group_use)) {
    group_use <- intersect(group_use, colnames(gsva_scores))
    if (length(group_use) == 0) {
      log_message(
        "No matching groups found in GSVA results",
        message_type = "error"
      )
    }
    gsva_scores <- gsva_scores[, group_use, drop = FALSE]
  }

  if (plot_type == "heatmap") {
    heatmap_topTerm <- topTerm
    if (
      is.null(features) &&
        (is.null(heatmap_topTerm) || is.infinite(heatmap_topTerm)) &&
        nrow(gsva_scores) > 100
    ) {
      heatmap_topTerm <- 50
      log_message(
        "Too many gene sets for a readable heatmap. Using the top 50 most variable gene sets by default.",
        message_type = "warning"
      )
    }
    if (!is.null(features)) {
      if (is.list(features)) {
        features <- unique(unlist(features))
      }
      features <- intersect(features, rownames(gsva_scores))
      if (length(features) == 0) {
        log_message(
          "No matching gene sets found in GSVA results",
          message_type = "error"
        )
      }
      gsva_scores <- gsva_scores[features, , drop = FALSE]
    } else if (!is.null(heatmap_topTerm) && is.finite(heatmap_topTerm) && heatmap_topTerm < nrow(gsva_scores)) {
      geneset_var <- apply(gsva_scores, 1, stats::var, na.rm = TRUE)
      top_genesets <- names(sort(geneset_var, decreasing = TRUE))[seq_len(min(heatmap_topTerm, length(geneset_var)))]
      gsva_scores <- gsva_scores[top_genesets, , drop = FALSE]
    }
  }

  if (!is.null(score_cutoff)) {
    keep <- apply(abs(gsva_scores), 1, max, na.rm = TRUE) >= abs(score_cutoff)
    gsva_scores <- gsva_scores[keep, , drop = FALSE]
    if (nrow(gsva_scores) == 0) {
      log_message(
        "No gene sets pass the score cutoff",
        message_type = "error"
      )
    }
  }

  if (plot_type != "heatmap") {
    if (is.null(enrichment)) {
      enrichment <- do.call(rbind, lapply(colnames(gsva_scores), function(group) {
        data.frame(
          ID = rownames(gsva_scores),
          Description = rownames(gsva_scores),
          Groups = group,
          Database = if (length(gsva_db) == 1) gsva_db else gsva_db[1],
          GSVA_Score = as.numeric(gsva_scores[, group]),
          stringsAsFactors = FALSE
        )
      }))
    }

    if (!"GSVA_Score" %in% colnames(enrichment)) {
      enrichment[["GSVA_Score"]] <- enrichment[["Count"]] %||% 0
    }
    enrichment[["GSVA_Score"]] <- as.numeric(enrichment[["GSVA_Score"]])

    if (!is.null(score_cutoff)) {
      enrichment <- enrichment[
        abs(enrichment[["GSVA_Score"]]) >= abs(score_cutoff), ,
        drop = FALSE
      ]
      if (nrow(enrichment) == 0) {
        log_message(
          "No gene sets pass the score cutoff",
          message_type = "error"
        )
      }
    }

    abs_scores <- abs(enrichment[["GSVA_Score"]])
    max_score <- max(abs_scores, na.rm = TRUE)
    if (!is.finite(max_score) || max_score <= 0) {
      pvalue_scores <- rep(1, length(abs_scores))
    } else {
      normalized_scores <- abs_scores / max_score
      pvalue_scores <- exp(-normalized_scores * 3) * 0.9 + 0.1
      pvalue_scores <- pmin(pmax(as.numeric(pvalue_scores), 1e-3), 1)
    }

    enrichment[["pvalue"]] <- as.numeric(enrichment[["pvalue"]] %||% pvalue_scores)
    enrichment[["p.adjust"]] <- as.numeric(enrichment[["p.adjust"]] %||% pvalue_scores)
    enrichment[["pvalue"]][!is.finite(enrichment[["pvalue"]])] <- 1
    enrichment[["p.adjust"]][!is.finite(enrichment[["p.adjust"]])] <- 1
    enrichment[["geneID"]] <- enrichment[["geneID"]] %||% ""
    has_geneid <- any(nzchar(trimws(as.character(enrichment[["geneID"]]))))

    if (isTRUE(has_geneid)) {
      gene_counts <- vapply(
        as.character(enrichment[["geneID"]]),
        function(x) {
          x <- trimws(x)
          if (!nzchar(x)) return(0L)
          length(unique(strsplit(x, "/", fixed = TRUE)[[1]]))
        },
        FUN.VALUE = integer(1)
      )
      denom <- max(gene_counts, na.rm = TRUE)
      if (!is.finite(denom) || denom <= 0) denom <- 1L
      enrichment[["Count"]] <- as.numeric(enrichment[["Count"]] %||% gene_counts)
      enrichment[["GeneRatio"]] <- enrichment[["GeneRatio"]] %||% paste0(gene_counts, "/", denom)
      enrichment[["BgRatio"]] <- enrichment[["BgRatio"]] %||% "1/1"
    } else {
      denom <- max(abs_scores, na.rm = TRUE)
      if (!is.finite(denom) || denom <= 0) denom <- 1
      enrichment[["Count"]] <- as.numeric(enrichment[["Count"]] %||% abs_scores)
      enrichment[["GeneRatio"]] <- enrichment[["GeneRatio"]] %||% paste0(round(abs_scores, 3), "/", round(denom, 3))
      enrichment[["BgRatio"]] <- enrichment[["BgRatio"]] %||% "1/1"
    }

    match_geneset_ids <- function(query) {
      query <- as.character(query)
      query <- query[!is.na(query) & nzchar(trimws(query))]
      if (length(query) == 0) {
        return(character(0))
      }
      id_text <- tolower(trimws(as.character(enrichment[["ID"]])))
      desc_text <- tolower(trimws(as.character(enrichment[["Description"]])))

      matched_ids <- character(0)
      for (q in tolower(trimws(query))) {
        exact_hit <- enrichment[["ID"]][id_text == q | desc_text == q]
        if (length(exact_hit) == 0) {
          partial_hit <- enrichment[["ID"]][
            grepl(q, id_text, fixed = TRUE) |
              grepl(q, desc_text, fixed = TRUE)
          ]
          matched_ids <- c(matched_ids, partial_hit)
        } else {
          matched_ids <- c(matched_ids, exact_hit)
        }
      }
      unique(matched_ids)
    }

    if (!is.null(features)) {
      if (is.list(features)) {
        id_use <- lapply(features, match_geneset_ids)
        id_use <- id_use[lengths(id_use) > 0]
      } else {
        id_use <- match_geneset_ids(features)
      }
      if (length(id_use) == 0) {
        log_message(
          "No matching gene sets found in GSVA results",
          message_type = "error"
        )
      }
    } else {
      id_use <- NULL
    }

    topTerm <- if (is.null(topTerm) || is.infinite(topTerm)) {
      Inf
    } else {
      topTerm
    }

    if (plot_type %in% c("network", "enrichmap") && !has_geneid) {
      log_message(
        paste0(
          plot_type,
          " plotting requires gene sets with {.field geneID}. ",
          "Please rerun {.fn RunGSVA} with the updated version to store gene members."
        ),
        message_type = "error"
      )
    }

    if (plot_type == "wordcloud" && word_type == "feature" && !has_geneid) {
      log_message(
        "word_type 'feature' requires gene lists (geneID), which GSVA results do not contain. Using word_type='term' instead",
        message_type = "warning"
      )
      word_type <- "term"
    }

    return(
      EnrichmentPlot(
      srt = NULL,
      res = list(enrichment = enrichment),
      db = gsva_db,
      plot_type = plot_type,
      split_by = split_by,
      color_by = color_by,
      group_use = group_use,
      id_use = id_use,
      pvalueCutoff = pvalueCutoff %||% Inf,
      padjustCutoff = padjustCutoff %||% Inf,
      topTerm = topTerm,
      topWord = topWord,
      word_type = word_type,
      word_size = word_size,
      words_excluded = words_excluded,
      character_width = character_width,
      lineheight = lineheight,
      palette = heatmap_palette,
      palcolor = heatmap_palcolor,
      network_layout = network_layout,
      network_labelsize = network_labelsize,
      network_blendmode = network_blendmode,
      network_layoutadjust = network_layoutadjust,
      network_adjscale = network_adjscale,
      network_adjiter = network_adjiter,
      enrichmap_layout = enrichmap_layout,
      enrichmap_cluster = enrichmap_cluster,
      enrichmap_label = enrichmap_label,
      enrichmap_labelsize = enrichmap_labelsize,
      enrlichmap_nlabel = enrlichmap_nlabel,
      enrichmap_show_keyword = enrichmap_show_keyword,
      enrichmap_mark = enrichmap_mark,
      enrichmap_expand = enrichmap_expand,
      aspect.ratio = aspect.ratio,
      legend.position = legend.position,
      legend.direction = legend.direction,
      theme_use = theme_use,
      theme_args = theme_args,
      combine = combine,
      nrow = nrow,
      ncol = ncol,
      byrow = byrow,
      seed = seed
    ))
  }

  if (plot_type == "heatmap") {
    matrix_group_name <- group.by %||% "Group"
    return(EnrichmentHeatmap(
      scores = gsva_scores,
      group.by = matrix_group_name,
      feature_split = feature_split,
      n_split = n_split,
      split_order = split_order,
      split_method = split_method,
      decreasing = decreasing,
      fuzzification = fuzzification,
      cluster_rows = cluster_rows,
      cluster_columns = cluster_columns,
      cluster_row_slices = cluster_row_slices,
      show_row_names = show_row_names,
      show_column_names = show_column_names,
      row_names_side = row_names_side,
      column_names_side = column_names_side,
      row_names_rot = row_names_rot,
      column_names_rot = column_names_rot,
      character_width = character_width,
      palette = heatmap_palette,
      palcolor = heatmap_palcolor,
      group_palette = group_palette,
      group_palcolor = group_palcolor,
      use_raster = use_raster,
      raster_device = raster_device,
      raster_by_magick = raster_by_magick,
      height = height,
      width = width,
      units = units,
      border = border,
      ht_params = ht_params,
      seed = seed
    ))
  }

  log_message(
    "Unexpected plot_type: {.val {plot_type}}",
    message_type = "error"
  )
}
