#' @title Plots for GSVA (Gene Set Variation Analysis)
#'
#' @md
#' @inheritParams CellDimPlot
#' @inheritParams GroupHeatmap
#' @inheritParams EnrichmentPlot
#' @param srt A Seurat object containing the results of RunGSVA.
#' If specified, GSVA results will be extracted from the `Seurat` object automatically.
#' If not specified, the `res` argument must be provided.
#' @param group.by A character vector specifying the grouping variable used in RunGSVA.
#' @param res GSVA results generated by RunGSVA function.
#' If provided, 'srt' and 'group.by' are ignored.
#' @param assay_name The name of the assay or tools slot containing GSVA results.
#' Default is `"GSVA"`.
#' @param sample.by Metadata column identifying biological samples for
#' sample-level aggregation. Required when `mode = "diff"`.
#' @param mode Plot mode. `"score"` keeps the original GSVA score plotting
#' behavior; `"diff"` performs a two-group differential pathway activity test
#' on sample-aggregated GSVA scores.
#' @param plot_type The type of plot to generate.
#' Options are: `"heatmap"`, `"bar"`, `"network"`, `"enrichmap"`, `"wordcloud"`,
#' `"comparison"`, and `"volcano"`. When omitted, the default is `"heatmap"`
#' for `mode = "score"` and `"volcano"` for `mode = "diff"`.
#' @param db The database name used in RunGSVA. Only used for compatibility with EnrichmentPlot.
#' Default is `NULL` (will be inferred from GSVA results or set to "GSVA").
#' @param split_by The splitting variable(s) for the plot.
#' Can be `"Database"`, `"Groups"`, or both.
#' Default is `"Database"`.
#' @param color_by The variable used for coloring.
#' Default is `"Database"`.
#' @param group_use The group(s) to be used for GSVA plot.
#' Default is `NULL` (all groups).
#' @param score_cutoff The score cutoff for the GSVA plot.
#' Default is `NULL` (no cutoff).
#' @param sort.by Ranking metric used when `return_data = TRUE` in
#' `mode = "score"`. `"abs"` uses absolute GSVA score and `"score"` uses signed
#' GSVA score.
#' @param aggregate.fun Function used to aggregate cells within each
#' `sample.by` and `group.by` combination in `mode = "diff"`. Supports `"mean"`
#' and `"median"`.
#' @param test.use Statistical test for `mode = "diff"`. Supports `"wilcox"`
#' and `"t.test"`.
#' @param p.adjust.method Multiple-testing correction method passed to
#' [stats::p.adjust()] in `mode = "diff"`.
#' @param return_data Whether to return the ranking/statistics table instead of
#' a plot.
#' @details
#' GSVA itself returns pathway activity/enrichment scores, not statistical
#' p-values. In `mode = "score"`, plots use signed `GSVA_Score` values directly
#' and `score_cutoff` is the only score threshold. Use `mode = "diff"` for real
#' sample-level statistical tests and adjusted p-values on GSVA scores.
#'
#' @seealso
#' [RunGSVA], [EnrichmentPlot]
#'
#' @export
#'
#' @examples
#' data(pancreas_sub)
#' pancreas_sub <- pancreas_sub[, 1:80]
#' pancreas_sub <- Seurat::NormalizeData(pancreas_sub, verbose = FALSE)
#' features_all <- rownames(pancreas_sub)
#' pancreas_sub <- RunGSVA(
#'   pancreas_sub,
#'   features = list(
#'     A = features_all[1:5],
#'     B = features_all[6:10]
#'   ),
#'   method = "zscore",
#'   minGSSize = 2,
#'   min.sz = 2
#' )
#'
#' ht <- GSVAPlot(
#'   pancreas_sub,
#'   plot_type = "heatmap",
#'   group.by = "CellType",
#'   topTerm = 2,
#'   width = 1,
#'   height = 2
#' )
#' ht$plot
#'
#' GSVAPlot(
#'   srt = pancreas_sub,
#'   group.by = "CellType",
#'   plot_type = "comparison",
#'   topTerm = 1
#' )
#'
#' GSVAPlot(
#'   srt = pancreas_sub,
#'   group.by = "CellType",
#'   plot_type = "bar",
#'   topTerm = 2
#' )
GSVAPlot <- function(
  srt = NULL,
  res = NULL,
  group.by = NULL,
  sample.by = NULL,
  assay_name = "GSVA",
  db = NULL,
  mode = c("score", "diff"),
  plot_type = c(
    "heatmap",
    "bar",
    "network",
    "enrichmap",
    "wordcloud",
    "comparison",
    "volcano"
  ),
  split_by = c("Database", "Groups"),
  color_by = "Database",
  group_use = NULL,
  features = NULL,
  topTerm = NULL,
  score_cutoff = NULL,
  sort.by = c("abs", "score"),
  aggregate.fun = c("mean", "median"),
  test.use = c("wilcox", "t.test"),
  p.adjust.method = "BH",
  pvalueCutoff = NULL,
  padjustCutoff = NULL,
  topWord = 100,
  word_type = c("term", "feature"),
  word_size = c(2, 8),
  network_layout = "fr",
  network_labelsize = 5,
  network_blendmode = "blend",
  network_layoutadjust = TRUE,
  network_adjscale = 60,
  network_adjiter = 100,
  enrichmap_layout = "fr",
  enrichmap_cluster = "fast_greedy",
  enrichmap_label = c("term", "feature"),
  enrichmap_labelsize = 5,
  enrlichmap_nlabel = 4,
  enrichmap_show_keyword = FALSE,
  enrichmap_mark = c("ellipse", "hull"),
  enrichmap_expand = c(0.5, 0.5),
  words_excluded = NULL,
  lineheight = 0.7,
  feature_split = NULL,
  n_split = NULL,
  split_order = NULL,
  split_method = c("kmeans", "hclust", "mfuzz"),
  decreasing = FALSE,
  fuzzification = NULL,
  cluster_rows = FALSE,
  cluster_columns = FALSE,
  cluster_row_slices = FALSE,
  show_row_names = FALSE,
  show_column_names = FALSE,
  row_names_side = "right",
  column_names_side = "bottom",
  row_names_rot = 0,
  column_names_rot = 90,
  character_width = 50,
  palette = "simspec",
  palcolor = NULL,
  group_palette = "Chinese",
  group_palcolor = NULL,
  heatmap_palette = "RdBu",
  heatmap_palcolor = NULL,
  limits = NULL,
  height = NULL,
  width = NULL,
  units = "inch",
  use_raster = NULL,
  raster_device = "png",
  raster_by_magick = FALSE,
  ht_params = list(),
  aspect.ratio = 1,
  legend.position = "right",
  legend.direction = "vertical",
  theme_use = "theme_scop",
  theme_args = list(),
  combine = TRUE,
  return_data = FALSE,
  nrow = NULL,
  ncol = NULL,
  byrow = TRUE,
  border = TRUE,
  nlabel = 0,
  seed = 11,
  verbose = TRUE
) {
  set.seed(seed)
  if (isTRUE(raster_by_magick)) {
    check_r("magick", verbose = FALSE)
  }
  mode <- match.arg(mode)
  sort.by <- match.arg(sort.by)
  aggregate.fun <- match.arg(aggregate.fun)
  test.use <- match.arg(test.use)
  plot_type_missing <- missing(plot_type) || is.null(plot_type)
  plot_type_choices <- c(
    "heatmap",
    "bar",
    "network",
    "enrichmap",
    "wordcloud",
    "comparison",
    "volcano"
  )
  if (isTRUE(plot_type_missing)) {
    plot_type <- if (identical(mode, "diff")) "volcano" else "heatmap"
  }
  plot_type <- match.arg(plot_type, plot_type_choices)
  word_type <- match.arg(word_type)
  split_method <- match.arg(split_method)
  enrichmap_label <- match.arg(enrichmap_label)
  enrichmap_mark <- match.arg(enrichmap_mark)
  if (identical(mode, "score") && identical(plot_type, "volcano")) {
    log_message(
      "{.arg plot_type = 'volcano'} is only available when {.arg mode = 'diff'}",
      message_type = "error"
    )
  }
  if (identical(mode, "diff") && !plot_type %in% c("volcano", "bar")) {
    log_message(
      "{.arg mode = 'diff'} supports {.arg plot_type} values {.val volcano} and {.val bar}",
      message_type = "error"
    )
  }
  if (
    identical(mode, "score") &&
      (!is.null(pvalueCutoff) || !is.null(padjustCutoff))
  ) {
    log_message(
      paste0(
        "{.arg pvalueCutoff} and {.arg padjustCutoff} are only available when ",
        "{.arg mode = 'diff'}. Use {.arg score_cutoff} for score plots."
      ),
      message_type = "error"
    )
  }
  if (plot_type == "wordcloud") {
    check_r("ggwordcloud", verbose = FALSE)
    check_r("simplifyEnrichment", verbose = FALSE)
  }
  words_excluded <- words_excluded %||% scop::words_excluded
  if (is.null(topTerm) && !plot_type %in% c("heatmap", "wordcloud")) {
    topTerm <- if (plot_type == "enrichmap") 100 else 6
  }

  gsva_db <- NULL
  gsva_scores <- NULL
  enrichment <- NULL
  gsva_is_group_level <- FALSE
  if (is.null(res)) {
    if (is.null(srt)) {
      log_message(
        "Either {.arg srt} or {.arg res} must be provided",
        message_type = "error"
      )
    }

    tool_name <- NULL
    if (!is.null(group.by)) {
      if (paste0("GSVA_", assay_name, "_", group.by) %in% names(srt@tools)) {
        tool_name <- paste0("GSVA_", assay_name, "_", group.by)
      } else {
        possible_names <- grep(
          pattern = paste0("^GSVA_", group.by, "_"),
          x = names(srt@tools),
          value = TRUE
        )
        if (length(possible_names) > 0) {
          tool_name <- possible_names[1]
          if (length(possible_names) > 1) {
            log_message(
              "Multiple GSVA results found for {.val {group.by}}. Using {.val {tool_name}}",
              message_type = "warning",
              verbose = verbose
            )
          }
        }
      }
    } else {
      possible_names <- c(
        paste0("GSVA_", assay_name),
        paste0("GSVA_", assay_name, "_", group.by)
      )
      for (name in possible_names) {
        if (name %in% names(srt@tools)) {
          tool_name <- name
          break
        }
      }
    }

    if (is.null(tool_name) || !tool_name %in% names(srt@tools)) {
      if (assay_name %in% SeuratObject::Assays(srt)) {
        gsva_scores <- GetAssayData5(srt, assay = assay_name, layer = "data")
      } else {
        log_message(
          "GSVA results not found. Please run RunGSVA first",
          message_type = "error"
        )
      }
    } else {
      gsva_result <- srt@tools[[tool_name]]
      gsva_scores <- gsva_result[["scores"]]
      enrichment <- gsva_result[["enrichment"]]
      group.by <- gsva_result[["group.by"]] %||% group.by
      gsva_db <- gsva_result[["db"]] %||% db
      gsva_is_group_level <- !is.null(gsva_result[["group.by"]])
    }
  } else {
    if (is.list(res) && "scores" %in% names(res)) {
      gsva_scores <- res[["scores"]]
      enrichment <- res[["enrichment"]]
      group.by <- res[["group.by"]] %||% group.by
      gsva_db <- res[["db"]] %||% db
      gsva_is_group_level <- !is.null(res[["group.by"]])
    } else if (is.matrix(res) || inherits(res, "Matrix")) {
      gsva_scores <- res
      gsva_db <- db
    } else {
      log_message(
        "Invalid {.arg res} format",
        message_type = "error"
      )
    }
  }

  if (!is.matrix(gsva_scores)) {
    gsva_scores <- as.matrix(gsva_scores)
  }

  if (is.null(gsva_db)) {
    gsva_db <- db %||% "GSVA"
  }

  if (identical(mode, "diff")) {
    scores_for_diff <- gsva_scores
    if (!is.null(features)) {
      keep <- gsva_plot_match_features(features, scores_for_diff, enrichment)
      if (length(keep) == 0L) {
        log_message(
          "No matching gene sets found in GSVA results",
          message_type = "error"
        )
      }
      scores_for_diff <- scores_for_diff[keep, , drop = FALSE]
    }
    diff_df <- gsva_plot_diff_table(
      scores = scores_for_diff,
      enrichment = enrichment,
      srt = srt,
      group.by = group.by,
      sample.by = sample.by,
      group_use = group_use,
      aggregate.fun = aggregate.fun,
      test.use = test.use,
      p.adjust.method = p.adjust.method,
      is_group_level = gsva_is_group_level
    )
    if (!is.null(padjustCutoff)) {
      diff_df <- diff_df[
        is.finite(diff_df[["p.adjust"]]) & diff_df[["p.adjust"]] <= padjustCutoff, ,
        drop = FALSE
      ]
      if (nrow(diff_df) == 0L) {
        log_message(
          "No GSVA differential results pass {.arg padjustCutoff}",
          message_type = "error"
        )
      }
    }
    if (isTRUE(return_data)) {
      return(diff_df)
    }
    if (identical(plot_type, "bar")) {
      return(gsva_plot_diff_bar(
        diff_df,
        topTerm = topTerm,
        palette = palette,
        palcolor = palcolor,
        theme_use = theme_use,
        theme_args = theme_args
      ))
    }
    return(gsva_plot_diff_volcano(
      diff_df,
      padjustCutoff = padjustCutoff,
      palette = palette,
      palcolor = palcolor,
      theme_use = theme_use,
      theme_args = theme_args
    ))
  }

  if (!is.null(group_use)) {
    group_use <- intersect(group_use, colnames(gsva_scores))
    if (length(group_use) == 0) {
      log_message(
        "No matching groups found in GSVA results",
        message_type = "error"
      )
    }
    gsva_scores <- gsva_scores[, group_use, drop = FALSE]
  }

  if (plot_type == "heatmap") {
    heatmap_topTerm <- topTerm
    if (
      is.null(features) &&
        (is.null(heatmap_topTerm) || is.infinite(heatmap_topTerm)) &&
        nrow(gsva_scores) > 100
    ) {
      heatmap_topTerm <- 50
      log_message(
        "Too many gene sets for a readable heatmap. Using the top 50 most variable gene sets by default.",
        message_type = "warning",
        verbose = verbose
      )
    }
    if (!is.null(features)) {
      if (is.list(features)) {
        features <- unique(unlist(features))
      }
      features <- intersect(features, rownames(gsva_scores))
      if (length(features) == 0) {
        log_message(
          "No matching gene sets found in GSVA results",
          message_type = "error"
        )
      }
      gsva_scores <- gsva_scores[features, , drop = FALSE]
    } else if (!is.null(heatmap_topTerm) && is.finite(heatmap_topTerm) && heatmap_topTerm < nrow(gsva_scores)) {
      geneset_var <- gsva_plot_row_variances(gsva_scores)
      top_genesets <- names(sort(geneset_var, decreasing = TRUE))[seq_len(min(heatmap_topTerm, length(geneset_var)))]
      gsva_scores <- gsva_scores[top_genesets, , drop = FALSE]
    }
  }

  if (!is.null(score_cutoff)) {
    keep <- gsva_plot_score_cutoff_keep(gsva_scores, score_cutoff)
    gsva_scores <- gsva_scores[keep, , drop = FALSE]
    if (nrow(gsva_scores) == 0) {
      log_message(
        "No gene sets pass the score cutoff",
        message_type = "error"
      )
    }
  }

  if (isTRUE(return_data)) {
    return(gsva_plot_score_table(
      scores = gsva_scores,
      enrichment = enrichment,
      srt = srt,
      group.by = group.by,
      group_use = group_use,
      sort.by = sort.by,
      topTerm = topTerm,
      score_cutoff = NULL
    ))
  }

  if (plot_type %in% c("bar", "comparison")) {
    score_df <- gsva_plot_score_table(
      scores = gsva_scores,
      enrichment = enrichment,
      srt = srt,
      group.by = group.by,
      group_use = group_use,
      sort.by = sort.by,
      topTerm = Inf,
      score_cutoff = score_cutoff
    )
    if (!is.null(features)) {
      features_flat <- unique(as.character(unlist(features)))
      score_df <- score_df[
        score_df[["ID"]] %in% features_flat |
          score_df[["Description"]] %in% features_flat, ,
        drop = FALSE
      ]
      if (nrow(score_df) == 0L) {
        log_message(
          "No matching gene sets found in GSVA results",
          message_type = "error"
        )
      }
    }
    theme_fun <- if (is.function(theme_use)) {
      theme_use
    } else {
      get(theme_use, mode = "function", inherits = TRUE)
    }
    return(thisplot::StatPlot(
      meta.data = score_df,
      stat.by = "Description",
      value.by = "GSVA_Score",
      group.by = "Groups",
      split.by = "Database",
      stat_type = "value",
      plot_type = if (identical(plot_type, "bar")) "bar" else "dot",
      top_n = topTerm,
      complete_groups = identical(plot_type, "comparison"),
      rank.by = if (identical(sort.by, "abs")) "absolute" else "value",
      palette = heatmap_palette,
      palcolor = heatmap_palcolor,
      value_limits = limits,
      value_legend_title = "GSVA score",
      xlab = if (identical(plot_type, "comparison")) "Group" else NULL,
      ylab = if (identical(plot_type, "bar")) "GSVA score" else NULL,
      character_width = character_width,
      flip = identical(plot_type, "bar"),
      theme_use = theme_fun,
      theme_args = theme_args,
      legend.position = legend.position,
      legend.direction = legend.direction
    ))
  }

  if (plot_type != "heatmap") {
    if (is.null(enrichment)) {
      n_terms <- nrow(gsva_scores)
      n_groups <- ncol(gsva_scores)
      term_names <- rownames(gsva_scores)
      db_value <- if (length(gsva_db) == 1) gsva_db else gsva_db[1]
      enrichment <- data.frame(
        ID = rep(term_names, times = n_groups),
        Description = rep(term_names, times = n_groups),
        Groups = rep(colnames(gsva_scores), each = n_terms),
        Database = db_value,
        GSVA_Score = as.numeric(gsva_scores),
        stringsAsFactors = FALSE
      )
    }

    if (!"GSVA_Score" %in% colnames(enrichment)) {
      enrichment[["GSVA_Score"]] <- enrichment[["Count"]] %||% 0
    }
    enrichment[["GSVA_Score"]] <- as.numeric(enrichment[["GSVA_Score"]])

    if (!is.null(score_cutoff)) {
      enrichment <- enrichment[
        abs(enrichment[["GSVA_Score"]]) >= abs(score_cutoff), ,
        drop = FALSE
      ]
      if (nrow(enrichment) == 0) {
        log_message(
          "No gene sets pass the score cutoff",
          message_type = "error"
        )
      }
    }

    abs_scores <- abs(enrichment[["GSVA_Score"]])
    enrichment[["geneID"]] <- enrichment[["geneID"]] %||% ""
    has_geneid <- any(nzchar(trimws(as.character(enrichment[["geneID"]]))))

    if (isTRUE(has_geneid)) {
      gene_counts <- vapply(
        as.character(enrichment[["geneID"]]),
        function(x) {
          x <- trimws(x)
          if (!nzchar(x)) {
            return(0L)
          }
          length(unique(strsplit(x, "/", fixed = TRUE)[[1]]))
        },
        FUN.VALUE = integer(1)
      )
      enrichment[["Count"]] <- as.numeric(enrichment[["Count"]] %||% gene_counts)
    } else {
      enrichment[["Count"]] <- as.numeric(enrichment[["Count"]] %||% abs_scores)
    }

    match_geneset_ids <- function(query) {
      query <- as.character(query)
      query <- query[!is.na(query) & nzchar(trimws(query))]
      if (length(query) == 0) {
        return(character(0))
      }
      id_text <- tolower(trimws(as.character(enrichment[["ID"]])))
      desc_text <- tolower(trimws(as.character(enrichment[["Description"]])))

      matched_ids <- character(0)
      for (q in tolower(trimws(query))) {
        exact_hit <- enrichment[["ID"]][id_text == q | desc_text == q]
        if (length(exact_hit) == 0) {
          partial_hit <- enrichment[["ID"]][
            grepl(q, id_text, fixed = TRUE) |
              grepl(q, desc_text, fixed = TRUE)
          ]
          matched_ids <- c(matched_ids, partial_hit)
        } else {
          matched_ids <- c(matched_ids, exact_hit)
        }
      }
      unique(matched_ids)
    }

    if (!is.null(features)) {
      if (is.list(features)) {
        id_use <- lapply(features, match_geneset_ids)
        id_use <- id_use[lengths(id_use) > 0]
      } else {
        id_use <- match_geneset_ids(features)
      }
      if (length(id_use) == 0) {
        log_message(
          "No matching gene sets found in GSVA results",
          message_type = "error"
        )
      }
    } else {
      id_use <- NULL
    }

    topTerm <- if (is.null(topTerm) || is.infinite(topTerm)) {
      Inf
    } else {
      topTerm
    }

    if (plot_type %in% c("network", "enrichmap") && !has_geneid) {
      log_message(
        paste0(
          plot_type,
          " plotting requires gene sets with {.field geneID}. ",
          "Please rerun {.fn RunGSVA} with the updated version to store gene members."
        ),
        message_type = "error"
      )
    }

    if (plot_type == "wordcloud" && word_type == "feature" && !has_geneid) {
      log_message(
        "word_type 'feature' requires gene lists (geneID), which GSVA results do not contain. Using word_type='term' instead",
        message_type = "warning",
        verbose = verbose
      )
      word_type <- "term"
    }

    return(
      EnrichmentPlot(
        srt = NULL,
        res = list(enrichment = enrichment),
        db = gsva_db,
        plot_type = plot_type,
        split_by = split_by,
        color_by = color_by,
        group_use = group_use,
        id_use = id_use,
        pvalueCutoff = NULL,
        padjustCutoff = NULL,
        score_col = "GSVA_Score",
        scoreCutoff = score_cutoff,
        score_label = "GSVA score",
        topTerm = topTerm,
        topWord = topWord,
        word_type = word_type,
        word_size = word_size,
        words_excluded = words_excluded,
        character_width = character_width,
        lineheight = lineheight,
        palette = heatmap_palette,
        palcolor = heatmap_palcolor,
        network_layout = network_layout,
        network_labelsize = network_labelsize,
        network_blendmode = network_blendmode,
        network_layoutadjust = network_layoutadjust,
        network_adjscale = network_adjscale,
        network_adjiter = network_adjiter,
        enrichmap_layout = enrichmap_layout,
        enrichmap_cluster = enrichmap_cluster,
        enrichmap_label = enrichmap_label,
        enrichmap_labelsize = enrichmap_labelsize,
        enrlichmap_nlabel = enrlichmap_nlabel,
        enrichmap_show_keyword = enrichmap_show_keyword,
        enrichmap_mark = enrichmap_mark,
        enrichmap_expand = enrichmap_expand,
        aspect.ratio = aspect.ratio,
        legend.position = legend.position,
        legend.direction = legend.direction,
        theme_use = theme_use,
        theme_args = theme_args,
        combine = combine,
        nrow = nrow,
        ncol = ncol,
        byrow = byrow,
        seed = seed
      )
    )
  }

  if (plot_type == "heatmap") {
    matrix_group_name <- group.by %||% "Group"
    return(EnrichmentHeatmap(
      scores = gsva_scores,
      group.by = matrix_group_name,
      feature_split = feature_split,
      n_split = n_split,
      split_order = split_order,
      split_method = split_method,
      decreasing = decreasing,
      fuzzification = fuzzification,
      cluster_rows = cluster_rows,
      cluster_columns = cluster_columns,
      cluster_row_slices = cluster_row_slices,
      show_row_names = show_row_names,
      show_column_names = show_column_names,
      row_names_side = row_names_side,
      column_names_side = column_names_side,
      row_names_rot = row_names_rot,
      column_names_rot = column_names_rot,
      character_width = character_width,
      palette = heatmap_palette,
      palcolor = heatmap_palcolor,
      group_palette = group_palette,
      group_palcolor = group_palcolor,
      use_raster = use_raster,
      raster_device = raster_device,
      raster_by_magick = raster_by_magick,
      height = height,
      width = width,
      units = units,
      border = border,
      legend.position = legend.position,
      nlabel = nlabel,
      ht_params = ht_params,
      seed = seed
    ))
  }

  log_message(
    "Unexpected plot_type: {.val {plot_type}}",
    message_type = "error"
  )
}
