# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

augur_subsample_cpp <- function(mat, cols) {
    .Call(`_scop_augur_subsample_cpp`, mat, cols)
}

bayesprism_gibbs_initial_cpp <- function(mixture, phi, gibbs_idx, alpha = 1.0, seed = 123L, cores = 1L) {
    .Call(`_scop_bayesprism_gibbs_initial_cpp`, mixture, phi, gibbs_idx, alpha, seed, cores)
}

bayesprism_gibbs_final_cpp <- function(mixture, phi, gibbs_idx, alpha = 1.0, seed = 123L, cores = 1L) {
    .Call(`_scop_bayesprism_gibbs_final_cpp`, mixture, phi, gibbs_idx, alpha, seed, cores)
}

ccc_aggregate_long_cpp <- function(sender, receiver, score, significant) {
    .Call(`_scop_ccc_aggregate_long_cpp`, sender, receiver, score, significant)
}

ccc_aggregate_liana_table_cpp <- function(source, target, ligand_complex, receptor_complex, sample, score, pvalue, classification, method, liana_method, resource, has_sample) {
    .Call(`_scop_ccc_aggregate_liana_table_cpp`, source, target, ligand_complex, receptor_complex, sample, score, pvalue, classification, method, liana_method, resource, has_sample)
}

cibersort_cpp <- function(signature, mixture, perm = 0L, QN = TRUE, absolute = FALSE, cores = 1L, seed = 123L, verbose = FALSE) {
    .Call(`_scop_cibersort_cpp`, signature, mixture, perm, QN, absolute, cores, seed, verbose)
}

cellrank_validate_transition_matrix_cpp <- function(T_, eps = 1e-10, min_self_loop = 0.01) {
    .Call(`_scop_cellrank_validate_transition_matrix_cpp`, T_, eps, min_self_loop)
}

cellrank_stationary_distribution_cpp <- function(T_, max_iter = 1000L, tol = 1e-10) {
    .Call(`_scop_cellrank_stationary_distribution_cpp`, T_, max_iter, tol)
}

cellrank_schur_cpp <- function(T_, n_components = 10L) {
    .Call(`_scop_cellrank_schur_cpp`, T_, n_components)
}

cellrank_auto_n_states_cpp <- function(eigenvalues, min_states = 2L, max_states = 20L) {
    .Call(`_scop_cellrank_auto_n_states_cpp`, eigenvalues, min_states, max_states)
}

cellrank_velocity_kernel_cpp <- function(velocity_embedding, embedding, knn_idx, backward = FALSE, softmax_scale = 4.0, n_neighbors_velo = -1L) {
    .Call(`_scop_cellrank_velocity_kernel_cpp`, velocity_embedding, embedding, knn_idx, backward, softmax_scale, n_neighbors_velo)
}

cellrank_velocity_kernel_gene_cpp <- function(gene_velocity, expression, knn_idx, backward = FALSE, softmax_scale = 4.0, n_neighbors_velo = -1L) {
    .Call(`_scop_cellrank_velocity_kernel_gene_cpp`, gene_velocity, expression, knn_idx, backward, softmax_scale, n_neighbors_velo)
}

cellrank_pseudotime_kernel_cpp <- function(pseudotime, knn_idx, cell_weights, bandwidth = 1.0, backward = FALSE) {
    .Call(`_scop_cellrank_pseudotime_kernel_cpp`, pseudotime, knn_idx, cell_weights, bandwidth, backward)
}

cellrank_cytotrace_kernel_cpp <- function(gene_counts, knn_idx, bandwidth = 1.0, backward = FALSE) {
    .Call(`_scop_cellrank_cytotrace_kernel_cpp`, gene_counts, knn_idx, bandwidth, backward)
}

cellrank_cflare_cpp <- function(T_, n_states = 5L, max_iter = 1000L, tol = 1e-6) {
    .Call(`_scop_cellrank_cflare_cpp`, T_, n_states, max_iter, tol)
}

cellrank_gpcca_cpp <- function(T_, n_states = 5L, n_cells_terminal = 10L, skip_perron = FALSE) {
    .Call(`_scop_cellrank_gpcca_cpp`, T_, n_states, n_cells_terminal, skip_perron)
}

cellrank_lineage_drivers_cpp <- function(expression, abs_probs, lineage_idx = integer()) {
    .Call(`_scop_cellrank_lineage_drivers_cpp`, expression, abs_probs, lineage_idx)
}

classification_metrics <- function(predicted, truth, classes, rare_threshold = 0.05) {
    .Call(`_scop_classification_metrics`, predicted, truth, classes, rare_threshold)
}

cytospace_assign <- function(sc_expr, st_expr, spot_capacities, seed = 1L, upstream_tie_break = TRUE, verbose = FALSE) {
    .Call(`_scop_cytospace_assign`, sc_expr, st_expr, spot_capacities, seed, upstream_tie_break, verbose)
}

cytotrace2_preprocess_numeric <- function(expression_mapped) {
    .Call(`_scop_cytotrace2_preprocess_numeric`, expression_mapped)
}

cytotrace2_preprocess_sparse_numeric <- function(expression_mapped) {
    .Call(`_scop_cytotrace2_preprocess_sparse_numeric`, expression_mapped)
}

cytotrace2_main <- function(rank_data, log2_data, parameter_dict, smooth_groups, cores, seed, pca_coords) {
    .Call(`_scop_cytotrace2_main`, rank_data, log2_data, parameter_dict, smooth_groups, cores, seed, pca_coords)
}

scvelo_dynamical_nm_cpp <- function(Ms, Mu, use_genes, max_iter = 10L, init_alpha = -1.0, init_beta = -1.0, init_gamma = -1.0) {
    .Call(`_scop_scvelo_dynamical_nm_cpp`, Ms, Mu, use_genes, max_iter, init_alpha, init_beta, init_gamma)
}

scvelo_dynamical_velocity_cpp <- function(Ms, Mu, alpha, beta, gamma, t_, knn_idx, embedding) {
    .Call(`_scop_scvelo_dynamical_velocity_cpp`, Ms, Mu, alpha, beta, gamma, t_, knn_idx, embedding)
}

scvelo_dynamical_em_cpp <- function(Ms, Mu, use_genes, max_iter_em = 10L, conv_tol = 1e-6, em_oversampling = 2L, init_alpha = -1.0, init_beta = -1.0, init_gamma = -1.0) {
    .Call(`_scop_scvelo_dynamical_em_cpp`, Ms, Mu, use_genes, max_iter_em, conv_tol, em_oversampling, init_alpha, init_beta, init_gamma)
}

gniplr_cpp <- function(expression, target_idx, correlation_threshold = 0.3, lasso_degree = 30L, lasso_alpha = 0.1, max_lag = 3L) {
    .Call(`_scop_gniplr_cpp`, expression, target_idx, correlation_threshold, lasso_degree, lasso_alpha, max_lag)
}

aucell_auc_sparse <- function(expr, gene_sets, auc_max_rank, norm_auc = TRUE, strategy = 1L, algorithm = 1L, seed = 0L) {
    .Call(`_scop_aucell_auc_sparse`, expr, gene_sets, auc_max_rank, norm_auc, strategy, algorithm, seed)
}

aucell_auc_ranked <- function(rankings, gene_sets, auc_max_rank) {
    .Call(`_scop_aucell_auc_ranked`, rankings, gene_sets, auc_max_rank)
}

ora_hypergeom <- function(genes, term_ids, term_genes, term_name_ids, term_names, min_size = 10L, max_size = 2147483647L) {
    .Call(`_scop_ora_hypergeom`, genes, term_ids, term_genes, term_name_ids, term_names, min_size, max_size)
}

module_score_sparse <- function(expr, feature_sets, control_sets) {
    .Call(`_scop_module_score_sparse`, expr, feature_sets, control_sets)
}

proportion_permutation <- function(sample_ids, cluster_ids, cluster_levels, n_permutations, pseudocount = 1e-8, verbose = FALSE) {
    .Call(`_scop_proportion_permutation`, sample_ids, cluster_ids, cluster_levels, n_permutations, pseudocount, verbose)
}

ssgsea_rank_dense <- function(expr, gene_sets, alpha = 0.25, normalize = TRUE) {
    .Call(`_scop_ssgsea_rank_dense`, expr, gene_sets, alpha, normalize)
}

zscore_dense <- function(expr, gene_sets, min_size = 1L, max_size = 2147483647L) {
    .Call(`_scop_zscore_dense`, expr, gene_sets, min_size, max_size)
}

plage_dense <- function(expr, gene_sets, min_size = 1L, max_size = 2147483647L) {
    .Call(`_scop_plage_dense`, expr, gene_sets, min_size, max_size)
}

gsva_gaussian_dense <- function(expr, gene_sets, max_diff = TRUE, abs_ranking = FALSE, tau = 1.0, chunk_size = 0L) {
    .Call(`_scop_gsva_gaussian_dense`, expr, gene_sets, max_diff, abs_ranking, tau, chunk_size)
}

gsva_poisson_dense <- function(expr, gene_sets, max_diff = TRUE, abs_ranking = FALSE, tau = 1.0, chunk_size = 0L) {
    .Call(`_scop_gsva_poisson_dense`, expr, gene_sets, max_diff, abs_ranking, tau, chunk_size)
}

mdic3_score_cpp <- function(expression, grn, group) {
    .Call(`_scop_mdic3_score_cpp`, expression, grn, group)
}

wilcox_rank_sum_sparse <- function(mat, n_group1, min_expression = 0.0) {
    .Call(`_scop_wilcox_rank_sum_sparse`, mat, n_group1, min_expression)
}

wilcox_rank_sum_sparse_all_cells <- function(mat, n_group1) {
    .Call(`_scop_wilcox_rank_sum_sparse_all_cells`, mat, n_group1)
}

sparse_topk_by_column <- function(mat, k, decreasing = TRUE) {
    .Call(`_scop_sparse_topk_by_column`, mat, k, decreasing)
}

dense_topk_by_column <- function(mat, k, decreasing = FALSE) {
    .Call(`_scop_dense_topk_by_column`, mat, k, decreasing)
}

milo_neighborhood_medians_cpp <- function(coords, knn_idx) {
    .Call(`_scop_milo_neighborhood_medians_cpp`, coords, knn_idx)
}

milo_nhood_counts_cpp <- function(knn_idx, sampled_vertices, sample_id, n_samples, k_dist) {
    .Call(`_scop_milo_nhood_counts_cpp`, knn_idx, sampled_vertices, sample_id, n_samples, k_dist)
}

milo_weighted_fdr_cpp <- function(pvalues, weights) {
    .Call(`_scop_milo_weighted_fdr_cpp`, pvalues, weights)
}

monocle2_order_from_mst_cpp <- function(distances, edges, root_cell = 1L) {
    .Call(`_scop_monocle2_order_from_mst_cpp`, distances, edges, root_cell)
}

monocle2_order_from_weighted_edges_cpp <- function(n_cells, edges, weights, root_cell = 1L) {
    .Call(`_scop_monocle2_order_from_weighted_edges_cpp`, n_cells, edges, weights, root_cell)
}

monocle2_project_cells_to_mst_cpp <- function(z, y, graph_edges, closest_vertex) {
    .Call(`_scop_monocle2_project_cells_to_mst_cpp`, z, y, graph_edges, closest_vertex)
}

monocle2_select_root_by_state_cpp <- function(coords, candidate_cells, pseudotime, closest_vertex, use_min_pseudotime = FALSE) {
    .Call(`_scop_monocle2_select_root_by_state_cpp`, coords, candidate_cells, pseudotime, closest_vertex, use_min_pseudotime)
}

paga_connectivities_cpp <- function(knn_idx, groups, n_groups) {
    .Call(`_scop_paga_connectivities_cpp`, knn_idx, groups, n_groups)
}

paga_diffusion_pseudotime_cpp <- function(connectivities, root_group, n_dcs = 10L, n_branchings = 0L, group_sizes = numeric(), min_group_size = 0.01) {
    .Call(`_scop_paga_diffusion_pseudotime_cpp`, connectivities, root_group, n_dcs, n_branchings, group_sizes, min_group_size)
}

paga_velocity_transitions_cpp <- function(velocity_embedding, knn_idx, groups, n_groups, softmax_scale = 4.0) {
    .Call(`_scop_paga_velocity_transitions_cpp`, velocity_embedding, knn_idx, groups, n_groups, softmax_scale)
}

paga_root_cell_cpp <- function(embedding, groups, root_group) {
    .Call(`_scop_paga_root_cell_cpp`, embedding, groups, root_group)
}

phate_graphtools_affinity_data_cpp <- function(data, knn, decay, thresh = 1e-4, knn_max = -1L) {
    .Call(`_scop_phate_graphtools_affinity_data_cpp`, data, knn, decay, thresh, knn_max)
}

phate_affinity_cpp <- function(knn_dist, knn_idx, alpha_decay = 1.0, bandwidth_k = -1L) {
    .Call(`_scop_phate_affinity_cpp`, knn_dist, knn_idx, alpha_decay, bandwidth_k)
}

phate_diffusion_operator_cpp <- function(rows, cols, vals, n_cells, t_max = 10L) {
    .Call(`_scop_phate_diffusion_operator_cpp`, rows, cols, vals, n_cells, t_max)
}

phate_potential_distance_cpp <- function(log_transition, n_landmarks = -1L) {
    .Call(`_scop_phate_potential_distance_cpp`, log_transition, n_landmarks)
}

phate_metric_mds_cpp <- function(D, n_components = 2L) {
    .Call(`_scop_phate_metric_mds_cpp`, D, n_components)
}

phate_find_optimal_t_cpp <- function(rows, cols, vals, n_cells, t_max = 20L) {
    .Call(`_scop_phate_find_optimal_t_cpp`, rows, cols, vals, n_cells, t_max)
}

palantir_compute_kernel_cpp <- function(data, knn_idx, knn_dist, knn, alpha = 0.0) {
    .Call(`_scop_palantir_compute_kernel_cpp`, data, knn_idx, knn_dist, knn, alpha)
}

palantir_normalize_kernel_cpp <- function(kernel_i, kernel_j, kernel_x, n) {
    .Call(`_scop_palantir_normalize_kernel_cpp`, kernel_i, kernel_j, kernel_x, n)
}

palantir_multiscale_space_cpp <- function(eigenvectors, eigenvalues) {
    .Call(`_scop_palantir_multiscale_space_cpp`, eigenvectors, eigenvalues)
}

palantir_numpy_random_sample_cpp <- function(n, seed = 0L) {
    .Call(`_scop_palantir_numpy_random_sample_cpp`, n, seed)
}

palantir_maxmin_waypoints_cpp <- function(ms_data, num_waypoints, seed = 20L) {
    .Call(`_scop_palantir_maxmin_waypoints_cpp`, ms_data, num_waypoints, seed)
}

palantir_pseudotime_cpp <- function(ms_data, start_cell, waypoints, knn, max_iterations = 25L, n_jobs = 1L) {
    .Call(`_scop_palantir_pseudotime_cpp`, ms_data, start_cell, waypoints, knn, max_iterations, n_jobs)
}

palantir_markov_chain_cpp <- function(wp_data, knn, pseudotime) {
    .Call(`_scop_palantir_markov_chain_cpp`, wp_data, knn, pseudotime)
}

palantir_terminal_states_cpp <- function(T_i, T_j, T_x, n, wp_data) {
    .Call(`_scop_palantir_terminal_states_cpp`, T_i, T_j, T_x, n, wp_data)
}

palantir_absorption_cpp <- function(T_i, T_j, T_x, n, terminal_state_indices) {
    .Call(`_scop_palantir_absorption_cpp`, T_i, T_j, T_x, n, terminal_state_indices)
}

scvelo_filter_genes_scanpy_cpp <- function(spliced, unspliced, min_counts = 3L, min_counts_u = 3L) {
    .Call(`_scop_scvelo_filter_genes_scanpy_cpp`, spliced, unspliced, min_counts, min_counts_u)
}

scvelo_normalize_scanpy_cpp <- function(spliced, unspliced, initial_spliced_totals, initial_unspliced_totals) {
    .Call(`_scop_scvelo_normalize_scanpy_cpp`, spliced, unspliced, initial_spliced_totals, initial_unspliced_totals)
}

scvelo_pca_scanpy_cpp <- function(X, n_pcs = 30L) {
    .Call(`_scop_scvelo_pca_scanpy_cpp`, X, n_pcs)
}

scvelo_knn_scanpy_cpp <- function(coords, n_neighbors = 10L, exclude_self = TRUE) {
    .Call(`_scop_scvelo_knn_scanpy_cpp`, coords, n_neighbors, exclude_self)
}

scvelo_filter_genes_shared_cpp <- function(spliced, unspliced, min_shared_counts = 30L) {
    .Call(`_scop_scvelo_filter_genes_shared_cpp`, spliced, unspliced, min_shared_counts)
}

scvelo_preprocess_scanpy_cpp <- function(spliced, unspliced, n_pcs = 30L, n_neighbors = 10L, min_counts = 3L, min_counts_u = 3L) {
    .Call(`_scop_scvelo_preprocess_scanpy_cpp`, spliced, unspliced, n_pcs, n_neighbors, min_counts, min_counts_u)
}

proportion_bootstrap_log2fd <- function(v1, v2, n_bootstrap = 1000L, pseudocount = 1e-5, verbose = FALSE) {
    .Call(`_scop_proportion_bootstrap_log2fd`, v1, v2, n_bootstrap, pseudocount, verbose)
}

proportion_bootstrap_stats <- function(v1, v2, n_bootstrap = 1000L, pseudocount = 1e-5, verbose = FALSE) {
    .Call(`_scop_proportion_bootstrap_stats`, v1, v2, n_bootstrap, pseudocount, verbose)
}

pseudotime_velocity_knn <- function(x_emb, pseudotime, neighbors, normalize = TRUE) {
    .Call(`_scop_pseudotime_velocity_knn`, x_emb, pseudotime, neighbors, normalize)
}

pseudotime_velocity_gradient <- function(x_emb, pseudotime, neighbors, smooth = 0.5, normalize = TRUE) {
    .Call(`_scop_pseudotime_velocity_gradient`, x_emb, pseudotime, neighbors, smooth, normalize)
}

rctd_sparse_quality_cpp <- function(st_counts, ref_counts) {
    .Call(`_scop_rctd_sparse_quality_cpp`, st_counts, ref_counts)
}

rctd_normalize_weights_cpp <- function(weights) {
    .Call(`_scop_rctd_normalize_weights_cpp`, weights)
}

rctd_metadata_cpp <- function(weights, all_spots) {
    .Call(`_scop_rctd_metadata_cpp`, weights, all_spots)
}

rctd_finalize_weights_cpp <- function(weights, all_spots) {
    .Call(`_scop_rctd_finalize_weights_cpp`, weights, all_spots)
}

grnboost_tree <- function(expr, regulator_idx, target_idx, n_rounds = 5000L, learning_rate = 0.01, max_edges_per_target = 0L, max_depth = 3L, max_features = 0.1, subsample = 0.9, early_stop_window_length = 25L, random_seed = 1234L, exclude_self = TRUE) {
    .Call(`_scop_grnboost_tree`, expr, regulator_idx, target_idx, n_rounds, learning_rate, max_edges_per_target, max_depth, max_features, subsample, early_stop_window_length, random_seed, exclude_self)
}

grnboost_tree_parallel <- function(expr, regulator_idx, target_idx, n_rounds = 5000L, learning_rate = 0.01, max_edges_per_target = 0L, max_depth = 3L, max_features = 0.1, subsample = 0.9, early_stop_window_length = 25L, random_seed = 1234L, exclude_self = TRUE, cores = 1L) {
    .Call(`_scop_grnboost_tree_parallel`, expr, regulator_idx, target_idx, n_rounds, learning_rate, max_edges_per_target, max_depth, max_features, subsample, early_stop_window_length, random_seed, exclude_self, cores)
}

grnboost_tree_sparse <- function(expr, regulator_idx, target_idx, n_rounds = 5000L, learning_rate = 0.01, max_edges_per_target = 0L, max_depth = 3L, max_features = 0.1, subsample = 0.9, early_stop_window_length = 25L, random_seed = 1234L, exclude_self = TRUE) {
    .Call(`_scop_grnboost_tree_sparse`, expr, regulator_idx, target_idx, n_rounds, learning_rate, max_edges_per_target, max_depth, max_features, subsample, early_stop_window_length, random_seed, exclude_self)
}

grnboost_tree_sparse_parallel <- function(expr, regulator_idx, target_idx, n_rounds = 5000L, learning_rate = 0.01, max_edges_per_target = 0L, max_depth = 3L, max_features = 0.1, subsample = 0.9, early_stop_window_length = 25L, random_seed = 1234L, exclude_self = TRUE, cores = 1L) {
    .Call(`_scop_grnboost_tree_sparse_parallel`, expr, regulator_idx, target_idx, n_rounds, learning_rate, max_edges_per_target, max_depth, max_features, subsample, early_stop_window_length, random_seed, exclude_self, cores)
}

grnboost_tree_profile <- function(expr, regulator_idx, target_idx, n_rounds = 5000L, learning_rate = 0.01, max_edges_per_target = 0L, max_depth = 3L, max_features = 0.1, subsample = 0.9, early_stop_window_length = 25L, random_seed = 1234L, exclude_self = TRUE) {
    .Call(`_scop_grnboost_tree_profile`, expr, regulator_idx, target_idx, n_rounds, learning_rate, max_edges_per_target, max_depth, max_features, subsample, early_stop_window_length, random_seed, exclude_self)
}

grnboost_tree_round_trace <- function(expr, regulator_idx, target_idx, trace_regulator_idx, n_rounds = 5000L, learning_rate = 0.01, max_depth = 3L, max_features = 0.1, subsample = 0.9, early_stop_window_length = 25L, random_seed = 1234L, exclude_self = TRUE) {
    .Call(`_scop_grnboost_tree_round_trace`, expr, regulator_idx, target_idx, trace_regulator_idx, n_rounds, learning_rate, max_depth, max_features, subsample, early_stop_window_length, random_seed, exclude_self)
}

grnboost_tree_round_nodes <- function(expr, regulator_idx, target_idx, trace_round, n_rounds = 5000L, learning_rate = 0.01, max_depth = 3L, max_features = 0.1, subsample = 0.9, early_stop_window_length = 25L, random_seed = 1234L, exclude_self = TRUE) {
    .Call(`_scop_grnboost_tree_round_nodes`, expr, regulator_idx, target_idx, trace_round, n_rounds, learning_rate, max_depth, max_features, subsample, early_stop_window_length, random_seed, exclude_self)
}

grnboost_tree_node_candidates <- function(expr, regulator_idx, target_idx, trace_round, trace_node, n_rounds = 5000L, learning_rate = 0.01, max_depth = 3L, max_features = 0.1, subsample = 0.9, early_stop_window_length = 25L, random_seed = 1234L, exclude_self = TRUE) {
    .Call(`_scop_grnboost_tree_node_candidates`, expr, regulator_idx, target_idx, trace_round, trace_node, n_rounds, learning_rate, max_depth, max_features, subsample, early_stop_window_length, random_seed, exclude_self)
}

scenic_ctx_recovery <- function(ranks, weights, rank_threshold) {
    .Call(`_scop_scenic_ctx_recovery`, ranks, weights, rank_threshold)
}

scenic_ctx_auc_avg2sd <- function(ranks, total_genes, rank_threshold, rank_cutoff) {
    .Call(`_scop_scenic_ctx_auc_avg2sd`, ranks, total_genes, rank_threshold, rank_cutoff)
}

scenic_ctx_auc_nes <- function(ranks, nes_threshold, rank_cutoff) {
    .Call(`_scop_scenic_ctx_auc_nes`, ranks, nes_threshold, rank_cutoff)
}

scenicplus_region_gene_cor <- function(atac_log, rna_log, region_idx, gene_idx) {
    .Call(`_scop_scenicplus_region_gene_cor`, atac_log, rna_log, region_idx, gene_idx)
}

scenicplus_triplets_cpp <- function(tf_gene_tf, tf_gene_target, tf_gene_importance, region_gene_region, region_gene_gene, region_gene_score, tf_region_tf, tf_region_region, tf_region_score) {
    .Call(`_scop_scenicplus_triplets_cpp`, tf_gene_tf, tf_gene_target, tf_gene_importance, region_gene_region, region_gene_gene, region_gene_score, tf_region_tf, tf_region_region, tf_region_score)
}

scvelo_filter_genes_cpp <- function(spliced, unspliced, min_counts = 3L, min_counts_u = 3L) {
    .Call(`_scop_scvelo_filter_genes_cpp`, spliced, unspliced, min_counts, min_counts_u)
}

scvelo_normalize_log_cpp <- function(spliced, unspliced) {
    .Call(`_scop_scvelo_normalize_log_cpp`, spliced, unspliced)
}

scvelo_moments_cpp <- function(spliced, unspliced, knn_idx) {
    .Call(`_scop_scvelo_moments_cpp`, spliced, unspliced, knn_idx)
}

scvelo_moments_connectivities_cpp <- function(spliced, unspliced, knn_idx) {
    .Call(`_scop_scvelo_moments_connectivities_cpp`, spliced, unspliced, knn_idx)
}

scvelo_second_order_moments_cpp <- function(spliced, unspliced, knn_idx) {
    .Call(`_scop_scvelo_second_order_moments_cpp`, spliced, unspliced, knn_idx)
}

scvelo_deterministic_cpp <- function(Ms, Mu, knn_idx, embedding, fit_offset = FALSE, perc = 0.0) {
    .Call(`_scop_scvelo_deterministic_cpp`, Ms, Mu, knn_idx, embedding, fit_offset, perc)
}

scvelo_stochastic_cpp <- function(Ms, Mu, Mss, Mus, knn_idx, embedding) {
    .Call(`_scop_scvelo_stochastic_cpp`, Ms, Mu, Mss, Mus, knn_idx, embedding)
}

scvelo_velocity_graph_cpp <- function(Ms, Mu, residual, knn_idx, n_neighbors_velo = -1L, softmax_scale = 4.0, sqrt_transform = FALSE, n_recurse_neighbors = 1L) {
    .Call(`_scop_scvelo_velocity_graph_cpp`, Ms, Mu, residual, knn_idx, n_neighbors_velo, softmax_scale, sqrt_transform, n_recurse_neighbors)
}

scvelo_project_velocity_embedding_cpp <- function(graph_rows, graph_cols, graph_vals, graph_neg_rows, graph_neg_cols, graph_neg_vals, embedding, scale = 10.0, self_transitions = TRUE, use_negative_cosines = TRUE) {
    .Call(`_scop_scvelo_project_velocity_embedding_cpp`, graph_rows, graph_cols, graph_vals, graph_neg_rows, graph_neg_cols, graph_neg_vals, embedding, scale, self_transitions, use_negative_cosines)
}

scvelo_velocity_confidence_cpp <- function(Ms, residual, knn_idx) {
    .Call(`_scop_scvelo_velocity_confidence_cpp`, Ms, residual, knn_idx)
}

scvelo_velocity_transition_cpp <- function(Ms, residual, knn_idx, n_neighbors_velo = -1L, softmax_scale = 10.0) {
    .Call(`_scop_scvelo_velocity_transition_cpp`, Ms, residual, knn_idx, n_neighbors_velo, softmax_scale)
}

scvelo_terminal_states_transition_cpp <- function(transition_matrix, knn_idx) {
    .Call(`_scop_scvelo_terminal_states_transition_cpp`, transition_matrix, knn_idx)
}

scvelo_terminal_states_cpp <- function(velocity_embedding, embedding, knn_idx, n_neighbors_velo = 10L, seed = 0L) {
    .Call(`_scop_scvelo_terminal_states_cpp`, velocity_embedding, embedding, knn_idx, n_neighbors_velo, seed)
}

scvelo_terminal_states_graph_cpp <- function(graph_rows, graph_cols, graph_vals, graph_neg_rows, graph_neg_cols, graph_neg_vals, knn_idx, eps = 1e-3) {
    .Call(`_scop_scvelo_terminal_states_graph_cpp`, graph_rows, graph_cols, graph_vals, graph_neg_rows, graph_neg_cols, graph_neg_vals, knn_idx, eps)
}

scvelo_pseudotime_transition_cpp <- function(transition_matrix, root_cells, end_points) {
    .Call(`_scop_scvelo_pseudotime_transition_cpp`, transition_matrix, root_cells, end_points)
}

scvelo_pseudotime_cpp <- function(velocity_embedding, embedding, knn_idx, root_cells, end_points, n_neighbors_velo = 10L) {
    .Call(`_scop_scvelo_pseudotime_cpp`, velocity_embedding, embedding, knn_idx, root_cells, end_points, n_neighbors_velo)
}

scvelo_pseudotime_graph_cpp <- function(graph_rows, graph_cols, graph_vals, graph_neg_rows, graph_neg_cols, graph_neg_vals, knn_idx, root_cells, end_points, n_dcs = 10L) {
    .Call(`_scop_scvelo_pseudotime_graph_cpp`, graph_rows, graph_cols, graph_vals, graph_neg_rows, graph_neg_cols, graph_neg_vals, knn_idx, root_cells, end_points, n_dcs)
}

scvelo_velocity_genes_cpp <- function(Ms, velocity) {
    .Call(`_scop_scvelo_velocity_genes_cpp`, Ms, velocity)
}

scvelo_stochastic_embedding_cpp <- function(spliced, unspliced, knn_idx, embedding) {
    .Call(`_scop_scvelo_stochastic_embedding_cpp`, spliced, unspliced, knn_idx, embedding)
}

sctenifold_pcnet_covariance_raw <- function(x, n_comp = 3L, ncv = 0L, maxit = 1000L, tol = 1e-10, cores = 1L) {
    .Call(`_scop_sctenifold_pcnet_covariance_raw`, x, n_comp, ncv, maxit, tol, cores)
}

sctenifold_pcnet_covariance_sparse <- function(x, n_comp = 3L, scale_scores = TRUE, symmetric = FALSE, q = 0.0, ncv = 0L, maxit = 1000L, tol = 1e-10, cores = 1L) {
    .Call(`_scop_sctenifold_pcnet_covariance_sparse`, x, n_comp, scale_scores, symmetric, q, ncv, maxit, tol, cores)
}

sctenifold_tensor_decomposition <- function(x_list, init_u, max_iter = 1000L, tol = 1e-5, verbose = FALSE) {
    .Call(`_scop_sctenifold_tensor_decomposition`, x_list, init_u, max_iter, tol, verbose)
}

sctenifold_strict_direction <- function(x, lambda = 1.0) {
    .Call(`_scop_sctenifold_strict_direction`, x, lambda)
}

sctenifold_manifold_matrix <- function(x, y) {
    .Call(`_scop_sctenifold_manifold_matrix`, x, y)
}

sctenifold_pair_distances <- function(aligned) {
    .Call(`_scop_sctenifold_pair_distances`, aligned)
}

scibet_fit_predict <- function(ref, query, labels, n_labels, n_top, additional_per_label = 0L, return_probabilities = TRUE) {
    .Call(`_scop_scibet_fit_predict`, ref, query, labels, n_labels, n_top, additional_per_label, return_probabilities)
}

scibet_fit_predict_sparse <- function(ref, query, labels, n_labels, n_top, additional_per_label = 0L, return_probabilities = TRUE) {
    .Call(`_scop_scibet_fit_predict_sparse`, ref, query, labels, n_labels, n_top, additional_per_label, return_probabilities)
}

scibet_predict <- function(query, core, feature_index) {
    .Call(`_scop_scibet_predict`, query, core, feature_index)
}

scaleC <- function(X) {
    .Call(`_scop_scaleC`, X)
}

OmegaC <- function(Omega, sgn) {
    .Call(`_scop_OmegaC`, Omega, sgn)
}

OmegaSC <- function(OmegaS, sgn) {
    .Call(`_scop_OmegaSC`, OmegaS, sgn)
}

maxLambdaLmC <- function(X, y, alpha, wbeta, N0, p) {
    .Call(`_scop_maxLambdaLmC`, X, y, alpha, wbeta, N0, p)
}

cvTrimLmC <- function(beta, nn, nn2, loco, XF, yF, NF, a0) {
    .Call(`_scop_cvTrimLmC`, beta, nn, nn2, loco, XF, yF, NF, a0)
}

EnetLmC <- function(X, y, alpha, lambda, nlambda, ilambda, wbeta, p, N0, thresh, maxit, thresh2) {
    .Call(`_scop_EnetLmC`, X, y, alpha, lambda, nlambda, ilambda, wbeta, p, N0, thresh, maxit, thresh2)
}

cvEnetLmC <- function(X, y, alpha, lambda, nlambda, wbeta, N, p, thresh, maxit, XF, yF, NF, thresh2) {
    .Call(`_scop_cvEnetLmC`, X, y, alpha, lambda, nlambda, wbeta, N, p, thresh, maxit, XF, yF, NF, thresh2)
}

NetLmC <- function(X, y, alpha, lambda, nlambda, ilambda, wbeta, Omega, loc, nadj, p, N0, thresh, maxit, thresh2) {
    .Call(`_scop_NetLmC`, X, y, alpha, lambda, nlambda, ilambda, wbeta, Omega, loc, nadj, p, N0, thresh, maxit, thresh2)
}

cvNetLmC <- function(X, y, alpha, lambda, nlambda, wbeta, Omega, loc, nadj, N, p, thresh, maxit, XF, yF, NF, thresh2) {
    .Call(`_scop_cvNetLmC`, X, y, alpha, lambda, nlambda, wbeta, Omega, loc, nadj, N, p, thresh, maxit, XF, yF, NF, thresh2)
}

maxLambdaCoxC <- function(X, tevent, N, nevent, nevent1, loc1, n, alpha, wbeta, N0, p) {
    .Call(`_scop_maxLambdaCoxC`, X, tevent, N, nevent, nevent1, loc1, n, alpha, wbeta, N0, p)
}

pletaCm <- function(xb, exb, nevent, nevent1, loc1, n, ifast, itwo) {
    .Call(`_scop_pletaCm`, xb, exb, nevent, nevent1, loc1, n, ifast, itwo)
}

cvTrimCoxC <- function(beta, nn, nn2, loco, XF, NF, neventF, nevent1F, loc1F, nF, X, N, nevent, nevent1, loc1, n, ifast, itwo) {
    .Call(`_scop_cvTrimCoxC`, beta, nn, nn2, loco, XF, NF, neventF, nevent1F, loc1F, nF, X, N, nevent, nevent1, loc1, n, ifast, itwo)
}

EnetCoxC <- function(X, tevent, alpha, lambda, nlambda, ilambda, wbeta, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast) {
    .Call(`_scop_EnetCoxC`, X, tevent, alpha, lambda, nlambda, ilambda, wbeta, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast)
}

cvEnetCoxC <- function(X, tevent, alpha, lambda, nlambda, wbeta, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast, XF, NF, neventF, nevent1F, loc1F, nF) {
    .Call(`_scop_cvEnetCoxC`, X, tevent, alpha, lambda, nlambda, wbeta, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast, XF, NF, neventF, nevent1F, loc1F, nF)
}

NetCoxC <- function(X, tevent, alpha, lambda, nlambda, ilambda, wbeta, Omega, loc, nadj, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast) {
    .Call(`_scop_NetCoxC`, X, tevent, alpha, lambda, nlambda, ilambda, wbeta, Omega, loc, nadj, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast)
}

cvNetCoxC <- function(X, tevent, alpha, lambda, nlambda, wbeta, Omega, loc, nadj, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast, XF, NF, neventF, nevent1F, loc1F, nF) {
    .Call(`_scop_cvNetCoxC`, X, tevent, alpha, lambda, nlambda, wbeta, Omega, loc, nadj, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast, XF, NF, neventF, nevent1F, loc1F, nF)
}

maxLambdaLogC <- function(X, Z, alpha, wbeta, N0, p) {
    .Call(`_scop_maxLambdaLogC`, X, Z, alpha, wbeta, N0, p)
}

cvTrimLogC <- function(beta, nn, nn2, loco, XF, yF, NF, threshP) {
    .Call(`_scop_cvTrimLogC`, beta, nn, nn2, loco, XF, yF, NF, threshP)
}

EnetLogC <- function(X, y, alpha, lambda, nlambda, ilambda, wbeta, wbetai, p, N0, thresh, maxit, threshP) {
    .Call(`_scop_EnetLogC`, X, y, alpha, lambda, nlambda, ilambda, wbeta, wbetai, p, N0, thresh, maxit, threshP)
}

cvEnetLogC <- function(X, y, alpha, lambda, nlambda, wbeta, wbetai, p, N0, thresh, maxit, XF, yF, NF, threshP) {
    .Call(`_scop_cvEnetLogC`, X, y, alpha, lambda, nlambda, wbeta, wbetai, p, N0, thresh, maxit, XF, yF, NF, threshP)
}

NetLogC <- function(X, y, alpha, lambda, nlambda, ilambda, wbeta, wbetai, Omega, loc, nadj, p, N0, thresh, maxit, threshP) {
    .Call(`_scop_NetLogC`, X, y, alpha, lambda, nlambda, ilambda, wbeta, wbetai, Omega, loc, nadj, p, N0, thresh, maxit, threshP)
}

cvNetLogC <- function(X, y, alpha, lambda, nlambda, wbeta, wbetai, Omega, loc, nadj, p, N0, thresh, maxit, XF, yF, NF, threshP) {
    .Call(`_scop_cvNetLogC`, X, y, alpha, lambda, nlambda, wbeta, wbetai, Omega, loc, nadj, p, N0, thresh, maxit, XF, yF, NF, threshP)
}

scissor_gaussian_net_fit_cpp <- function(x, y, omega, alpha, lambda = NULL, nlambda = 100L, foldid = NULL, inzero = TRUE, isd = FALSE, thresh = 1e-7, maxit = 100000L, threshP = 1e-5) {
    .Call(`_scop_scissor_gaussian_net_fit_cpp`, x, y, omega, alpha, lambda, nlambda, foldid, inzero, isd, thresh, maxit, threshP)
}

scissor_binomial_net_fit_cpp <- function(x, y, omega, alpha, lambda = NULL, nlambda = 100L, foldid = NULL, inzero = TRUE, isd = FALSE, thresh = 1e-7, maxit = 100000L, threshP = 1e-5) {
    .Call(`_scop_scissor_binomial_net_fit_cpp`, x, y, omega, alpha, lambda, nlambda, foldid, inzero, isd, thresh, maxit, threshP)
}

spatial_gradient_screening_cpp <- function(expr, coords, reference_spots, trajectory, variables, mode, n_bins = 50L, n_random = 0L, seed = 123L, min_spots = 3L) {
    .Call(`_scop_spatial_gradient_screening_cpp`, expr, coords, reference_spots, trajectory, variables, mode, n_bins, n_random, seed, min_spots)
}

parallel_all_in_one_dgc <- function(x_sexp, groups, group_sizes) {
    .Call(`_scop_parallel_all_in_one_dgc`, x_sexp, groups, group_sizes)
}

annoy_build_search <- function(data, k, n_trees, cores) {
    .Call(`_scop_annoy_build_search`, data, k, n_trees, cores)
}

exact_knn_f32 <- function(data, k, cores) {
    .Call(`_scop_exact_knn_f32`, data, k, cores)
}

log_normalize_dgc <- function(mat, scale_factor, grain_size = 100L) {
    invisible(.Call(`_scop_log_normalize_dgc`, mat, scale_factor, grain_size))
}

pca_backend_run <- function(X, npcs, weight_by_var = TRUE) {
    .Call(`_scop_pca_backend_run`, X, npcs, weight_by_var)
}

scale_sparse_full <- function(sparse_mat, gene_indices, scale_max) {
    .Call(`_scop_scale_sparse_full`, sparse_mat, gene_indices, scale_max)
}

csc_to_csr <- function(csc_i, csc_p, csc_x, nrow, ncol) {
    .Call(`_scop_csc_to_csr`, csc_i, csc_p, csc_x, nrow, ncol)
}

sct_stats_correct_sparse <- function(intercepts, cell_mu_base, csr_row_ptr, csr_col_idx, csr_vals, gene_idx, theta, corr_factor, min_var, clip_lo, clip_hi, do_correct) {
    .Call(`_scop_sct_stats_correct_sparse`, intercepts, cell_mu_base, csr_row_ptr, csr_col_idx, csr_vals, gene_idx, theta, corr_factor, min_var, clip_lo, clip_hi, do_correct)
}

sct_fused_resid_center_sparse <- function(intercepts, cell_mu_base, csr_row_ptr, csr_col_idx, csr_vals, gene_idx, theta, min_var, wide_clip_lo, wide_clip_hi, narrow_clip_lo, narrow_clip_hi) {
    .Call(`_scop_sct_fused_resid_center_sparse`, intercepts, cell_mu_base, csr_row_ptr, csr_col_idx, csr_vals, gene_idx, theta, min_var, wide_clip_lo, wide_clip_hi, narrow_clip_lo, narrow_clip_hi)
}

tage_elastic_net_predict_cpp <- function(expr, feature_match, imputer, center, scale, coef, intercept) {
    .Call(`_scop_tage_elastic_net_predict_cpp`, expr, feature_match, imputer, center, scale, coef, intercept)
}

sparse_row_mean_var <- function(p, i, x, nrow, ncol) {
    .Call(`_scop_sparse_row_mean_var`, p, i, x, nrow, ncol)
}

sparse_row_mean_var_dgc_list <- function(mats, nrow) {
    .Call(`_scop_sparse_row_mean_var_dgc_list`, mats, nrow)
}

sparse_row_var_std <- function(p, i, x, nrow, ncol, mu, sd, vmax, nnzPerRow) {
    .Call(`_scop_sparse_row_var_std`, p, i, x, nrow, ncol, mu, sd, vmax, nnzPerRow)
}

sparse_row_var_std_dgc_list <- function(mats, nrow, mu, sd, vmax) {
    .Call(`_scop_sparse_row_var_std_dgc_list`, mats, nrow, mu, sd, vmax)
}

