# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

classification_metrics_cpp <- function(predicted, truth, classes, rare_threshold = 0.05) {
    .Call(`_scop_classification_metrics_cpp`, predicted, truth, classes, rare_threshold)
}

cytotrace2_ensemble_predict <- function(rank_data, log2_data, parameter_dict, cores = 1L) {
    .Call(`_scop_cytotrace2_ensemble_predict`, rank_data, log2_data, parameter_dict, cores)
}

cytotrace2_diffusion_smooth <- function(log2_data, raw_scores, smooth_groups) {
    .Call(`_scop_cytotrace2_diffusion_smooth`, log2_data, raw_scores, smooth_groups)
}

cytotrace2_bin_data <- function(smoothed_scores, categories, category_labels) {
    .Call(`_scop_cytotrace2_bin_data`, smoothed_scores, categories, category_labels)
}

cytotrace2_knn_smooth <- function(pca_coords, preKNN_scores, preKNN_potency, cores = 1L, seed = 14L) {
    .Call(`_scop_cytotrace2_knn_smooth`, pca_coords, preKNN_scores, preKNN_potency, cores, seed)
}

cytotrace2_main <- function(rank_data, log2_data, parameter_dict, smooth_groups, cores, seed, pca_coords) {
    .Call(`_scop_cytotrace2_main`, rank_data, log2_data, parameter_dict, smooth_groups, cores, seed, pca_coords)
}

aucell_auc_sparse_cpp <- function(expr, gene_sets, auc_max_rank, norm_auc = TRUE, strategy = 1L) {
    .Call(`_scop_aucell_auc_sparse_cpp`, expr, gene_sets, auc_max_rank, norm_auc, strategy)
}

ora_hypergeom_cpp <- function(genes, term_ids, term_genes, term_name_ids, term_names, min_size = 10L, max_size = 2147483647L) {
    .Call(`_scop_ora_hypergeom_cpp`, genes, term_ids, term_genes, term_name_ids, term_names, min_size, max_size)
}

module_score_sparse_cpp <- function(expr, feature_sets, control_sets) {
    .Call(`_scop_module_score_sparse_cpp`, expr, feature_sets, control_sets)
}

proportion_permutation_cpp <- function(sample_ids, cluster_ids, cluster_levels, n_permutations, pseudocount = 1e-8) {
    .Call(`_scop_proportion_permutation_cpp`, sample_ids, cluster_ids, cluster_levels, n_permutations, pseudocount)
}

ssgsea_rank_dense_cpp <- function(expr, gene_sets, alpha = 0.25, normalize = TRUE) {
    .Call(`_scop_ssgsea_rank_dense_cpp`, expr, gene_sets, alpha, normalize)
}

zscore_dense_cpp <- function(expr, gene_sets, min_size = 1L, max_size = 2147483647L) {
    .Call(`_scop_zscore_dense_cpp`, expr, gene_sets, min_size, max_size)
}

plage_dense_cpp <- function(expr, gene_sets, min_size = 1L, max_size = 2147483647L) {
    .Call(`_scop_plage_dense_cpp`, expr, gene_sets, min_size, max_size)
}

gsva_gaussian_dense_cpp <- function(expr, gene_sets, max_diff = TRUE, abs_ranking = FALSE, tau = 1.0, chunk_size = 0L) {
    .Call(`_scop_gsva_gaussian_dense_cpp`, expr, gene_sets, max_diff, abs_ranking, tau, chunk_size)
}

gsva_poisson_dense_cpp <- function(expr, gene_sets, max_diff = TRUE, abs_ranking = FALSE, tau = 1.0, chunk_size = 0L) {
    .Call(`_scop_gsva_poisson_dense_cpp`, expr, gene_sets, max_diff, abs_ranking, tau, chunk_size)
}

wilcox_rank_sum_sparse_cpp <- function(mat, n_group1, min_expression = 0.0) {
    .Call(`_scop_wilcox_rank_sum_sparse_cpp`, mat, n_group1, min_expression)
}

wilcox_rank_sum_sparse_all_cells_cpp <- function(mat, n_group1) {
    .Call(`_scop_wilcox_rank_sum_sparse_all_cells_cpp`, mat, n_group1)
}

sparse_topk_by_column_cpp <- function(mat, k, decreasing = TRUE) {
    .Call(`_scop_sparse_topk_by_column_cpp`, mat, k, decreasing)
}

dense_topk_by_column_cpp <- function(mat, k, decreasing = FALSE) {
    .Call(`_scop_dense_topk_by_column_cpp`, mat, k, decreasing)
}

proportion_bootstrap_log2fd_cpp <- function(v1, v2, n_bootstrap = 1000L, pseudocount = 1e-5) {
    .Call(`_scop_proportion_bootstrap_log2fd_cpp`, v1, v2, n_bootstrap, pseudocount)
}

proportion_bootstrap_stats_cpp <- function(v1, v2, n_bootstrap = 1000L, pseudocount = 1e-5) {
    .Call(`_scop_proportion_bootstrap_stats_cpp`, v1, v2, n_bootstrap, pseudocount)
}

pseudotime_velocity_knn_cpp <- function(x_emb, pseudotime, neighbors, normalize = TRUE) {
    .Call(`_scop_pseudotime_velocity_knn_cpp`, x_emb, pseudotime, neighbors, normalize)
}

pseudotime_velocity_gradient_cpp <- function(x_emb, pseudotime, neighbors, smooth = 0.5, normalize = TRUE) {
    .Call(`_scop_pseudotime_velocity_gradient_cpp`, x_emb, pseudotime, neighbors, smooth, normalize)
}

sctenifold_pcnet_covariance_raw_cpp <- function(x, n_comp = 3L, ncv = 0L, maxit = 1000L, tol = 1e-10, n_threads = 1L) {
    .Call(`_scop_sctenifold_pcnet_covariance_raw_cpp`, x, n_comp, ncv, maxit, tol, n_threads)
}

sctenifold_pcnet_covariance_sparse_cpp <- function(x, n_comp = 3L, scale_scores = TRUE, symmetric = FALSE, q = 0.0, ncv = 0L, maxit = 1000L, tol = 1e-10, n_threads = 1L) {
    .Call(`_scop_sctenifold_pcnet_covariance_sparse_cpp`, x, n_comp, scale_scores, symmetric, q, ncv, maxit, tol, n_threads)
}

sctenifold_tensor_decomposition_cpp <- function(x_list, init_u, max_iter = 1000L, tol = 1e-5) {
    .Call(`_scop_sctenifold_tensor_decomposition_cpp`, x_list, init_u, max_iter, tol)
}

sctenifold_strict_direction_cpp <- function(x, lambda = 1.0) {
    .Call(`_scop_sctenifold_strict_direction_cpp`, x, lambda)
}

sctenifold_manifold_matrix_cpp <- function(x, y) {
    .Call(`_scop_sctenifold_manifold_matrix_cpp`, x, y)
}

sctenifold_pair_distances_cpp <- function(aligned) {
    .Call(`_scop_sctenifold_pair_distances_cpp`, aligned)
}

