#' @title scTenifoldKnk Plot
#'
#' @description
#' Visualize in-silico knockout results generated by [RunscTenifoldKnk].
#'
#' @md
#' @inheritParams thisutils::log_message
#' @param srt A Seurat object containing a scTenifoldKnk result in
#' `srt@tools`.
#' @param tool_name Name of the `srt@tools` entry created by
#' [RunscTenifoldKnk].
#' @param plot_type Plot type. `"qq"` shows the common scTenifoldKnk
#' `FC` versus theoretical chi-square quantile plot. `"effect"` ranks top
#' perturbed genes by `FC`. `"network"` draws a knockout-centered WT network
#' subgraph from saved tensor networks using [thisplot::GraphPlot].
#' `"manifold"` draws paired WT-to-KO
#' displacement arrows for selected genes in the non-linear manifold alignment
#' space, showing how each gene's network context shifts after virtual knockout.
#' @param top_n Number of top genes to show or label.
#' @param FDR_threshold Adjusted p-value cutoff used to mark significant genes.
#' @param FC_threshold FC cutoff used to mark significant genes.
#' @param features Character vector of genes to show or label. For
#' `plot_type = "network"` and `"manifold"`, these genes are included in the
#' displayed subset when present.
#' @param label Whether to label genes.
#' @param nlabel Number of labels to add when `features = NULL`.
#' @param pt.size Point size.
#' @param pt.alpha Point transparency.
#' @param label.size Label text size.
#' @param edge_top_n Maximum number of network edges to draw.
#' @param edge_threshold Minimum absolute edge weight for
#' `plot_type = "network"`. If `NULL`, the largest `edge_top_n` edges are used.
#' @param arrow.length Arrow head length for `plot_type = "manifold"`.
#' @param arrow.linewidth Arrow line width for `plot_type = "manifold"`.
#' @param arrow.alpha Arrow transparency for `plot_type = "manifold"`.
#' @param start.pt.size WT-position point size for `plot_type = "manifold"`.
#' @param end.pt.size KO-position point size for `plot_type = "manifold"`.
#' @param manifold.aspect.ratio Panel aspect ratio for
#' `plot_type = "manifold"`. Default `1` keeps the panel square.
#' Set `NULL` to use the device aspect ratio.
#' @param cols.sig Color for significant genes.
#' @param cols.ns Color for non-significant genes.
#' @param cols.ko Color for knocked-out genes.
#' @param xlab,ylab Axis labels.
#' @param title Plot title. If `NULL`, a default title is used.
#' @param theme_use Theme function used to style the plot.
#' @param theme_args Other arguments passed to `theme_use`.
#'
#' @return A `ggplot` object.
#' @export
#'
#' @examples
#' data(pancreas_sub)
#' gene_use <- "Pdx1"
#' counts <- GetAssayData5(pancreas_sub, assay = "RNA", layer = "counts")
#' detected <- names(sort(Matrix::rowSums(counts > 0), decreasing = TRUE))
#' features_use <- unique(c(gene_use, head(detected, 300)))
#'
#' pancreas_sub <- RunscTenifoldKnk(
#'   pancreas_sub,
#'   gKO = gene_use,
#'   features = features_use,
#'   qc = FALSE,
#'   nc_nNet = 3,
#'   nc_nCells = 200,
#'   td_maxIter = 200,
#'   store_networks = TRUE,
#'   store_manifold = TRUE
#' )
#'
#' scTenifoldKnkPlot(pancreas_sub, plot_type = "qq")
#'
#' scTenifoldKnkPlot(pancreas_sub, plot_type = "effect")
#'
#' scTenifoldKnkPlot(pancreas_sub, plot_type = "network")
#'
#' scTenifoldKnkPlot(pancreas_sub, plot_type = "manifold")
scTenifoldKnkPlot <- function(
  srt,
  tool_name = "scTenifoldKnk",
  plot_type = c("qq", "effect", "network", "manifold"),
  top_n = 20,
  FDR_threshold = 0.05,
  FC_threshold = 1,
  features = NULL,
  label = TRUE,
  nlabel = 10,
  pt.size = 2,
  pt.alpha = 0.85,
  label.size = 3.5,
  edge_top_n = 100,
  edge_threshold = NULL,
  arrow.length = 0.14,
  arrow.linewidth = 0.8,
  arrow.alpha = 0.8,
  start.pt.size = 2.2,
  end.pt.size = 3,
  manifold.aspect.ratio = 1,
  cols.sig = "#D7301F",
  cols.ns = "grey70",
  cols.ko = "#542788",
  xlab = NULL,
  ylab = NULL,
  title = NULL,
  theme_use = "theme_scop",
  theme_args = list(),
  verbose = TRUE
) {
  plot_type <- match.arg(plot_type)
  if (!inherits(srt, "Seurat")) {
    log_message(
      "{.arg srt} must be a {.cls Seurat} object",
      message_type = "error"
    )
  }
  if (!tool_name %in% names(srt@tools)) {
    log_message(
      "Cannot find scTenifoldKnk result {.val {tool_name}} in {.code srt@tools}",
      message_type = "error"
    )
  }
  bundle <- srt@tools[[tool_name]]
  dr <- bundle$diffRegulation %||% bundle$result$diffRegulation
  if (is.null(dr) || !is.data.frame(dr) || nrow(dr) == 0L) {
    log_message(
      "No valid {.field diffRegulation} table found in scTenifoldKnk result",
      message_type = "error"
    )
  }
  required <- c("gene", "FC", "p.adj")
  missing_required <- setdiff(required, colnames(dr))
  if (length(missing_required) > 0L) {
    log_message(
      "{.field diffRegulation} is missing required columns: {.val {missing_required}}",
      message_type = "error"
    )
  }
  dr <- as.data.frame(dr)
  dr$gene <- as.character(dr$gene)
  dr$FC <- suppressWarnings(as.numeric(dr$FC))
  dr$p.adj <- suppressWarnings(as.numeric(dr$p.adj))
  dr$significant <- !is.na(dr$p.adj) &
    !is.na(dr$FC) &
    dr$p.adj < FDR_threshold &
    dr$FC >= FC_threshold
  dr$status <- ifelse(
    dr$gene %in% bundle$parameters$gKO,
    "Knockout",
    ifelse(dr$significant, "Significant", "NS")
  )
  dr$status <- factor(dr$status, levels = c("Knockout", "Significant", "NS"))
  top_n <- suppressWarnings(as.integer(top_n[1]))
  if (is.na(top_n) || top_n < 1L) {
    log_message(
      "{.arg top_n} must be a positive integer",
      message_type = "error"
    )
  }
  nlabel <- suppressWarnings(as.integer(nlabel[1]))
  if (is.na(nlabel) || nlabel < 0L) {
    log_message(
      "{.arg nlabel} must be a non-negative integer",
      message_type = "error"
    )
  }
  edge_top_n <- suppressWarnings(as.integer(edge_top_n[1]))
  if (is.na(edge_top_n) || edge_top_n < 1L) {
    log_message(
      "{.arg edge_top_n} must be a positive integer",
      message_type = "error"
    )
  }

  plot_fun <- switch(
    plot_type,
    qq = sctenifold_plot_qq,
    effect = sctenifold_plot_effect,
    network = sctenifold_plot_network,
    manifold = sctenifold_plot_manifold
  )
  plot_fun(
    bundle = bundle,
    dr = dr,
    top_n = top_n,
    FDR_threshold = FDR_threshold,
    FC_threshold = FC_threshold,
    features = features,
    label = label,
    nlabel = nlabel,
    pt.size = pt.size,
    pt.alpha = pt.alpha,
    label.size = label.size,
    edge_top_n = edge_top_n,
    edge_threshold = edge_threshold,
    arrow.length = arrow.length,
    arrow.linewidth = arrow.linewidth,
    arrow.alpha = arrow.alpha,
    start.pt.size = start.pt.size,
    end.pt.size = end.pt.size,
    manifold.aspect.ratio = manifold.aspect.ratio,
    cols.sig = cols.sig,
    cols.ns = cols.ns,
    cols.ko = cols.ko,
    xlab = xlab,
    ylab = ylab,
    title = title,
    theme_use = theme_use,
    theme_args = theme_args,
    verbose = verbose
  )
}

sctenifold_plot_theme <- function(theme_use, theme_args = list()) {
  if (is.null(theme_use)) {
    return(ggplot2::theme())
  }
  if (inherits(theme_use, "theme")) {
    return(theme_use)
  }
  theme_fun <- if (is.character(theme_use)) {
    get(theme_use, mode = "function", inherits = TRUE)
  } else if (is.function(theme_use)) {
    theme_use
  } else {
    log_message(
      "{.arg theme_use} must be a theme object, function, function name, or NULL",
      message_type = "error"
    )
  }
  do.call(theme_fun, theme_args)
}

sctenifold_status_colors <- function(cols.sig, cols.ns, cols.ko) {
  c(Knockout = cols.ko, Significant = cols.sig, NS = cols.ns)
}

sctenifold_label_genes <- function(dr, features, nlabel) {
  if (!is.null(features)) {
    return(intersect(as.character(features), dr$gene))
  }
  if (nlabel == 0L) {
    return(character())
  }
  head(dr$gene[order(dr$FC, decreasing = TRUE)], nlabel)
}

sctenifold_plot_qq <- function(
  bundle,
  dr,
  top_n,
  features,
  label,
  nlabel,
  pt.size,
  pt.alpha,
  label.size,
  cols.sig,
  cols.ns,
  cols.ko,
  xlab,
  ylab,
  title,
  theme_use,
  theme_args,
  ...
) {
  dr <- dr[order(dr$FC, decreasing = TRUE), , drop = FALSE]
  dr$chisq_quantile <- sort(
    stats::qchisq(stats::ppoints(nrow(dr)), df = 1),
    decreasing = TRUE
  )
  p <- ggplot2::ggplot(
    dr,
    ggplot2::aes(x = chisq_quantile, y = FC, color = status)
  ) +
    ggplot2::geom_abline(
      slope = 1,
      intercept = 0,
      linetype = "dashed",
      color = "grey55",
      linewidth = 0.4
    ) +
    ggplot2::geom_point(size = pt.size, alpha = pt.alpha) +
    ggplot2::scale_color_manual(values = sctenifold_status_colors(cols.sig, cols.ns, cols.ko), drop = FALSE) +
    ggplot2::labs(
      x = xlab %||% "Expected chi-square quantiles",
      y = ylab %||% "Observed FC",
      color = NULL,
      title = title %||% "scTenifoldKnk differential regulation"
    ) +
    sctenifold_plot_theme(theme_use, theme_args)
  if (isTRUE(label)) {
    label_df <- dr[dr$gene %in% sctenifold_label_genes(dr, features, min(nlabel, top_n)), , drop = FALSE]
    if (nrow(label_df) > 0L) {
      p <- p + ggrepel::geom_text_repel(
        data = label_df,
        ggplot2::aes(x = chisq_quantile, y = FC, label = gene),
        inherit.aes = FALSE,
        size = label.size,
        max.overlaps = Inf,
        box.padding = 0.35,
        show.legend = FALSE
      )
    }
  }
  p
}

sctenifold_plot_effect <- function(
  bundle,
  dr,
  top_n,
  features,
  label,
  nlabel,
  pt.size,
  label.size,
  cols.sig,
  cols.ns,
  cols.ko,
  xlab,
  ylab,
  title,
  theme_use,
  theme_args,
  ...
) {
  genes_use <- sctenifold_label_genes(dr, features, top_n)
  plot_df <- dr[dr$gene %in% genes_use, , drop = FALSE]
  plot_df <- plot_df[order(plot_df$FC, decreasing = FALSE), , drop = FALSE]
  plot_df$gene <- factor(plot_df$gene, levels = plot_df$gene)
  p <- ggplot2::ggplot(plot_df, ggplot2::aes(x = FC, y = gene, color = status)) +
    ggplot2::geom_segment(
      ggplot2::aes(x = 0, xend = FC, yend = gene),
      linewidth = 0.5,
      color = "grey75"
    ) +
    ggplot2::geom_point(size = pt.size + 0.8) +
    ggplot2::scale_color_manual(values = sctenifold_status_colors(cols.sig, cols.ns, cols.ko), drop = FALSE) +
    ggplot2::labs(
      x = xlab %||% "FC",
      y = ylab %||% NULL,
      color = NULL,
      title = title %||% "Top scTenifoldKnk effects"
    ) +
    sctenifold_plot_theme(theme_use, theme_args)
  if (isTRUE(label)) {
    p <- p + ggplot2::geom_text(
      ggplot2::aes(label = sprintf("%.2f", FC)),
      hjust = -0.15,
      size = label.size,
      show.legend = FALSE
    ) +
      ggplot2::expand_limits(x = max(plot_df$FC, na.rm = TRUE) * 1.12)
  }
  p
}

sctenifold_plot_network <- function(
  bundle,
  dr,
  top_n,
  features,
  label,
  pt.size,
  label.size,
  edge_top_n,
  edge_threshold,
  cols.sig,
  cols.ns,
  cols.ko,
  title,
  theme_use,
  theme_args,
  ...
) {
  networks <- bundle$result$tensorNetworks %||% bundle$tensorNetworks
  wt <- networks$WT
  if (is.null(wt)) {
    log_message(
      "{.val network} plot requires {.arg store_networks = TRUE} in {.fun RunscTenifoldKnk}",
      message_type = "error"
    )
  }
  wt <- as.matrix(wt)
  genes_use <- unique(c(bundle$parameters$gKO, sctenifold_label_genes(dr, features, top_n)))
  genes_use <- intersect(genes_use, intersect(rownames(wt), colnames(wt)))
  if (length(genes_use) < 2L) {
    log_message(
      "At least two retained genes are required for {.val network} plot",
      message_type = "error"
    )
  }
  sub_wt <- wt[genes_use, genes_use, drop = FALSE]
  edge_idx <- which(is.finite(sub_wt) & sub_wt != 0, arr.ind = TRUE)
  edge_df <- data.frame(
    from = rownames(sub_wt)[edge_idx[, 1]],
    to = colnames(sub_wt)[edge_idx[, 2]],
    weight = sub_wt[edge_idx],
    stringsAsFactors = FALSE
  )
  edge_df <- edge_df[edge_df$from != edge_df$to, , drop = FALSE]
  edge_df$abs_weight <- abs(edge_df$weight)
  if (!is.null(edge_threshold)) {
    edge_df <- edge_df[edge_df$abs_weight >= edge_threshold, , drop = FALSE]
  }
  edge_df <- edge_df[order(edge_df$abs_weight, decreasing = TRUE), , drop = FALSE]
  edge_df <- head(edge_df, edge_top_n)
  if (nrow(edge_df) == 0L) {
    log_message(
      "No network edges passed the current filter",
      message_type = "error"
    )
  }
  node_df <- dr[match(genes_use, dr$gene), c("gene", "status", "FC"), drop = FALSE]
  node_df <- node_df[!is.na(node_df$gene), , drop = FALSE]
  graph <- igraph::graph_from_data_frame(edge_df, directed = TRUE, vertices = node_df)
  layout <- igraph::layout_with_fr(graph, weights = igraph::E(graph)$abs_weight)
  node_plot <- data.frame(
    gene = igraph::V(graph)$name,
    x = layout[, 1],
    y = layout[, 2],
    stringsAsFactors = FALSE
  )
  node_plot <- merge(node_plot, node_df, by = "gene", all.x = TRUE, sort = FALSE)
  fc_range <- range(node_plot$FC, na.rm = TRUE)
  if (!all(is.finite(fc_range)) || diff(fc_range) == 0) {
    node_plot$node_size <- pt.size + 3
  } else {
    node_plot$node_size <- (node_plot$FC - fc_range[1]) / diff(fc_range) * 4 + pt.size + 1
  }
  rownames(node_plot) <- node_plot$gene

  edge_mat <- matrix(
    0,
    nrow = nrow(node_plot),
    ncol = nrow(node_plot),
    dimnames = list(rownames(node_plot), rownames(node_plot))
  )
  edge_df <- edge_df[edge_df$from %in% rownames(edge_mat) & edge_df$to %in% colnames(edge_mat), , drop = FALSE]
  edge_mat[cbind(edge_df$from, edge_df$to)] <- edge_df$abs_weight

  p <- thisplot::GraphPlot(
    node = node_plot,
    edge = edge_mat,
    node_coord = c("x", "y"),
    node_group = "status",
    node_palcolor = sctenifold_status_colors(cols.sig, cols.ns, cols.ko),
    node_size = "node_size",
    node_alpha = 0.95,
    node_highlight = bundle$parameters$gKO,
    node_highlight_color = cols.ko,
    label = FALSE,
    edge_threshold = 0,
    use_triangular = "both",
    edge_line = "straight",
    edge_color = "grey45",
    edge_size = c(0.25, 1.8),
    edge_alpha = 0.55,
    aspect.ratio = 1,
    title = title %||% "scTenifoldKnk WT network",
    xlab = NULL,
    ylab = NULL,
    legend.position = "right",
    theme_use = theme_use,
    theme_args = theme_args
  )
  if (isTRUE(label)) {
    p <- p + ggrepel::geom_text_repel(
      data = node_plot,
      ggplot2::aes(x = x, y = y, label = gene),
      inherit.aes = FALSE,
      size = label.size,
      color = "black",
      bg.color = "white",
      bg.r = 0.1,
      max.overlaps = Inf,
      box.padding = 0.35,
      show.legend = FALSE
    )
  }
  p
}

sctenifold_plot_manifold <- function(
  bundle,
  dr,
  top_n,
  features,
  label,
  label.size,
  arrow.length,
  arrow.linewidth,
  arrow.alpha,
  start.pt.size,
  end.pt.size,
  manifold.aspect.ratio,
  cols.sig,
  cols.ns,
  cols.ko,
  xlab,
  ylab,
  title,
  theme_use,
  theme_args,
  ...
) {
  ma <- bundle$result$manifoldAlignment %||% bundle$manifoldAlignment
  if (is.null(ma)) {
    log_message(
      "{.val manifold} plot requires {.arg store_manifold = TRUE} in {.fun RunscTenifoldKnk}",
      message_type = "error"
    )
  }
  ma <- as.matrix(ma)
  if (ncol(ma) < 2L || nrow(ma) %% 2L != 0L) {
    log_message(
      "Unexpected scTenifoldKnk manifold-alignment matrix",
      message_type = "error"
    )
  }
  n_genes <- nrow(ma) / 2L
  x_names <- rownames(ma)[seq_len(n_genes)]
  y_names <- rownames(ma)[seq.int(n_genes + 1L, nrow(ma))]
  genes <- sub("^X_", "", x_names)
  if (!identical(genes, sub("^Y_", "", y_names))) {
    log_message(
      "Genes are not ordered as expected in scTenifoldKnk manifold output",
      message_type = "error"
    )
  }
  plot_df <- data.frame(
    gene = genes,
    x = ma[seq_len(n_genes), 1],
    y = ma[seq_len(n_genes), 2],
    xend = ma[seq.int(n_genes + 1L, nrow(ma)), 1],
    yend = ma[seq.int(n_genes + 1L, nrow(ma)), 2],
    stringsAsFactors = FALSE
  )
  plot_df <- merge(plot_df, dr[, c("gene", "status", "FC")], by = "gene", all.x = TRUE, sort = FALSE)
  genes_use <- unique(c(bundle$parameters$gKO, sctenifold_label_genes(dr, features, top_n)))
  plot_df <- plot_df[plot_df$gene %in% genes_use, , drop = FALSE]
  if (nrow(plot_df) == 0L) {
    log_message(
      "No genes available for {.val manifold} plot",
      message_type = "error"
    )
  }
  p <- ggplot2::ggplot(plot_df) +
    ggplot2::geom_segment(
      ggplot2::aes(x = x, y = y, xend = xend, yend = yend),
      arrow = grid::arrow(length = grid::unit(arrow.length, "inches"), type = "closed"),
      linewidth = arrow.linewidth,
      color = "grey35",
      alpha = arrow.alpha,
      lineend = "round"
    ) +
    ggplot2::geom_point(
      ggplot2::aes(x = x, y = y),
      shape = 21,
      fill = "white",
      color = "grey45",
      stroke = 0.7,
      size = start.pt.size
    ) +
    ggplot2::geom_point(ggplot2::aes(x = xend, y = yend, color = status, size = FC), alpha = 0.95) +
    ggplot2::scale_color_manual(values = sctenifold_status_colors(cols.sig, cols.ns, cols.ko), drop = FALSE) +
    ggplot2::scale_size_continuous(range = c(end.pt.size, end.pt.size + 4), guide = "none") +
    ggplot2::labs(
      x = xlab %||% "NLMA 1",
      y = ylab %||% "NLMA 2",
      color = NULL,
      title = title %||% "scTenifoldKnk manifold displacement"
    ) +
    sctenifold_plot_theme(theme_use, theme_args) +
    ggplot2::theme(aspect.ratio = manifold.aspect.ratio)
  if (isTRUE(label)) {
    p <- p + ggrepel::geom_text_repel(
      ggplot2::aes(x = xend, y = yend, label = gene),
      size = label.size,
      max.overlaps = Inf,
      box.padding = 0.35,
      show.legend = FALSE
    )
  }
  p
}
